/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import41 from '@angular/core/src/di/injector';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import73 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const LoginNgFactory: import73.ComponentFactory<import1.Login>;
export declare function viewFactory_Login0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Login>;
export declare const AccountNgFactory: import73.ComponentFactory<import1.Account>;
export declare function viewFactory_Account0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Account>;
export declare const DashboardNgFactory: import73.ComponentFactory<import1.Dashboard>;
export declare function viewFactory_Dashboard0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Dashboard>;
export declare const ProfileNgFactory: import73.ComponentFactory<import1.Profile>;
export declare function viewFactory_Profile0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Profile>;
export declare const E2EAppNgFactory: import73.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EApp>;
