/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../../dist/components/app/app';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '../../../dist/ionic-module';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '../../../dist/components/action-sheet/action-sheet';
import * as import23 from '../../../dist/components/alert/alert';
import * as import24 from '../../../dist/util/form';
import * as import25 from '../../../dist/util/feature-detect';
import * as import26 from '../../../dist/gestures/gesture-controller';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '../../../dist/util/keyboard';
import * as import32 from '../../../dist/components/loading/loading';
import * as import33 from '../../../dist/components/menu/menu-controller';
import * as import34 from '../../../dist/components/modal/modal';
import * as import35 from '../../../dist/components/picker/picker';
import * as import36 from '../../../dist/components/popover/popover';
import * as import37 from '../../../dist/components/tap-click/tap-click';
import * as import38 from '../../../dist/components/toast/toast';
import * as import39 from '../../../dist/translation/translate';
import * as import40 from '../../../dist/transitions/transition-controller';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../../../dist/components/app/app-root.d.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/http/http';
import * as import49 from '../../../dist/providers';
import * as import50 from '../../../dist/platform/query-params';
import * as import51 from '../../../dist/platform/platform';
import * as import52 from '../../../dist/config/config';
import * as import53 from '../../../dist/util/events';
import * as import54 from '@angular/core/src/console';
import * as import55 from '@angular/core/src/facade/exception_handler';
import * as import56 from '@angular/core/src/linker/component_resolver';
import * as import57 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import58 from '@angular/platform-browser/src/dom/animation_driver';
import * as import59 from '@angular/core/src/render/api';
import * as import60 from '@angular/core/src/security';
import * as import61 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import62 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import63 from '../../../dist/components/app/app-root';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/core/src/render/api';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import70 from '@angular/core/src/linker/view_type';
import * as import71 from '@angular/core/src/change_detection/change_detection';
import * as import72 from '@angular/core/src/linker/component_factory';
import * as import73 from '../../../dist/components/toolbar/toolbar';
import * as import74 from '../../../dist/components/toolbar/toolbar-title';
import * as import75 from '../../../dist/components/content/content';
import * as import76 from '../../../dist/components/list/list';
import * as import77 from '../../../dist/components/item/item';
import * as import78 from '@angular/core/src/linker/query_list';
import * as import79 from '../../../dist/components/input/input';
import * as import80 from '../../../dist/components/icon/icon';
import * as import81 from '../../../dist/components/nav/view-controller';
import * as import82 from '../../../dist/components/toolbar/toolbar.d.ngfactory';
import * as import83 from '@angular/core/src/linker/element_ref';
import * as import84 from '../../../dist/components/toolbar/toolbar-title.d.ngfactory';
import * as import85 from '../../../dist/components/navbar/navbar';
import * as import86 from '../../../dist/components/content/content.d.ngfactory';
import * as import87 from '../../../dist/components/tabs/tabs';
import * as import88 from '../../../dist/components/item/item.d.ngfactory';
import * as import89 from '../../../dist/components/input/input.d.ngfactory';
import * as import90 from '../../../dist/components/nav/nav-controller';
import * as import91 from '@angular/forms/src/directives/ng_control';
import * as import92 from '@angular/core/src/metadata/view';
import * as import93 from '../../../dist/components/nav/nav';
import * as import94 from '../../../dist/components/nav/nav.d.ngfactory';
import * as import95 from '../../../dist/components/nav/nav-controller-base';
import * as import96 from '@angular/core/src/linker/component_factory_resolver';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _ExceptionHandler_6:any;
  _UserUrl_7:any;
  _QueryParams_8:any;
  _UserAgent_9:any;
  _UserNavigatorPlatform_10:any;
  _Platform_11:any;
  _UserConfig_12:any;
  _Config_13:any;
  _App_14:import7.App;
  _APP_INITIALIZER_15:any[];
  _ApplicationInitStatus_16:import8.ApplicationInitStatus;
  _Testability_17:import9.Testability;
  _ApplicationRef__18:import10.ApplicationRef_;
  _ApplicationRef_19:any;
  _IonicModule_20:import11.IonicModule;
  _AppModule_21:import1.AppModule;
  __Compiler_22:import12.Compiler;
  __ComponentResolver_23:any;
  __APP_ID_24:any;
  __DOCUMENT_25:any;
  __HAMMER_GESTURE_CONFIG_26:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_27:any[];
  __EventManager_28:import14.EventManager;
  __DomSharedStylesHost_29:import15.DomSharedStylesHost;
  __AnimationDriver_30:any;
  __DomRootRenderer_31:import16.DomRootRenderer_;
  __RootRenderer_32:any;
  __DomSanitizationService_33:import17.DomSanitizationServiceImpl;
  __SanitizationService_34:any;
  __ViewUtils_35:import18.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DynamicComponentLoader_38:import19.DynamicComponentLoader_;
  __SharedStylesHost_39:any;
  __RadioControlRegistry_40:import20.RadioControlRegistry;
  __FormBuilder_41:import21.FormBuilder;
  __UserRoot_42:any;
  __ActionSheetController_43:import22.ActionSheetController;
  __AlertController_44:import23.AlertController;
  __Form_45:import24.Form;
  __FeatureDetect_46:import25.FeatureDetect;
  __GestureController_47:import26.GestureController;
  __BrowserXhr_48:import27.BrowserXhr;
  __ResponseOptions_49:import28.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import29.XHRBackend;
  __RequestOptions_52:import30.BaseRequestOptions;
  __Http_53:any;
  __Keyboard_54:import31.Keyboard;
  __LoadingController_55:import32.LoadingController;
  __MenuController_56:import33.MenuController;
  __ModalController_57:import34.ModalController;
  __PickerController_58:import35.PickerController;
  __PopoverController_59:import36.PopoverController;
  __TapClick_60:import37.TapClick;
  __ToastController_61:import38.ToastController;
  __Translate_62:import39.Translate;
  __TransitionController_63:import40.TransitionController;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.AppRootNgFactory,
      E2EAppNgFactory,
      E2EAppNgFactory,
      E2EPageNgFactory
    ]
    ,[]);
  }
  get _Compiler_22():import12.Compiler {
    if ((this.__Compiler_22 == null)) { (this.__Compiler_22 = new import12.Compiler()); }
    return this.__Compiler_22;
  }
  get _ComponentResolver_23():any {
    if ((this.__ComponentResolver_23 == null)) { (this.__ComponentResolver_23 = this._Compiler_22); }
    return this.__ComponentResolver_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == null)) { (this.__APP_ID_24 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_24;
  }
  get _DOCUMENT_25():any {
    if ((this.__DOCUMENT_25 == null)) { (this.__DOCUMENT_25 = import4._document()); }
    return this.__DOCUMENT_25;
  }
  get _HAMMER_GESTURE_CONFIG_26():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_26 == null)) { (this.__HAMMER_GESTURE_CONFIG_26 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_26;
  }
  get _EVENT_MANAGER_PLUGINS_27():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_27 == null)) { (this.__EVENT_MANAGER_PLUGINS_27 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_26)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_27;
  }
  get _EventManager_28():import14.EventManager {
    if ((this.__EventManager_28 == null)) { (this.__EventManager_28 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_27,this.parent.get(import46.NgZone))); }
    return this.__EventManager_28;
  }
  get _DomSharedStylesHost_29():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_29 == null)) { (this.__DomSharedStylesHost_29 = new import15.DomSharedStylesHost(this._DOCUMENT_25)); }
    return this.__DomSharedStylesHost_29;
  }
  get _AnimationDriver_30():any {
    if ((this.__AnimationDriver_30 == null)) { (this.__AnimationDriver_30 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_30;
  }
  get _DomRootRenderer_31():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_31 == null)) { (this.__DomRootRenderer_31 = new import16.DomRootRenderer_(this._DOCUMENT_25,this._EventManager_28,this._DomSharedStylesHost_29,this._AnimationDriver_30)); }
    return this.__DomRootRenderer_31;
  }
  get _RootRenderer_32():any {
    if ((this.__RootRenderer_32 == null)) { (this.__RootRenderer_32 = import47._createConditionalRootRenderer(this._DomRootRenderer_31)); }
    return this.__RootRenderer_32;
  }
  get _DomSanitizationService_33():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_33 == null)) { (this.__DomSanitizationService_33 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_33;
  }
  get _SanitizationService_34():any {
    if ((this.__SanitizationService_34 == null)) { (this.__SanitizationService_34 = this._DomSanitizationService_33); }
    return this.__SanitizationService_34;
  }
  get _ViewUtils_35():import18.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import18.ViewUtils(this._RootRenderer_32,this._APP_ID_24,this._SanitizationService_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _DynamicComponentLoader_38():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_38 == null)) { (this.__DynamicComponentLoader_38 = new import19.DynamicComponentLoader_(this._Compiler_22)); }
    return this.__DynamicComponentLoader_38;
  }
  get _SharedStylesHost_39():any {
    if ((this.__SharedStylesHost_39 == null)) { (this.__SharedStylesHost_39 = this._DomSharedStylesHost_29); }
    return this.__SharedStylesHost_39;
  }
  get _RadioControlRegistry_40():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _FormBuilder_41():import21.FormBuilder {
    if ((this.__FormBuilder_41 == null)) { (this.__FormBuilder_41 = new import21.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _UserRoot_42():any {
    if ((this.__UserRoot_42 == null)) { (this.__UserRoot_42 = import1.E2EApp); }
    return this.__UserRoot_42;
  }
  get _ActionSheetController_43():import22.ActionSheetController {
    if ((this.__ActionSheetController_43 == null)) { (this.__ActionSheetController_43 = new import22.ActionSheetController(this._App_14)); }
    return this.__ActionSheetController_43;
  }
  get _AlertController_44():import23.AlertController {
    if ((this.__AlertController_44 == null)) { (this.__AlertController_44 = new import23.AlertController(this._App_14)); }
    return this.__AlertController_44;
  }
  get _Form_45():import24.Form {
    if ((this.__Form_45 == null)) { (this.__Form_45 = new import24.Form()); }
    return this.__Form_45;
  }
  get _FeatureDetect_46():import25.FeatureDetect {
    if ((this.__FeatureDetect_46 == null)) { (this.__FeatureDetect_46 = new import25.FeatureDetect()); }
    return this.__FeatureDetect_46;
  }
  get _GestureController_47():import26.GestureController {
    if ((this.__GestureController_47 == null)) { (this.__GestureController_47 = new import26.GestureController(this._App_14)); }
    return this.__GestureController_47;
  }
  get _BrowserXhr_48():import27.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import48._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import29.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import29.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import30.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import48.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _Keyboard_54():import31.Keyboard {
    if ((this.__Keyboard_54 == null)) { (this.__Keyboard_54 = new import31.Keyboard(this._Config_13,this._Form_45,this.parent.get(import46.NgZone))); }
    return this.__Keyboard_54;
  }
  get _LoadingController_55():import32.LoadingController {
    if ((this.__LoadingController_55 == null)) { (this.__LoadingController_55 = new import32.LoadingController(this._App_14)); }
    return this.__LoadingController_55;
  }
  get _MenuController_56():import33.MenuController {
    if ((this.__MenuController_56 == null)) { (this.__MenuController_56 = new import33.MenuController()); }
    return this.__MenuController_56;
  }
  get _ModalController_57():import34.ModalController {
    if ((this.__ModalController_57 == null)) { (this.__ModalController_57 = new import34.ModalController(this._App_14)); }
    return this.__ModalController_57;
  }
  get _PickerController_58():import35.PickerController {
    if ((this.__PickerController_58 == null)) { (this.__PickerController_58 = new import35.PickerController(this._App_14)); }
    return this.__PickerController_58;
  }
  get _PopoverController_59():import36.PopoverController {
    if ((this.__PopoverController_59 == null)) { (this.__PopoverController_59 = new import36.PopoverController(this._App_14)); }
    return this.__PopoverController_59;
  }
  get _TapClick_60():import37.TapClick {
    if ((this.__TapClick_60 == null)) { (this.__TapClick_60 = new import37.TapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))); }
    return this.__TapClick_60;
  }
  get _ToastController_61():import38.ToastController {
    if ((this.__ToastController_61 == null)) { (this.__ToastController_61 = new import38.ToastController(this._App_14)); }
    return this.__ToastController_61;
  }
  get _Translate_62():import39.Translate {
    if ((this.__Translate_62 == null)) { (this.__Translate_62 = new import39.Translate()); }
    return this.__Translate_62;
  }
  get _TransitionController_63():import40.TransitionController {
    if ((this.__TransitionController_63 == null)) { (this.__TransitionController_63 = new import40.TransitionController()); }
    return this.__TransitionController_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._ExceptionHandler_6 = import4._exceptionHandler();
    this._UserUrl_7 = import49.getWindowLocation();
    this._QueryParams_8 = import50.setupQueryParams(this._UserUrl_7);
    this._UserAgent_9 = import49.getWindowUserAgent();
    this._UserNavigatorPlatform_10 = import49.getWindowPlatform();
    this._Platform_11 = import51.setupPlatform(this._QueryParams_8,this._UserAgent_9,this._UserNavigatorPlatform_10,this.parent.get(import46.NgZone));
    this._UserConfig_12 = null;
    this._Config_13 = import52.setupConfig(this._UserConfig_12,this._QueryParams_8,this._Platform_11);
    this._App_14 = new import7.App(this._Config_13,this._Platform_11);
    this._APP_INITIALIZER_15 = [
      import53.setupProvideEvents(this._Platform_11),
      import37.setupTapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))
    ]
    ;
    this._ApplicationInitStatus_16 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_15);
    this._Testability_17 = new import9.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__18 = new import10.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import54.Console),this,this._ExceptionHandler_6,this,this._ApplicationInitStatus_16,this.parent.get(import9.TestabilityRegistry,null),this._Testability_17);
    this._ApplicationRef_19 = this._ApplicationRef__18;
    this._IonicModule_20 = new import11.IonicModule(this.parent.get(import11.IonicModule,null),this._ApplicationRef_19);
    this._AppModule_21 = new import1.AppModule();
    return this._AppModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import55.ExceptionHandler)) { return this._ExceptionHandler_6; }
    if ((token === import50.UserUrl)) { return this._UserUrl_7; }
    if ((token === import50.QueryParams)) { return this._QueryParams_8; }
    if ((token === import51.UserAgent)) { return this._UserAgent_9; }
    if ((token === import51.UserNavigatorPlatform)) { return this._UserNavigatorPlatform_10; }
    if ((token === import51.Platform)) { return this._Platform_11; }
    if ((token === import52.UserConfig)) { return this._UserConfig_12; }
    if ((token === import52.Config)) { return this._Config_13; }
    if ((token === import7.App)) { return this._App_14; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import9.Testability)) { return this._Testability_17; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import11.IonicModule)) { return this._IonicModule_20; }
    if ((token === import1.AppModule)) { return this._AppModule_21; }
    if ((token === import12.Compiler)) { return this._Compiler_22; }
    if ((token === import56.ComponentResolver)) { return this._ComponentResolver_23; }
    if ((token === import43.APP_ID)) { return this._APP_ID_24; }
    if ((token === import57.DOCUMENT)) { return this._DOCUMENT_25; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_26; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_27; }
    if ((token === import14.EventManager)) { return this._EventManager_28; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_29; }
    if ((token === import58.AnimationDriver)) { return this._AnimationDriver_30; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_31; }
    if ((token === import59.RootRenderer)) { return this._RootRenderer_32; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_33; }
    if ((token === import60.SanitizationService)) { return this._SanitizationService_34; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import61.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import62.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_38; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_39; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import63.UserRoot)) { return this._UserRoot_42; }
    if ((token === import22.ActionSheetController)) { return this._ActionSheetController_43; }
    if ((token === import23.AlertController)) { return this._AlertController_44; }
    if ((token === import24.Form)) { return this._Form_45; }
    if ((token === import25.FeatureDetect)) { return this._FeatureDetect_46; }
    if ((token === import26.GestureController)) { return this._GestureController_47; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import65.Http)) { return this._Http_53; }
    if ((token === import31.Keyboard)) { return this._Keyboard_54; }
    if ((token === import32.LoadingController)) { return this._LoadingController_55; }
    if ((token === import33.MenuController)) { return this._MenuController_56; }
    if ((token === import34.ModalController)) { return this._ModalController_57; }
    if ((token === import35.PickerController)) { return this._PickerController_58; }
    if ((token === import36.PopoverController)) { return this._PopoverController_59; }
    if ((token === import37.TapClick)) { return this._TapClick_60; }
    if ((token === import38.ToastController)) { return this._ToastController_61; }
    if ((token === import39.Translate)) { return this._Translate_62; }
    if ((token === import40.TransitionController)) { return this._TransitionController_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
var renderType_E2EPage_Host:import66.RenderComponentType = null;
class _View_E2EPage_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EPage_0_4:import1.E2EPage;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage_Host0,renderType_E2EPage_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EPage_0_4 = new import1.E2EPage();
    this._appEl_0.initComponent(this._E2EPage_0_4,[],compView_0);
    compView_0.create(this._E2EPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EPage) && (0 === requestNodeIndex))) { return this._E2EPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EPage_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EPage_Host === null)) { (renderType_E2EPage_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EPageNgFactory:import72.ComponentFactory<import1.E2EPage> = new import72.ComponentFactory<import1.E2EPage>('ng-component',viewFactory_E2EPage_Host0,import1.E2EPage);
const styles_E2EPage:any[] = [];
var renderType_E2EPage:import66.RenderComponentType = null;
class _View_E2EPage0 extends import67.AppView<import1.E2EPage> {
  _el_0:any;
  _Header_0_3:import73.Header;
  _text_1:any;
  _el_2:any;
  private _appEl_2:import68.AppElement;
  _Toolbar_2_4:import73.Toolbar;
  _text_3:any;
  _el_4:any;
  private _appEl_4:import68.AppElement;
  _ToolbarTitle_4_4:import74.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  private _appEl_9:import68.AppElement;
  _Content_9_4:import75.Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import76.List;
  _text_12:any;
  _el_13:any;
  private _appEl_13:import68.AppElement;
  _ItemContent_13_4:import77.ItemContent;
  _Item_13_5:import77.Item;
  _query_Label_13_0:import78.QueryList<any>;
  _query_Button_13_1:import78.QueryList<any>;
  _query_Icon_13_2:import78.QueryList<any>;
  _text_14:any;
  _el_15:any;
  private _appEl_15:import68.AppElement;
  _TextInput_15_4:import79.TextInput;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  private _appEl_18:import68.AppElement;
  _ItemContent_18_4:import77.ItemContent;
  _Item_18_5:import77.Item;
  _query_Label_18_0:import78.QueryList<any>;
  _query_Button_18_1:import78.QueryList<any>;
  _query_Icon_18_2:import78.QueryList<any>;
  _text_19:any;
  _el_20:any;
  private _appEl_20:import68.AppElement;
  _TextInput_20_4:import79.TextInput;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  private _appEl_23:import68.AppElement;
  _ItemContent_23_4:import77.ItemContent;
  _Item_23_5:import77.Item;
  _query_Label_23_0:import78.QueryList<any>;
  _query_Button_23_1:import78.QueryList<any>;
  _query_Icon_23_2:import78.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import80.Icon;
  _text_26:any;
  _el_27:any;
  private _appEl_27:import68.AppElement;
  _TextInput_27_4:import79.TextInput;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  private _appEl_30:import68.AppElement;
  _ItemContent_30_4:import77.ItemContent;
  _Item_30_5:import77.Item;
  _query_Label_30_0:import78.QueryList<any>;
  _query_Button_30_1:import78.QueryList<any>;
  _query_Icon_30_2:import78.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Icon_32_3:import80.Icon;
  _text_33:any;
  _el_34:any;
  private _appEl_34:import68.AppElement;
  _TextInput_34_4:import79.TextInput;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  private _appEl_37:import68.AppElement;
  _ItemContent_37_4:import77.ItemContent;
  _Item_37_5:import77.Item;
  _query_Label_37_0:import78.QueryList<any>;
  _query_Button_37_1:import78.QueryList<any>;
  _query_Icon_37_2:import78.QueryList<any>;
  _text_38:any;
  _el_39:any;
  private _appEl_39:import68.AppElement;
  _TextArea_39_4:import79.TextArea;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  private _appEl_42:import68.AppElement;
  _ItemContent_42_4:import77.ItemContent;
  _Item_42_5:import77.Item;
  _query_Label_42_0:import78.QueryList<any>;
  _query_Button_42_1:import78.QueryList<any>;
  _query_Icon_42_2:import78.QueryList<any>;
  _text_43:any;
  _el_44:any;
  private _appEl_44:import68.AppElement;
  _TextArea_44_4:import79.TextArea;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _List_48_3:import76.List;
  _text_49:any;
  _el_50:any;
  private _appEl_50:import68.AppElement;
  _ItemContent_50_4:import77.ItemContent;
  _Item_50_5:import77.Item;
  _query_Label_50_0:import78.QueryList<any>;
  _query_Button_50_1:import78.QueryList<any>;
  _query_Icon_50_2:import78.QueryList<any>;
  _text_51:any;
  _el_52:any;
  private _appEl_52:import68.AppElement;
  _TextInput_52_4:import79.TextInput;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  private _appEl_55:import68.AppElement;
  _ItemContent_55_4:import77.ItemContent;
  _Item_55_5:import77.Item;
  _query_Label_55_0:import78.QueryList<any>;
  _query_Button_55_1:import78.QueryList<any>;
  _query_Icon_55_2:import78.QueryList<any>;
  _text_56:any;
  _el_57:any;
  private _appEl_57:import68.AppElement;
  _TextInput_57_4:import79.TextInput;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  private _appEl_60:import68.AppElement;
  _ItemContent_60_4:import77.ItemContent;
  _Item_60_5:import77.Item;
  _query_Label_60_0:import78.QueryList<any>;
  _query_Button_60_1:import78.QueryList<any>;
  _query_Icon_60_2:import78.QueryList<any>;
  _text_61:any;
  _el_62:any;
  _Icon_62_3:import80.Icon;
  _text_63:any;
  _el_64:any;
  private _appEl_64:import68.AppElement;
  _TextInput_64_4:import79.TextInput;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  private _appEl_67:import68.AppElement;
  _ItemContent_67_4:import77.ItemContent;
  _Item_67_5:import77.Item;
  _query_Label_67_0:import78.QueryList<any>;
  _query_Button_67_1:import78.QueryList<any>;
  _query_Icon_67_2:import78.QueryList<any>;
  _text_68:any;
  _el_69:any;
  _Icon_69_3:import80.Icon;
  _text_70:any;
  _el_71:any;
  private _appEl_71:import68.AppElement;
  _TextInput_71_4:import79.TextInput;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  private _expr_0:any;
  private _expr_1:any;
  private _expr_2:any;
  private _expr_3:any;
  private _expr_4:any;
  private _expr_5:any;
  private _expr_6:any;
  private _expr_7:any;
  private _expr_8:any;
  private _expr_9:any;
  private _expr_10:any;
  private _expr_11:any;
  private _expr_12:any;
  private _expr_13:any;
  private _expr_14:any;
  private _expr_15:any;
  private _expr_16:any;
  private _expr_17:any;
  private _expr_18:any;
  private _expr_19:any;
  private _expr_20:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage0,renderType_E2EPage,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',null);
    this._Header_0_3 = new import73.Header(this.parentInjector.get(import81.ViewController,null));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',null);
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import68.AppElement(2,0,this,this._el_2);
    var compView_2:any = import82.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import73.Toolbar(this.parentInjector.get(import81.ViewController,null),this._Header_0_3,this.parentInjector.get(import73.Footer,null),this.parentInjector.get(import52.Config),new import83.ElementRef(this._el_2));
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText(null,'\n    ',null);
    this._el_4 = this.renderer.createElement(null,'ion-title',null);
    this._appEl_4 = new import68.AppElement(4,2,this,this._el_4);
    var compView_4:any = import84.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import74.ToolbarTitle(new import83.ElementRef(this._el_4),this._Toolbar_2_4,this.parentInjector.get(import85.Navbar,null));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText(null,'Placeholder Label Text Input',null);
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],null);
    this._text_6 = this.renderer.createText(null,'\n  ',null);
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,null);
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',null);
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',null);
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this.renderer.setElementAttribute(this._el_9,'class','outer-content');
    this._appEl_9 = new import68.AppElement(9,null,this,this._el_9);
    var compView_9:any = import86.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import75.Content(new import83.ElementRef(this._el_9),this.parentInjector.get(import52.Config),this.parentInjector.get(import7.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import81.ViewController,null),this.parentInjector.get(import87.Tabs,null));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText(null,'\n\n  ',null);
    this._el_11 = this.renderer.createElement(null,'ion-list',null);
    this._List_11_3 = new import76.List(new import83.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_13 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_13,'class','item');
    this._appEl_13 = new import68.AppElement(13,11,this,this._el_13);
    var compView_13:any = import88.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ItemContent_13_4 = new import77.ItemContent();
    this._Item_13_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_13));
    this._query_Label_13_0 = new import78.QueryList<any>();
    this._query_Button_13_1 = new import78.QueryList<any>();
    this._query_Icon_13_2 = new import78.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_5,[],compView_13);
    this._text_14 = this.renderer.createText(null,'\n      ',null);
    this._el_15 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_15,'placeholder','Text Input Placeholder');
    this._appEl_15 = new import68.AppElement(15,13,this,this._el_15);
    var compView_15:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(15),this._appEl_15);
    this._TextInput_15_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_13_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_15),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_15.initComponent(this._TextInput_15_4,[],compView_15);
    compView_15.create(this._TextInput_15_4,[],null);
    this._text_16 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_13_0.reset([]);
    this._Item_13_5.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_5,[
      [],
      [],
      [].concat([
        this._text_14,
        this._text_16
      ]
      ),
      [].concat([this._el_15]),
      []
    ]
    ,null);
    this._text_17 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_18 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_18,'class','item');
    this._appEl_18 = new import68.AppElement(18,11,this,this._el_18);
    var compView_18:any = import88.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._ItemContent_18_4 = new import77.ItemContent();
    this._Item_18_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_18));
    this._query_Label_18_0 = new import78.QueryList<any>();
    this._query_Button_18_1 = new import78.QueryList<any>();
    this._query_Icon_18_2 = new import78.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_5,[],compView_18);
    this._text_19 = this.renderer.createText(null,'\n      ',null);
    this._el_20 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_20,'placeholder','Text Input Placeholder');
    this.renderer.setElementAttribute(this._el_20,'value','Text Input Value');
    this._appEl_20 = new import68.AppElement(20,18,this,this._el_20);
    var compView_20:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(20),this._appEl_20);
    this._TextInput_20_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_18_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_20),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_20.initComponent(this._TextInput_20_4,[],compView_20);
    compView_20.create(this._TextInput_20_4,[],null);
    this._text_21 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_18_0.reset([]);
    this._Item_18_5.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_5,[
      [],
      [],
      [].concat([
        this._text_19,
        this._text_21
      ]
      ),
      [].concat([this._el_20]),
      []
    ]
    ,null);
    this._text_22 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_23 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_23,'class','item');
    this._appEl_23 = new import68.AppElement(23,11,this,this._el_23);
    var compView_23:any = import88.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._ItemContent_23_4 = new import77.ItemContent();
    this._Item_23_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_23));
    this._query_Label_23_0 = new import78.QueryList<any>();
    this._query_Button_23_1 = new import78.QueryList<any>();
    this._query_Icon_23_2 = new import78.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_5,[],compView_23);
    this._text_24 = this.renderer.createText(null,'\n      ',null);
    this._el_25 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this.renderer.setElementAttribute(this._el_25,'name','call');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import80.Icon(this.parentInjector.get(import52.Config),new import83.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText(null,'\n      ',null);
    this._el_27 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_27,'placeholder','Text Input Placeholder');
    this._appEl_27 = new import68.AppElement(27,23,this,this._el_27);
    var compView_27:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(27),this._appEl_27);
    this._TextInput_27_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_23_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_27),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_27.initComponent(this._TextInput_27_4,[],compView_27);
    compView_27.create(this._TextInput_27_4,[],null);
    this._text_28 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_23_0.reset([]);
    this._Item_23_5.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_5,[
      [].concat([this._el_25]),
      [],
      [].concat([
        this._text_24,
        this._text_26,
        this._text_28
      ]
      ),
      [].concat([this._el_27]),
      []
    ]
    ,null);
    this._text_29 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_30 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_30,'class','item');
    this._appEl_30 = new import68.AppElement(30,11,this,this._el_30);
    var compView_30:any = import88.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._ItemContent_30_4 = new import77.ItemContent();
    this._Item_30_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_30));
    this._query_Label_30_0 = new import78.QueryList<any>();
    this._query_Button_30_1 = new import78.QueryList<any>();
    this._query_Icon_30_2 = new import78.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_5,[],compView_30);
    this._text_31 = this.renderer.createText(null,'\n      ',null);
    this._el_32 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_32,'item-left','');
    this.renderer.setElementAttribute(this._el_32,'name','call');
    this.renderer.setElementAttribute(this._el_32,'role','img');
    this._Icon_32_3 = new import80.Icon(this.parentInjector.get(import52.Config),new import83.ElementRef(this._el_32),this.renderer);
    this._text_33 = this.renderer.createText(null,'\n      ',null);
    this._el_34 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_34,'placeholder','Text Input Placeholder');
    this.renderer.setElementAttribute(this._el_34,'value','Text Input Value');
    this._appEl_34 = new import68.AppElement(34,30,this,this._el_34);
    var compView_34:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(34),this._appEl_34);
    this._TextInput_34_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_30_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_34),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_34.initComponent(this._TextInput_34_4,[],compView_34);
    compView_34.create(this._TextInput_34_4,[],null);
    this._text_35 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_30_0.reset([]);
    this._Item_30_5.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_5,[
      [].concat([this._el_32]),
      [],
      [].concat([
        this._text_31,
        this._text_33,
        this._text_35
      ]
      ),
      [].concat([this._el_34]),
      []
    ]
    ,null);
    this._text_36 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_37 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_37,'class','item');
    this._appEl_37 = new import68.AppElement(37,11,this,this._el_37);
    var compView_37:any = import88.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._ItemContent_37_4 = new import77.ItemContent();
    this._Item_37_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_37));
    this._query_Label_37_0 = new import78.QueryList<any>();
    this._query_Button_37_1 = new import78.QueryList<any>();
    this._query_Icon_37_2 = new import78.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_5,[],compView_37);
    this._text_38 = this.renderer.createText(null,'\n      ',null);
    this._el_39 = this.renderer.createElement(null,'ion-textarea',null);
    this.renderer.setElementAttribute(this._el_39,'placeholder','Textarea Placeholder');
    this._appEl_39 = new import68.AppElement(39,37,this,this._el_39);
    var compView_39:any = import89.viewFactory_TextArea0(this.viewUtils,this.injector(39),this._appEl_39);
    this._TextArea_39_4 = new import79.TextArea(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_37_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_39),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_39.initComponent(this._TextArea_39_4,[],compView_39);
    compView_39.create(this._TextArea_39_4,[],null);
    this._text_40 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_37_0.reset([]);
    this._Item_37_5.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_5,[
      [],
      [],
      [].concat([
        this._text_38,
        this._text_40
      ]
      ),
      [].concat([this._el_39]),
      []
    ]
    ,null);
    this._text_41 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_42 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_42,'class','item');
    this._appEl_42 = new import68.AppElement(42,11,this,this._el_42);
    var compView_42:any = import88.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._ItemContent_42_4 = new import77.ItemContent();
    this._Item_42_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_42));
    this._query_Label_42_0 = new import78.QueryList<any>();
    this._query_Button_42_1 = new import78.QueryList<any>();
    this._query_Icon_42_2 = new import78.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_5,[],compView_42);
    this._text_43 = this.renderer.createText(null,'\n      ',null);
    this._el_44 = this.renderer.createElement(null,'ion-textarea',null);
    this.renderer.setElementAttribute(this._el_44,'placeholder','ion-textarea Placeholder');
    this.renderer.setElementAttribute(this._el_44,'value','Textarea value');
    this._appEl_44 = new import68.AppElement(44,42,this,this._el_44);
    var compView_44:any = import89.viewFactory_TextArea0(this.viewUtils,this.injector(44),this._appEl_44);
    this._TextArea_44_4 = new import79.TextArea(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_42_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_44),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_44.initComponent(this._TextArea_44_4,[],compView_44);
    compView_44.create(this._TextArea_44_4,[],null);
    this._text_45 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_42_0.reset([]);
    this._Item_42_5.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_5,[
      [],
      [],
      [].concat([
        this._text_43,
        this._text_45
      ]
      ),
      [].concat([this._el_44]),
      []
    ]
    ,null);
    this._text_46 = this.renderer.createText(this._el_11,'\n\n  ',null);
    this._text_47 = this.renderer.createText(null,'\n\n  ',null);
    this._el_48 = this.renderer.createElement(null,'ion-list',null);
    this.renderer.setElementAttribute(this._el_48,'inset','');
    this._List_48_3 = new import76.List(new import83.ElementRef(this._el_48),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_49 = this.renderer.createText(this._el_48,'\n\n    ',null);
    this._el_50 = this.renderer.createElement(this._el_48,'ion-item',null);
    this.renderer.setElementAttribute(this._el_50,'class','item');
    this._appEl_50 = new import68.AppElement(50,48,this,this._el_50);
    var compView_50:any = import88.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._ItemContent_50_4 = new import77.ItemContent();
    this._Item_50_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_50));
    this._query_Label_50_0 = new import78.QueryList<any>();
    this._query_Button_50_1 = new import78.QueryList<any>();
    this._query_Icon_50_2 = new import78.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_5,[],compView_50);
    this._text_51 = this.renderer.createText(null,'\n      ',null);
    this._el_52 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_52,'placeholder','Inset List: Text Input Placeholder');
    this._appEl_52 = new import68.AppElement(52,50,this,this._el_52);
    var compView_52:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(52),this._appEl_52);
    this._TextInput_52_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_50_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_52),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_52.initComponent(this._TextInput_52_4,[],compView_52);
    compView_52.create(this._TextInput_52_4,[],null);
    this._text_53 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_50_0.reset([]);
    this._Item_50_5.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_5,[
      [],
      [],
      [].concat([
        this._text_51,
        this._text_53
      ]
      ),
      [].concat([this._el_52]),
      []
    ]
    ,null);
    this._text_54 = this.renderer.createText(this._el_48,'\n\n    ',null);
    this._el_55 = this.renderer.createElement(this._el_48,'ion-item',null);
    this.renderer.setElementAttribute(this._el_55,'class','item');
    this._appEl_55 = new import68.AppElement(55,48,this,this._el_55);
    var compView_55:any = import88.viewFactory_Item0(this.viewUtils,this.injector(55),this._appEl_55);
    this._ItemContent_55_4 = new import77.ItemContent();
    this._Item_55_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_55));
    this._query_Label_55_0 = new import78.QueryList<any>();
    this._query_Button_55_1 = new import78.QueryList<any>();
    this._query_Icon_55_2 = new import78.QueryList<any>();
    this._appEl_55.initComponent(this._Item_55_5,[],compView_55);
    this._text_56 = this.renderer.createText(null,'\n      ',null);
    this._el_57 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_57,'placeholder','Inset List: Text Input Placeholder');
    this.renderer.setElementAttribute(this._el_57,'value','Inset List: Text Input Value');
    this._appEl_57 = new import68.AppElement(57,55,this,this._el_57);
    var compView_57:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(57),this._appEl_57);
    this._TextInput_57_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_55_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_57),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_57.initComponent(this._TextInput_57_4,[],compView_57);
    compView_57.create(this._TextInput_57_4,[],null);
    this._text_58 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_55_0.reset([]);
    this._Item_55_5.contentLabel = this._query_Label_55_0.first;
    compView_55.create(this._Item_55_5,[
      [],
      [],
      [].concat([
        this._text_56,
        this._text_58
      ]
      ),
      [].concat([this._el_57]),
      []
    ]
    ,null);
    this._text_59 = this.renderer.createText(this._el_48,'\n\n    ',null);
    this._el_60 = this.renderer.createElement(this._el_48,'ion-item',null);
    this.renderer.setElementAttribute(this._el_60,'class','item');
    this._appEl_60 = new import68.AppElement(60,48,this,this._el_60);
    var compView_60:any = import88.viewFactory_Item0(this.viewUtils,this.injector(60),this._appEl_60);
    this._ItemContent_60_4 = new import77.ItemContent();
    this._Item_60_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_60));
    this._query_Label_60_0 = new import78.QueryList<any>();
    this._query_Button_60_1 = new import78.QueryList<any>();
    this._query_Icon_60_2 = new import78.QueryList<any>();
    this._appEl_60.initComponent(this._Item_60_5,[],compView_60);
    this._text_61 = this.renderer.createText(null,'\n      ',null);
    this._el_62 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_62,'item-left','');
    this.renderer.setElementAttribute(this._el_62,'name','call');
    this.renderer.setElementAttribute(this._el_62,'role','img');
    this._Icon_62_3 = new import80.Icon(this.parentInjector.get(import52.Config),new import83.ElementRef(this._el_62),this.renderer);
    this._text_63 = this.renderer.createText(null,'\n      ',null);
    this._el_64 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_64,'placeholder','Inset List: Text Input Placeholder');
    this._appEl_64 = new import68.AppElement(64,60,this,this._el_64);
    var compView_64:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(64),this._appEl_64);
    this._TextInput_64_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_60_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_64),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_64.initComponent(this._TextInput_64_4,[],compView_64);
    compView_64.create(this._TextInput_64_4,[],null);
    this._text_65 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_60_0.reset([]);
    this._Item_60_5.contentLabel = this._query_Label_60_0.first;
    compView_60.create(this._Item_60_5,[
      [].concat([this._el_62]),
      [],
      [].concat([
        this._text_61,
        this._text_63,
        this._text_65
      ]
      ),
      [].concat([this._el_64]),
      []
    ]
    ,null);
    this._text_66 = this.renderer.createText(this._el_48,'\n\n    ',null);
    this._el_67 = this.renderer.createElement(this._el_48,'ion-item',null);
    this.renderer.setElementAttribute(this._el_67,'class','item');
    this._appEl_67 = new import68.AppElement(67,48,this,this._el_67);
    var compView_67:any = import88.viewFactory_Item0(this.viewUtils,this.injector(67),this._appEl_67);
    this._ItemContent_67_4 = new import77.ItemContent();
    this._Item_67_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import83.ElementRef(this._el_67));
    this._query_Label_67_0 = new import78.QueryList<any>();
    this._query_Button_67_1 = new import78.QueryList<any>();
    this._query_Icon_67_2 = new import78.QueryList<any>();
    this._appEl_67.initComponent(this._Item_67_5,[],compView_67);
    this._text_68 = this.renderer.createText(null,'\n      ',null);
    this._el_69 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_69,'item-left','');
    this.renderer.setElementAttribute(this._el_69,'name','call');
    this.renderer.setElementAttribute(this._el_69,'role','img');
    this._Icon_69_3 = new import80.Icon(this.parentInjector.get(import52.Config),new import83.ElementRef(this._el_69),this.renderer);
    this._text_70 = this.renderer.createText(null,'\n      ',null);
    this._el_71 = this.renderer.createElement(null,'ion-input',null);
    this.renderer.setElementAttribute(this._el_71,'placeholder','Inset List: Text Input Placeholder');
    this.renderer.setElementAttribute(this._el_71,'value','Inset List: Text Input Value');
    this._appEl_71 = new import68.AppElement(71,67,this,this._el_71);
    var compView_71:any = import89.viewFactory_TextInput0(this.viewUtils,this.injector(71),this._appEl_71);
    this._TextInput_71_4 = new import79.TextInput(this.parentInjector.get(import52.Config),this.parentInjector.get(import24.Form),this._Item_67_5,this.parentInjector.get(import7.App),this.parentInjector.get(import51.Platform),new import83.ElementRef(this._el_71),this._Content_9_4,this.parentInjector.get(import90.NavController,null),this.parentInjector.get(import91.NgControl,null));
    this._appEl_71.initComponent(this._TextInput_71_4,[],compView_71);
    compView_71.create(this._TextInput_71_4,[],null);
    this._text_72 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_67_0.reset([]);
    this._Item_67_5.contentLabel = this._query_Label_67_0.first;
    compView_67.create(this._Item_67_5,[
      [].concat([this._el_69]),
      [],
      [].concat([
        this._text_68,
        this._text_70,
        this._text_72
      ]
      ),
      [].concat([this._el_71]),
      []
    ]
    ,null);
    this._text_73 = this.renderer.createText(this._el_48,'\n\n  ',null);
    this._text_74 = this.renderer.createText(null,'\n\n',null);
    compView_9.create(this._Content_9_4,[
      [].concat([
        this._text_10,
        this._el_11,
        this._text_47,
        this._el_48,
        this._text_74
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_75 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import71.UNINITIALIZED;
    this._expr_1 = import71.UNINITIALIZED;
    this._expr_2 = import71.UNINITIALIZED;
    this._expr_3 = import71.UNINITIALIZED;
    this._expr_4 = import71.UNINITIALIZED;
    this._expr_5 = import71.UNINITIALIZED;
    this._expr_6 = import71.UNINITIALIZED;
    this._expr_7 = import71.UNINITIALIZED;
    this._expr_8 = import71.UNINITIALIZED;
    this._expr_9 = import71.UNINITIALIZED;
    this._expr_10 = import71.UNINITIALIZED;
    this._expr_11 = import71.UNINITIALIZED;
    this._expr_12 = import71.UNINITIALIZED;
    this._expr_13 = import71.UNINITIALIZED;
    this._expr_14 = import71.UNINITIALIZED;
    this._expr_15 = import71.UNINITIALIZED;
    this._expr_16 = import71.UNINITIALIZED;
    this._expr_17 = import71.UNINITIALIZED;
    this._expr_18 = import71.UNINITIALIZED;
    this._expr_19 = import71.UNINITIALIZED;
    this._expr_20 = import71.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import74.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import73.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Toolbar_2_4; }
    if (((token === import73.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import79.TextInput) && (15 === requestNodeIndex))) { return this._TextInput_15_4; }
    if (((token === import77.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_13_4; }
    if (((token === import77.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_13_5; }
    if (((token === import79.TextInput) && (20 === requestNodeIndex))) { return this._TextInput_20_4; }
    if (((token === import77.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_18_4; }
    if (((token === import77.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_18_5; }
    if (((token === import80.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3; }
    if (((token === import79.TextInput) && (27 === requestNodeIndex))) { return this._TextInput_27_4; }
    if (((token === import77.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_23_4; }
    if (((token === import77.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_23_5; }
    if (((token === import80.Icon) && (32 === requestNodeIndex))) { return this._Icon_32_3; }
    if (((token === import79.TextInput) && (34 === requestNodeIndex))) { return this._TextInput_34_4; }
    if (((token === import77.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ItemContent_30_4; }
    if (((token === import77.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item_30_5; }
    if (((token === import79.TextArea) && (39 === requestNodeIndex))) { return this._TextArea_39_4; }
    if (((token === import77.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_37_4; }
    if (((token === import77.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_37_5; }
    if (((token === import79.TextArea) && (44 === requestNodeIndex))) { return this._TextArea_44_4; }
    if (((token === import77.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._ItemContent_42_4; }
    if (((token === import77.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Item_42_5; }
    if (((token === import76.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._List_11_3; }
    if (((token === import79.TextInput) && (52 === requestNodeIndex))) { return this._TextInput_52_4; }
    if (((token === import77.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ItemContent_50_4; }
    if (((token === import77.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Item_50_5; }
    if (((token === import79.TextInput) && (57 === requestNodeIndex))) { return this._TextInput_57_4; }
    if (((token === import77.ItemContent) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemContent_55_4; }
    if (((token === import77.Item) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_55_5; }
    if (((token === import80.Icon) && (62 === requestNodeIndex))) { return this._Icon_62_3; }
    if (((token === import79.TextInput) && (64 === requestNodeIndex))) { return this._TextInput_64_4; }
    if (((token === import77.ItemContent) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ItemContent_60_4; }
    if (((token === import77.Item) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Item_60_5; }
    if (((token === import80.Icon) && (69 === requestNodeIndex))) { return this._Icon_69_3; }
    if (((token === import79.TextInput) && (71 === requestNodeIndex))) { return this._TextInput_71_4; }
    if (((token === import77.ItemContent) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._ItemContent_67_4; }
    if (((token === import77.Item) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._Item_67_5; }
    if (((token === import76.List) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._List_48_3; }
    if (((token === import75.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_2:any = 'Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._TextInput_15_4.placeholder = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._TextInput_20_4.placeholder = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'Text Input Value';
    if (import69.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._TextInput_20_4.value = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'call';
    if (import69.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_25_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._TextInput_27_4.placeholder = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'call';
    if (import69.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_32_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._TextInput_34_4.placeholder = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'Text Input Value';
    if (import69.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._TextInput_34_4.value = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = 'Textarea Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._TextArea_39_4.placeholder = currVal_10;
      this._expr_10 = currVal_10;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextArea_39_4.ngOnInit(); }
    const currVal_11:any = 'ion-textarea Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._TextArea_44_4.placeholder = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'Textarea value';
    if (import69.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._TextArea_44_4.value = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextArea_44_4.ngOnInit(); }
    const currVal_13:any = 'Inset List: Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._TextInput_52_4.placeholder = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'Inset List: Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._TextInput_57_4.placeholder = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'Inset List: Text Input Value';
    if (import69.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._TextInput_57_4.value = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'call';
    if (import69.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_62_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = 'Inset List: Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._TextInput_64_4.placeholder = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = 'call';
    if (import69.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._Icon_69_3.name = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'Inset List: Text Input Placeholder';
    if (import69.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._TextInput_71_4.placeholder = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = 'Inset List: Text Input Value';
    if (import69.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._TextInput_71_4.value = currVal_20;
      this._expr_20 = currVal_20;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset([]);
        this._Item_13_5._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset([]);
        this._Item_13_5._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset([]);
        this._Item_18_5._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset([]);
        this._Item_18_5._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_5._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_25_3]);
        this._Item_23_5._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset([]);
        this._Item_30_5._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset([this._Icon_32_3]);
        this._Item_30_5._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset([]);
        this._Item_37_5._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset([]);
        this._Item_37_5._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([]);
        this._Item_42_5._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([]);
        this._Item_42_5._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset([]);
        this._Item_50_5._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset([]);
        this._Item_50_5._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if (this._query_Button_55_1.dirty) {
        this._query_Button_55_1.reset([]);
        this._Item_55_5._buttons = this._query_Button_55_1;
        this._query_Button_55_1.notifyOnChanges();
      }
      if (this._query_Icon_55_2.dirty) {
        this._query_Icon_55_2.reset([]);
        this._Item_55_5._icons = this._query_Icon_55_2;
        this._query_Icon_55_2.notifyOnChanges();
      }
      if (this._query_Button_60_1.dirty) {
        this._query_Button_60_1.reset([]);
        this._Item_60_5._buttons = this._query_Button_60_1;
        this._query_Button_60_1.notifyOnChanges();
      }
      if (this._query_Icon_60_2.dirty) {
        this._query_Icon_60_2.reset([this._Icon_62_3]);
        this._Item_60_5._icons = this._query_Icon_60_2;
        this._query_Icon_60_2.notifyOnChanges();
      }
      if (this._query_Button_67_1.dirty) {
        this._query_Button_67_1.reset([]);
        this._Item_67_5._buttons = this._query_Button_67_1;
        this._query_Button_67_1.notifyOnChanges();
      }
      if (this._query_Icon_67_2.dirty) {
        this._query_Icon_67_2.reset([this._Icon_69_3]);
        this._Item_67_5._icons = this._query_Icon_67_2;
        this._query_Icon_67_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_13_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_30_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_37_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_42_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_55_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_60_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_67_5.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Content_9_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_25_3.ngOnDestroy();
    this._Icon_32_3.ngOnDestroy();
    this._List_11_3.ngOnDestroy();
    this._Icon_62_3.ngOnDestroy();
    this._Icon_69_3.ngOnDestroy();
    this._List_48_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_E2EPage0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EPage> {
  if ((renderType_E2EPage === null)) { (renderType_E2EPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/input/placeholder-labels/main.html',0,import92.ViewEncapsulation.None,styles_E2EPage,{})); }
  return new _View_E2EPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_E2EApp_Host:import66.RenderComponentType = null;
class _View_E2EApp_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EApp_0_4:import1.E2EApp;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp_Host0,renderType_E2EApp_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EApp_0_4 = new import1.E2EApp();
    this._appEl_0.initComponent(this._E2EApp_0_4,[],compView_0);
    compView_0.create(this._E2EApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EApp) && (0 === requestNodeIndex))) { return this._E2EApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EApp_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EApp_Host === null)) { (renderType_E2EApp_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EAppNgFactory:import72.ComponentFactory<import1.E2EApp> = new import72.ComponentFactory<import1.E2EApp>('ng-component',viewFactory_E2EApp_Host0,import1.E2EApp);
const styles_E2EApp:any[] = [];
var renderType_E2EApp:import66.RenderComponentType = null;
class _View_E2EApp0 extends import67.AppView<import1.E2EApp> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _Nav_0_4:import93.Nav;
  private _expr_0:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp0,renderType_E2EApp,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = import94.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import93.Nav(this.parentInjector.get(import81.ViewController,null),this.parentInjector.get(import95.NavControllerBase,null),this.parentInjector.get(import7.App),this.parentInjector.get(import52.Config),this.parentInjector.get(import31.Keyboard),new import83.ElementRef(this._el_0),this.parentInjector.get(import46.NgZone),this.renderer,this.parentInjector.get(import96.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import71.UNINITIALIZED;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import93.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_E2EApp0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EApp> {
  if ((renderType_E2EApp === null)) { (renderType_E2EApp = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/input/placeholder-labels/AppModule.ts class E2EApp - inline template',0,import92.ViewEncapsulation.None,styles_E2EApp,{})); }
  return new _View_E2EApp0(viewUtils,parentInjector,declarationEl);
}