/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import41 from '@angular/core/src/di/injector';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import73 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const PopoverRadioPageNgFactory: import73.ComponentFactory<import1.PopoverRadioPage>;
export declare function viewFactory_PopoverRadioPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.PopoverRadioPage>;
export declare const PopoverListPageNgFactory: import73.ComponentFactory<import1.PopoverListPage>;
export declare function viewFactory_PopoverListPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.PopoverListPage>;
export declare const PopoverLongListPageNgFactory: import73.ComponentFactory<import1.PopoverLongListPage>;
export declare function viewFactory_PopoverLongListPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.PopoverLongListPage>;
export declare const E2EPageNgFactory: import73.ComponentFactory<import1.E2EPage>;
export declare function viewFactory_E2EPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EPage>;
export declare const E2EAppNgFactory: import73.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EApp>;
