/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../../dist/components/app/app';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '../../../dist/ionic-module';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '../../../dist/components/action-sheet/action-sheet';
import * as import23 from '../../../dist/components/alert/alert';
import * as import24 from '../../../dist/util/form';
import * as import25 from '../../../dist/util/feature-detect';
import * as import26 from '../../../dist/gestures/gesture-controller';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '../../../dist/util/keyboard';
import * as import32 from '../../../dist/components/loading/loading';
import * as import33 from '../../../dist/components/menu/menu-controller';
import * as import34 from '../../../dist/components/modal/modal';
import * as import35 from '../../../dist/components/picker/picker';
import * as import36 from '../../../dist/components/popover/popover';
import * as import37 from '../../../dist/components/tap-click/tap-click';
import * as import38 from '../../../dist/components/toast/toast';
import * as import39 from '../../../dist/translation/translate';
import * as import40 from '../../../dist/transitions/transition-controller';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../../../dist/components/app/app-root.d.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/http/http';
import * as import49 from '../../../dist/providers';
import * as import50 from '../../../dist/platform/query-params';
import * as import51 from '../../../dist/platform/platform';
import * as import52 from '../../../dist/config/config';
import * as import53 from '../../../dist/util/events';
import * as import54 from '@angular/core/src/console';
import * as import55 from '@angular/core/src/facade/exception_handler';
import * as import56 from '@angular/core/src/linker/component_resolver';
import * as import57 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import58 from '@angular/platform-browser/src/dom/animation_driver';
import * as import59 from '@angular/core/src/render/api';
import * as import60 from '@angular/core/src/security';
import * as import61 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import62 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import63 from '../../../dist/components/app/app-root';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/core/src/render/api';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import70 from '@angular/core/src/linker/view_type';
import * as import71 from '@angular/core/src/change_detection/change_detection';
import * as import72 from '@angular/core/src/linker/component_factory';
import * as import73 from '../../../dist/components/toolbar/toolbar';
import * as import74 from '../../../dist/components/toolbar/toolbar-title';
import * as import75 from '../../../dist/components/content/content';
import * as import76 from '../../../dist/components/button/button';
import * as import77 from '../../../dist/components/icon/icon';
import * as import78 from '../../../dist/components/item/item';
import * as import79 from '@angular/core/src/linker/query_list';
import * as import80 from '../../../dist/components/nav/view-controller';
import * as import81 from '../../../dist/components/toolbar/toolbar.d.ngfactory';
import * as import82 from '@angular/core/src/linker/element_ref';
import * as import83 from '../../../dist/components/toolbar/toolbar-title.d.ngfactory';
import * as import84 from '../../../dist/components/navbar/navbar';
import * as import85 from '../../../dist/components/content/content.d.ngfactory';
import * as import86 from '../../../dist/components/tabs/tabs';
import * as import87 from '../../../dist/components/button/button.d.ngfactory';
import * as import88 from '../../../dist/components/item/item.d.ngfactory';
import * as import89 from '@angular/core/src/metadata/view';
import * as import90 from '../../../dist/components/nav/nav';
import * as import91 from '../../../dist/components/nav/nav.d.ngfactory';
import * as import92 from '../../../dist/components/nav/nav-controller-base';
import * as import93 from '@angular/core/src/linker/component_factory_resolver';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _ExceptionHandler_6:any;
  _UserUrl_7:any;
  _QueryParams_8:any;
  _UserAgent_9:any;
  _UserNavigatorPlatform_10:any;
  _Platform_11:any;
  _UserConfig_12:any;
  _Config_13:any;
  _App_14:import7.App;
  _APP_INITIALIZER_15:any[];
  _ApplicationInitStatus_16:import8.ApplicationInitStatus;
  _Testability_17:import9.Testability;
  _ApplicationRef__18:import10.ApplicationRef_;
  _ApplicationRef_19:any;
  _IonicModule_20:import11.IonicModule;
  _AppModule_21:import1.AppModule;
  __Compiler_22:import12.Compiler;
  __ComponentResolver_23:any;
  __APP_ID_24:any;
  __DOCUMENT_25:any;
  __HAMMER_GESTURE_CONFIG_26:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_27:any[];
  __EventManager_28:import14.EventManager;
  __DomSharedStylesHost_29:import15.DomSharedStylesHost;
  __AnimationDriver_30:any;
  __DomRootRenderer_31:import16.DomRootRenderer_;
  __RootRenderer_32:any;
  __DomSanitizationService_33:import17.DomSanitizationServiceImpl;
  __SanitizationService_34:any;
  __ViewUtils_35:import18.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DynamicComponentLoader_38:import19.DynamicComponentLoader_;
  __SharedStylesHost_39:any;
  __RadioControlRegistry_40:import20.RadioControlRegistry;
  __FormBuilder_41:import21.FormBuilder;
  __UserRoot_42:any;
  __ActionSheetController_43:import22.ActionSheetController;
  __AlertController_44:import23.AlertController;
  __Form_45:import24.Form;
  __FeatureDetect_46:import25.FeatureDetect;
  __GestureController_47:import26.GestureController;
  __BrowserXhr_48:import27.BrowserXhr;
  __ResponseOptions_49:import28.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import29.XHRBackend;
  __RequestOptions_52:import30.BaseRequestOptions;
  __Http_53:any;
  __Keyboard_54:import31.Keyboard;
  __LoadingController_55:import32.LoadingController;
  __MenuController_56:import33.MenuController;
  __ModalController_57:import34.ModalController;
  __PickerController_58:import35.PickerController;
  __PopoverController_59:import36.PopoverController;
  __TapClick_60:import37.TapClick;
  __ToastController_61:import38.ToastController;
  __Translate_62:import39.Translate;
  __TransitionController_63:import40.TransitionController;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.AppRootNgFactory,
      E2EAppNgFactory,
      E2EPageNgFactory,
      E2EAppNgFactory
    ]
    ,[E2EAppNgFactory]);
  }
  get _Compiler_22():import12.Compiler {
    if ((this.__Compiler_22 == null)) { (this.__Compiler_22 = new import12.Compiler()); }
    return this.__Compiler_22;
  }
  get _ComponentResolver_23():any {
    if ((this.__ComponentResolver_23 == null)) { (this.__ComponentResolver_23 = this._Compiler_22); }
    return this.__ComponentResolver_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == null)) { (this.__APP_ID_24 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_24;
  }
  get _DOCUMENT_25():any {
    if ((this.__DOCUMENT_25 == null)) { (this.__DOCUMENT_25 = import4._document()); }
    return this.__DOCUMENT_25;
  }
  get _HAMMER_GESTURE_CONFIG_26():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_26 == null)) { (this.__HAMMER_GESTURE_CONFIG_26 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_26;
  }
  get _EVENT_MANAGER_PLUGINS_27():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_27 == null)) { (this.__EVENT_MANAGER_PLUGINS_27 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_26)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_27;
  }
  get _EventManager_28():import14.EventManager {
    if ((this.__EventManager_28 == null)) { (this.__EventManager_28 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_27,this.parent.get(import46.NgZone))); }
    return this.__EventManager_28;
  }
  get _DomSharedStylesHost_29():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_29 == null)) { (this.__DomSharedStylesHost_29 = new import15.DomSharedStylesHost(this._DOCUMENT_25)); }
    return this.__DomSharedStylesHost_29;
  }
  get _AnimationDriver_30():any {
    if ((this.__AnimationDriver_30 == null)) { (this.__AnimationDriver_30 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_30;
  }
  get _DomRootRenderer_31():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_31 == null)) { (this.__DomRootRenderer_31 = new import16.DomRootRenderer_(this._DOCUMENT_25,this._EventManager_28,this._DomSharedStylesHost_29,this._AnimationDriver_30)); }
    return this.__DomRootRenderer_31;
  }
  get _RootRenderer_32():any {
    if ((this.__RootRenderer_32 == null)) { (this.__RootRenderer_32 = import47._createConditionalRootRenderer(this._DomRootRenderer_31)); }
    return this.__RootRenderer_32;
  }
  get _DomSanitizationService_33():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_33 == null)) { (this.__DomSanitizationService_33 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_33;
  }
  get _SanitizationService_34():any {
    if ((this.__SanitizationService_34 == null)) { (this.__SanitizationService_34 = this._DomSanitizationService_33); }
    return this.__SanitizationService_34;
  }
  get _ViewUtils_35():import18.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import18.ViewUtils(this._RootRenderer_32,this._APP_ID_24,this._SanitizationService_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _DynamicComponentLoader_38():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_38 == null)) { (this.__DynamicComponentLoader_38 = new import19.DynamicComponentLoader_(this._Compiler_22)); }
    return this.__DynamicComponentLoader_38;
  }
  get _SharedStylesHost_39():any {
    if ((this.__SharedStylesHost_39 == null)) { (this.__SharedStylesHost_39 = this._DomSharedStylesHost_29); }
    return this.__SharedStylesHost_39;
  }
  get _RadioControlRegistry_40():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _FormBuilder_41():import21.FormBuilder {
    if ((this.__FormBuilder_41 == null)) { (this.__FormBuilder_41 = new import21.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _UserRoot_42():any {
    if ((this.__UserRoot_42 == null)) { (this.__UserRoot_42 = import1.E2EApp); }
    return this.__UserRoot_42;
  }
  get _ActionSheetController_43():import22.ActionSheetController {
    if ((this.__ActionSheetController_43 == null)) { (this.__ActionSheetController_43 = new import22.ActionSheetController(this._App_14)); }
    return this.__ActionSheetController_43;
  }
  get _AlertController_44():import23.AlertController {
    if ((this.__AlertController_44 == null)) { (this.__AlertController_44 = new import23.AlertController(this._App_14)); }
    return this.__AlertController_44;
  }
  get _Form_45():import24.Form {
    if ((this.__Form_45 == null)) { (this.__Form_45 = new import24.Form()); }
    return this.__Form_45;
  }
  get _FeatureDetect_46():import25.FeatureDetect {
    if ((this.__FeatureDetect_46 == null)) { (this.__FeatureDetect_46 = new import25.FeatureDetect()); }
    return this.__FeatureDetect_46;
  }
  get _GestureController_47():import26.GestureController {
    if ((this.__GestureController_47 == null)) { (this.__GestureController_47 = new import26.GestureController(this._App_14)); }
    return this.__GestureController_47;
  }
  get _BrowserXhr_48():import27.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import48._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import29.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import29.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import30.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import48.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _Keyboard_54():import31.Keyboard {
    if ((this.__Keyboard_54 == null)) { (this.__Keyboard_54 = new import31.Keyboard(this._Config_13,this._Form_45,this.parent.get(import46.NgZone))); }
    return this.__Keyboard_54;
  }
  get _LoadingController_55():import32.LoadingController {
    if ((this.__LoadingController_55 == null)) { (this.__LoadingController_55 = new import32.LoadingController(this._App_14)); }
    return this.__LoadingController_55;
  }
  get _MenuController_56():import33.MenuController {
    if ((this.__MenuController_56 == null)) { (this.__MenuController_56 = new import33.MenuController()); }
    return this.__MenuController_56;
  }
  get _ModalController_57():import34.ModalController {
    if ((this.__ModalController_57 == null)) { (this.__ModalController_57 = new import34.ModalController(this._App_14)); }
    return this.__ModalController_57;
  }
  get _PickerController_58():import35.PickerController {
    if ((this.__PickerController_58 == null)) { (this.__PickerController_58 = new import35.PickerController(this._App_14)); }
    return this.__PickerController_58;
  }
  get _PopoverController_59():import36.PopoverController {
    if ((this.__PopoverController_59 == null)) { (this.__PopoverController_59 = new import36.PopoverController(this._App_14)); }
    return this.__PopoverController_59;
  }
  get _TapClick_60():import37.TapClick {
    if ((this.__TapClick_60 == null)) { (this.__TapClick_60 = new import37.TapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))); }
    return this.__TapClick_60;
  }
  get _ToastController_61():import38.ToastController {
    if ((this.__ToastController_61 == null)) { (this.__ToastController_61 = new import38.ToastController(this._App_14)); }
    return this.__ToastController_61;
  }
  get _Translate_62():import39.Translate {
    if ((this.__Translate_62 == null)) { (this.__Translate_62 = new import39.Translate()); }
    return this.__Translate_62;
  }
  get _TransitionController_63():import40.TransitionController {
    if ((this.__TransitionController_63 == null)) { (this.__TransitionController_63 = new import40.TransitionController()); }
    return this.__TransitionController_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._ExceptionHandler_6 = import4._exceptionHandler();
    this._UserUrl_7 = import49.getWindowLocation();
    this._QueryParams_8 = import50.setupQueryParams(this._UserUrl_7);
    this._UserAgent_9 = import49.getWindowUserAgent();
    this._UserNavigatorPlatform_10 = import49.getWindowPlatform();
    this._Platform_11 = import51.setupPlatform(this._QueryParams_8,this._UserAgent_9,this._UserNavigatorPlatform_10,this.parent.get(import46.NgZone));
    this._UserConfig_12 = null;
    this._Config_13 = import52.setupConfig(this._UserConfig_12,this._QueryParams_8,this._Platform_11);
    this._App_14 = new import7.App(this._Config_13,this._Platform_11);
    this._APP_INITIALIZER_15 = [
      import53.setupProvideEvents(this._Platform_11),
      import37.setupTapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))
    ]
    ;
    this._ApplicationInitStatus_16 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_15);
    this._Testability_17 = new import9.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__18 = new import10.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import54.Console),this,this._ExceptionHandler_6,this,this._ApplicationInitStatus_16,this.parent.get(import9.TestabilityRegistry,null),this._Testability_17);
    this._ApplicationRef_19 = this._ApplicationRef__18;
    this._IonicModule_20 = new import11.IonicModule(this.parent.get(import11.IonicModule,null),this._ApplicationRef_19);
    this._AppModule_21 = new import1.AppModule();
    return this._AppModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import55.ExceptionHandler)) { return this._ExceptionHandler_6; }
    if ((token === import50.UserUrl)) { return this._UserUrl_7; }
    if ((token === import50.QueryParams)) { return this._QueryParams_8; }
    if ((token === import51.UserAgent)) { return this._UserAgent_9; }
    if ((token === import51.UserNavigatorPlatform)) { return this._UserNavigatorPlatform_10; }
    if ((token === import51.Platform)) { return this._Platform_11; }
    if ((token === import52.UserConfig)) { return this._UserConfig_12; }
    if ((token === import52.Config)) { return this._Config_13; }
    if ((token === import7.App)) { return this._App_14; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import9.Testability)) { return this._Testability_17; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import11.IonicModule)) { return this._IonicModule_20; }
    if ((token === import1.AppModule)) { return this._AppModule_21; }
    if ((token === import12.Compiler)) { return this._Compiler_22; }
    if ((token === import56.ComponentResolver)) { return this._ComponentResolver_23; }
    if ((token === import43.APP_ID)) { return this._APP_ID_24; }
    if ((token === import57.DOCUMENT)) { return this._DOCUMENT_25; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_26; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_27; }
    if ((token === import14.EventManager)) { return this._EventManager_28; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_29; }
    if ((token === import58.AnimationDriver)) { return this._AnimationDriver_30; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_31; }
    if ((token === import59.RootRenderer)) { return this._RootRenderer_32; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_33; }
    if ((token === import60.SanitizationService)) { return this._SanitizationService_34; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import61.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import62.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_38; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_39; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import63.UserRoot)) { return this._UserRoot_42; }
    if ((token === import22.ActionSheetController)) { return this._ActionSheetController_43; }
    if ((token === import23.AlertController)) { return this._AlertController_44; }
    if ((token === import24.Form)) { return this._Form_45; }
    if ((token === import25.FeatureDetect)) { return this._FeatureDetect_46; }
    if ((token === import26.GestureController)) { return this._GestureController_47; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import65.Http)) { return this._Http_53; }
    if ((token === import31.Keyboard)) { return this._Keyboard_54; }
    if ((token === import32.LoadingController)) { return this._LoadingController_55; }
    if ((token === import33.MenuController)) { return this._MenuController_56; }
    if ((token === import34.ModalController)) { return this._ModalController_57; }
    if ((token === import35.PickerController)) { return this._PickerController_58; }
    if ((token === import36.PopoverController)) { return this._PopoverController_59; }
    if ((token === import37.TapClick)) { return this._TapClick_60; }
    if ((token === import38.ToastController)) { return this._ToastController_61; }
    if ((token === import39.Translate)) { return this._Translate_62; }
    if ((token === import40.TransitionController)) { return this._TransitionController_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
var renderType_E2EPage_Host:import66.RenderComponentType = null;
class _View_E2EPage_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EPage_0_4:import1.E2EPage;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage_Host0,renderType_E2EPage_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EPage_0_4 = new import1.E2EPage();
    this._appEl_0.initComponent(this._E2EPage_0_4,[],compView_0);
    compView_0.create(this._E2EPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EPage) && (0 === requestNodeIndex))) { return this._E2EPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EPage_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EPage_Host === null)) { (renderType_E2EPage_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EPageNgFactory:import72.ComponentFactory<import1.E2EPage> = new import72.ComponentFactory<import1.E2EPage>('ng-component',viewFactory_E2EPage_Host0,import1.E2EPage);
const styles_E2EPage:any[] = ['.map-cards[_ngcontent-%COMP%] img[_ngcontent-%COMP%] {\n    height: 200px;\n  }'];
var renderType_E2EPage:import66.RenderComponentType = null;
class _View_E2EPage0 extends import67.AppView<import1.E2EPage> {
  _el_0:any;
  _Header_0_3:import73.Header;
  _text_1:any;
  _el_2:any;
  private _appEl_2:import68.AppElement;
  _Toolbar_2_4:import73.Toolbar;
  _text_3:any;
  _el_4:any;
  private _appEl_4:import68.AppElement;
  _ToolbarTitle_4_4:import74.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  private _appEl_9:import68.AppElement;
  _Content_9_4:import75.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  private _appEl_15:import68.AppElement;
  _Button_15_4:import76.Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import77.Icon;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  private _appEl_20:import68.AppElement;
  _ItemContent_20_4:import78.ItemContent;
  _Item_20_5:import78.Item;
  _query_Label_20_0:import79.QueryList<any>;
  _query_Button_20_1:import79.QueryList<any>;
  _query_Icon_20_2:import79.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Icon_22_3:import77.Icon;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  private _appEl_31:import68.AppElement;
  _ItemContent_31_4:import78.ItemContent;
  _Item_31_5:import78.Item;
  _query_Label_31_0:import79.QueryList<any>;
  _query_Button_31_1:import79.QueryList<any>;
  _query_Icon_31_2:import79.QueryList<any>;
  _text_32:any;
  _el_33:any;
  _Icon_33_3:import77.Icon;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  private _appEl_42:import68.AppElement;
  _ItemContent_42_4:import78.ItemContent;
  _Item_42_5:import78.Item;
  _query_Label_42_0:import79.QueryList<any>;
  _query_Button_42_1:import79.QueryList<any>;
  _query_Icon_42_2:import79.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  private _appEl_50:import68.AppElement;
  _Button_50_4:import76.Button;
  _text_51:any;
  _el_52:any;
  _Icon_52_3:import77.Icon;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  private _appEl_61:import68.AppElement;
  _Button_61_4:import76.Button;
  _text_62:any;
  _el_63:any;
  _Icon_63_3:import77.Icon;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  private _appEl_66:import68.AppElement;
  _ItemContent_66_4:import78.ItemContent;
  _Item_66_5:import78.Item;
  _query_Label_66_0:import79.QueryList<any>;
  _query_Button_66_1:import79.QueryList<any>;
  _query_Icon_66_2:import79.QueryList<any>;
  _text_67:any;
  _el_68:any;
  _Icon_68_3:import77.Icon;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  private _appEl_77:import68.AppElement;
  _ItemContent_77_4:import78.ItemContent;
  _Item_77_5:import78.Item;
  _query_Label_77_0:import79.QueryList<any>;
  _query_Button_77_1:import79.QueryList<any>;
  _query_Icon_77_2:import79.QueryList<any>;
  _text_78:any;
  _el_79:any;
  _Icon_79_3:import77.Icon;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  private _appEl_88:import68.AppElement;
  _ItemContent_88_4:import78.ItemContent;
  _Item_88_5:import78.Item;
  _query_Label_88_0:import79.QueryList<any>;
  _query_Button_88_1:import79.QueryList<any>;
  _query_Icon_88_2:import79.QueryList<any>;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  private _appEl_96:import68.AppElement;
  _Button_96_4:import76.Button;
  _text_97:any;
  _el_98:any;
  _Icon_98_3:import77.Icon;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  private _appEl_107:import68.AppElement;
  _Button_107_4:import76.Button;
  _text_108:any;
  _el_109:any;
  _Icon_109_3:import77.Icon;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  private _appEl_112:import68.AppElement;
  _ItemContent_112_4:import78.ItemContent;
  _Item_112_5:import78.Item;
  _query_Label_112_0:import79.QueryList<any>;
  _query_Button_112_1:import79.QueryList<any>;
  _query_Icon_112_2:import79.QueryList<any>;
  _text_113:any;
  _el_114:any;
  _Icon_114_3:import77.Icon;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _text_122:any;
  _el_123:any;
  private _appEl_123:import68.AppElement;
  _ItemContent_123_4:import78.ItemContent;
  _Item_123_5:import78.Item;
  _query_Label_123_0:import79.QueryList<any>;
  _query_Button_123_1:import79.QueryList<any>;
  _query_Icon_123_2:import79.QueryList<any>;
  _text_124:any;
  _el_125:any;
  _Icon_125_3:import77.Icon;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  private _appEl_134:import68.AppElement;
  _ItemContent_134_4:import78.ItemContent;
  _Item_134_5:import78.Item;
  _query_Label_134_0:import79.QueryList<any>;
  _query_Button_134_1:import79.QueryList<any>;
  _query_Icon_134_2:import79.QueryList<any>;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _text_141:any;
  _el_142:any;
  private _appEl_142:import68.AppElement;
  _Button_142_4:import76.Button;
  _text_143:any;
  _el_144:any;
  _Icon_144_3:import77.Icon;
  _text_145:any;
  _text_146:any;
  _text_147:any;
  _text_148:any;
  _text_149:any;
  _text_150:any;
  private _expr_0:any;
  private _expr_1:any;
  private _expr_2:any;
  private _expr_3:any;
  private _expr_4:any;
  private _expr_5:any;
  private _expr_6:any;
  private _expr_7:any;
  private _expr_8:any;
  private _expr_9:any;
  private _expr_10:any;
  private _expr_11:any;
  private _expr_12:any;
  private _expr_13:any;
  private _expr_14:any;
  private _expr_15:any;
  private _expr_16:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage0,renderType_E2EPage,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',null);
    this._Header_0_3 = new import73.Header(this.parentInjector.get(import80.ViewController,null));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',null);
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import68.AppElement(2,0,this,this._el_2);
    var compView_2:any = import81.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import73.Toolbar(this.parentInjector.get(import80.ViewController,null),this._Header_0_3,this.parentInjector.get(import73.Footer,null),this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_2));
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText(null,'\n    ',null);
    this._el_4 = this.renderer.createElement(null,'ion-title',null);
    this._appEl_4 = new import68.AppElement(4,2,this,this._el_4);
    var compView_4:any = import83.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import74.ToolbarTitle(new import82.ElementRef(this._el_4),this._Toolbar_2_4,this.parentInjector.get(import84.Navbar,null));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText(null,'Map Card',null);
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],null);
    this._text_6 = this.renderer.createText(null,'\n  ',null);
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,null);
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',null);
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',null);
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this.renderer.setElementAttribute(this._el_9,'class','map-cards');
    this._appEl_9 = new import68.AppElement(9,null,this,this._el_9);
    var compView_9:any = import85.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import75.Content(new import82.ElementRef(this._el_9),this.parentInjector.get(import52.Config),this.parentInjector.get(import7.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import80.ViewController,null),this.parentInjector.get(import86.Tabs,null));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText(null,'\n\n  ',null);
    this._el_11 = this.renderer.createElement(null,'ion-card',null);
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_13 = this.renderer.createElement(this._el_11,'img',null);
    this.renderer.setElementAttribute(this._el_13,'src','data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==');
    this._text_14 = this.renderer.createText(this._el_11,'\n    ',null);
    this._el_15 = this.renderer.createElement(this._el_11,'button',null);
    this.renderer.setElementAttribute(this._el_15,'fab','');
    this.renderer.setElementAttribute(this._el_15,'fab-right','');
    this.renderer.setElementAttribute(this._el_15,'fab-top','');
    this._appEl_15 = new import68.AppElement(15,11,this,this._el_15);
    var compView_15:any = import87.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_15),this.renderer,null);
    this._appEl_15.initComponent(this._Button_15_4,[],compView_15);
    this._text_16 = this.renderer.createText(null,'\n      ',null);
    this._el_17 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_17,'name','pin');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText(null,'\n    ',null);
      compView_15.create(this._Button_15_4,[[].concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],null);
    this._text_19 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_20 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_20,'class','item');
    this._appEl_20 = new import68.AppElement(20,11,this,this._el_20);
    var compView_20:any = import88.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._ItemContent_20_4 = new import78.ItemContent();
    this._Item_20_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_20));
    this._query_Label_20_0 = new import79.QueryList<any>();
    this._query_Button_20_1 = new import79.QueryList<any>();
    this._query_Icon_20_2 = new import79.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_5,[],compView_20);
    this._text_21 = this.renderer.createText(null,'\n      ',null);
    this._el_22 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_22,'item-left','');
    this.renderer.setElementAttribute(this._el_22,'large','');
    this.renderer.setElementAttribute(this._el_22,'name','football');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText(null,'\n      ',null);
    this._el_24 = this.renderer.createElement(null,'h2',null);
    this._text_25 = this.renderer.createText(this._el_24,'Museum of Football',null);
    this._text_26 = this.renderer.createText(null,'\n      ',null);
    this._el_27 = this.renderer.createElement(null,'p',null);
    this._text_28 = this.renderer.createText(this._el_27,'11 N. Way St, Madison, WI 53703',null);
    this._text_29 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_20_0.reset([]);
    this._Item_20_5.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_5,[
      [].concat([this._el_22]),
      [],
      [].concat([
        this._text_21,
        this._text_23,
        this._el_24,
        this._text_26,
        this._el_27,
        this._text_29
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_30 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_31 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_31,'class','item');
    this._appEl_31 = new import68.AppElement(31,11,this,this._el_31);
    var compView_31:any = import88.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._ItemContent_31_4 = new import78.ItemContent();
    this._Item_31_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_31));
    this._query_Label_31_0 = new import79.QueryList<any>();
    this._query_Button_31_1 = new import79.QueryList<any>();
    this._query_Icon_31_2 = new import79.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_5,[],compView_31);
    this._text_32 = this.renderer.createText(null,'\n      ',null);
    this._el_33 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_33,'item-left','');
    this.renderer.setElementAttribute(this._el_33,'large','');
    this.renderer.setElementAttribute(this._el_33,'name','wine');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText(null,'\n      ',null);
    this._el_35 = this.renderer.createElement(null,'h2',null);
    this._text_36 = this.renderer.createText(this._el_35,'Institute of Fine Cocktails',null);
    this._text_37 = this.renderer.createText(null,'\n      ',null);
    this._el_38 = this.renderer.createElement(null,'p',null);
    this._text_39 = this.renderer.createText(this._el_38,'14 S. Hop Avenue, Madison, WI 53703',null);
    this._text_40 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_31_0.reset([]);
    this._Item_31_5.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_5,[
      [].concat([this._el_33]),
      [],
      [].concat([
        this._text_32,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_40
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_41 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_42 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_42,'class','item');
    this._appEl_42 = new import68.AppElement(42,11,this,this._el_42);
    var compView_42:any = import88.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._ItemContent_42_4 = new import78.ItemContent();
    this._Item_42_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_42));
    this._query_Label_42_0 = new import79.QueryList<any>();
    this._query_Button_42_1 = new import79.QueryList<any>();
    this._query_Icon_42_2 = new import79.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_5,[],compView_42);
    this._text_43 = this.renderer.createText(null,'\n      ',null);
    this._el_44 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_44,'item-left','');
    this._text_45 = this.renderer.createText(this._el_44,'18 min',null);
    this._text_46 = this.renderer.createText(null,'\n      ',null);
    this._el_47 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_47,'item-left','');
    this._text_48 = this.renderer.createText(this._el_47,'(2.6 mi)',null);
    this._text_49 = this.renderer.createText(null,'\n      ',null);
    this._el_50 = this.renderer.createElement(null,'button',null);
    this.renderer.setElementAttribute(this._el_50,'clear','');
    this.renderer.setElementAttribute(this._el_50,'item-right','');
    this.renderer.setElementAttribute(this._el_50,'primary','');
    this._appEl_50 = new import68.AppElement(50,42,this,this._el_50);
    var compView_50:any = import87.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_50),this.renderer,null);
    this._appEl_50.initComponent(this._Button_50_4,[],compView_50);
    this._text_51 = this.renderer.createText(null,'\n        ',null);
    this._el_52 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_52,'name','navigate');
    this.renderer.setElementAttribute(this._el_52,'role','img');
    this._Icon_52_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_52),this.renderer);
    this._text_53 = this.renderer.createText(null,'\n        Start\n      ',null);
      compView_50.create(this._Button_50_4,[[].concat([
        this._text_51,
        this._el_52,
        this._text_53
      ]
    )],null);
    this._text_54 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_42_0.reset([]);
    this._Item_42_5.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_5,[
      [].concat([
        this._el_44,
        this._el_47
      ]
      ),
      [],
      [].concat([
        this._text_43,
        this._text_46,
        this._text_49,
        this._text_54
      ]
      ),
      [],
      [].concat([this._el_50])
    ]
    ,null);
    this._text_55 = this.renderer.createText(this._el_11,'\n\n  ',null);
    this._text_56 = this.renderer.createText(null,'\n\n  ',null);
    this._el_57 = this.renderer.createElement(null,'ion-card',null);
    this._text_58 = this.renderer.createText(this._el_57,'\n\n    ',null);
    this._el_59 = this.renderer.createElement(this._el_57,'img',null);
    this.renderer.setElementAttribute(this._el_59,'src','data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==');
    this._text_60 = this.renderer.createText(this._el_57,'\n    ',null);
    this._el_61 = this.renderer.createElement(this._el_57,'button',null);
    this.renderer.setElementAttribute(this._el_61,'danger','');
    this.renderer.setElementAttribute(this._el_61,'fab','');
    this.renderer.setElementAttribute(this._el_61,'fab-right','');
    this.renderer.setElementAttribute(this._el_61,'fab-top','');
    this._appEl_61 = new import68.AppElement(61,57,this,this._el_61);
    var compView_61:any = import87.viewFactory_Button0(this.viewUtils,this.injector(61),this._appEl_61);
    this._Button_61_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_61),this.renderer,null);
    this._appEl_61.initComponent(this._Button_61_4,[],compView_61);
    this._text_62 = this.renderer.createText(null,'\n      ',null);
    this._el_63 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_63,'name','pin');
    this.renderer.setElementAttribute(this._el_63,'role','img');
    this._Icon_63_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_63),this.renderer);
    this._text_64 = this.renderer.createText(null,'\n    ',null);
      compView_61.create(this._Button_61_4,[[].concat([
        this._text_62,
        this._el_63,
        this._text_64
      ]
    )],null);
    this._text_65 = this.renderer.createText(this._el_57,'\n\n    ',null);
    this._el_66 = this.renderer.createElement(this._el_57,'ion-item',null);
    this.renderer.setElementAttribute(this._el_66,'class','item');
    this._appEl_66 = new import68.AppElement(66,57,this,this._el_66);
    var compView_66:any = import88.viewFactory_Item0(this.viewUtils,this.injector(66),this._appEl_66);
    this._ItemContent_66_4 = new import78.ItemContent();
    this._Item_66_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_66));
    this._query_Label_66_0 = new import79.QueryList<any>();
    this._query_Button_66_1 = new import79.QueryList<any>();
    this._query_Icon_66_2 = new import79.QueryList<any>();
    this._appEl_66.initComponent(this._Item_66_5,[],compView_66);
    this._text_67 = this.renderer.createText(null,'\n      ',null);
    this._el_68 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_68,'item-left','');
    this.renderer.setElementAttribute(this._el_68,'large','');
    this.renderer.setElementAttribute(this._el_68,'name','cloud');
    this.renderer.setElementAttribute(this._el_68,'role','img');
    this._Icon_68_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_68),this.renderer);
    this._text_69 = this.renderer.createText(null,'\n      ',null);
    this._el_70 = this.renderer.createElement(null,'h2',null);
    this._text_71 = this.renderer.createText(this._el_70,'Yoshi\'s Island',null);
    this._text_72 = this.renderer.createText(null,'\n      ',null);
    this._el_73 = this.renderer.createElement(null,'p',null);
    this._text_74 = this.renderer.createText(this._el_73,'Iggy Koopa',null);
    this._text_75 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_66_0.reset([]);
    this._Item_66_5.contentLabel = this._query_Label_66_0.first;
    compView_66.create(this._Item_66_5,[
      [].concat([this._el_68]),
      [],
      [].concat([
        this._text_67,
        this._text_69,
        this._el_70,
        this._text_72,
        this._el_73,
        this._text_75
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_76 = this.renderer.createText(this._el_57,'\n\n    ',null);
    this._el_77 = this.renderer.createElement(this._el_57,'ion-item',null);
    this.renderer.setElementAttribute(this._el_77,'class','item');
    this._appEl_77 = new import68.AppElement(77,57,this,this._el_77);
    var compView_77:any = import88.viewFactory_Item0(this.viewUtils,this.injector(77),this._appEl_77);
    this._ItemContent_77_4 = new import78.ItemContent();
    this._Item_77_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_77));
    this._query_Label_77_0 = new import79.QueryList<any>();
    this._query_Button_77_1 = new import79.QueryList<any>();
    this._query_Icon_77_2 = new import79.QueryList<any>();
    this._appEl_77.initComponent(this._Item_77_5,[],compView_77);
    this._text_78 = this.renderer.createText(null,'\n      ',null);
    this._el_79 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_79,'item-left','');
    this.renderer.setElementAttribute(this._el_79,'large','');
    this.renderer.setElementAttribute(this._el_79,'name','leaf');
    this.renderer.setElementAttribute(this._el_79,'role','img');
    this._Icon_79_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(null,'\n      ',null);
    this._el_81 = this.renderer.createElement(null,'h2',null);
    this._text_82 = this.renderer.createText(this._el_81,'Forest of Illusion',null);
    this._text_83 = this.renderer.createText(null,'\n      ',null);
    this._el_84 = this.renderer.createElement(null,'p',null);
    this._text_85 = this.renderer.createText(this._el_84,'Roy Koopa',null);
    this._text_86 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_77_0.reset([]);
    this._Item_77_5.contentLabel = this._query_Label_77_0.first;
    compView_77.create(this._Item_77_5,[
      [].concat([this._el_79]),
      [],
      [].concat([
        this._text_78,
        this._text_80,
        this._el_81,
        this._text_83,
        this._el_84,
        this._text_86
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_87 = this.renderer.createText(this._el_57,'\n\n    ',null);
    this._el_88 = this.renderer.createElement(this._el_57,'ion-item',null);
    this.renderer.setElementAttribute(this._el_88,'class','item');
    this._appEl_88 = new import68.AppElement(88,57,this,this._el_88);
    var compView_88:any = import88.viewFactory_Item0(this.viewUtils,this.injector(88),this._appEl_88);
    this._ItemContent_88_4 = new import78.ItemContent();
    this._Item_88_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_88));
    this._query_Label_88_0 = new import79.QueryList<any>();
    this._query_Button_88_1 = new import79.QueryList<any>();
    this._query_Icon_88_2 = new import79.QueryList<any>();
    this._appEl_88.initComponent(this._Item_88_5,[],compView_88);
    this._text_89 = this.renderer.createText(null,'\n      ',null);
    this._el_90 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_90,'item-left','');
    this._text_91 = this.renderer.createText(this._el_90,'3 hr',null);
    this._text_92 = this.renderer.createText(null,'\n      ',null);
    this._el_93 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_93,'item-left','');
    this._text_94 = this.renderer.createText(this._el_93,'(4.8 mi)',null);
    this._text_95 = this.renderer.createText(null,'\n      ',null);
    this._el_96 = this.renderer.createElement(null,'button',null);
    this.renderer.setElementAttribute(this._el_96,'clear','');
    this.renderer.setElementAttribute(this._el_96,'danger','');
    this.renderer.setElementAttribute(this._el_96,'item-right','');
    this._appEl_96 = new import68.AppElement(96,88,this,this._el_96);
    var compView_96:any = import87.viewFactory_Button0(this.viewUtils,this.injector(96),this._appEl_96);
    this._Button_96_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_96),this.renderer,null);
    this._appEl_96.initComponent(this._Button_96_4,[],compView_96);
    this._text_97 = this.renderer.createText(null,'\n        ',null);
    this._el_98 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_98,'name','navigate');
    this.renderer.setElementAttribute(this._el_98,'role','img');
    this._Icon_98_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_98),this.renderer);
    this._text_99 = this.renderer.createText(null,'\n        Start\n      ',null);
      compView_96.create(this._Button_96_4,[[].concat([
        this._text_97,
        this._el_98,
        this._text_99
      ]
    )],null);
    this._text_100 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_88_0.reset([]);
    this._Item_88_5.contentLabel = this._query_Label_88_0.first;
    compView_88.create(this._Item_88_5,[
      [].concat([
        this._el_90,
        this._el_93
      ]
      ),
      [],
      [].concat([
        this._text_89,
        this._text_92,
        this._text_95,
        this._text_100
      ]
      ),
      [],
      [].concat([this._el_96])
    ]
    ,null);
    this._text_101 = this.renderer.createText(this._el_57,'\n\n  ',null);
    this._text_102 = this.renderer.createText(null,'\n\n  ',null);
    this._el_103 = this.renderer.createElement(null,'ion-card',null);
    this._text_104 = this.renderer.createText(this._el_103,'\n\n    ',null);
    this._el_105 = this.renderer.createElement(this._el_103,'img',null);
    this.renderer.setElementAttribute(this._el_105,'src','data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==');
    this._text_106 = this.renderer.createText(this._el_103,'\n    ',null);
    this._el_107 = this.renderer.createElement(this._el_103,'button',null);
    this.renderer.setElementAttribute(this._el_107,'fab','');
    this.renderer.setElementAttribute(this._el_107,'fab-right','');
    this.renderer.setElementAttribute(this._el_107,'fab-top','');
    this.renderer.setElementAttribute(this._el_107,'secondary','');
    this._appEl_107 = new import68.AppElement(107,103,this,this._el_107);
    var compView_107:any = import87.viewFactory_Button0(this.viewUtils,this.injector(107),this._appEl_107);
    this._Button_107_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_107),this.renderer,null);
    this._appEl_107.initComponent(this._Button_107_4,[],compView_107);
    this._text_108 = this.renderer.createText(null,'\n      ',null);
    this._el_109 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_109,'name','pin');
    this.renderer.setElementAttribute(this._el_109,'role','img');
    this._Icon_109_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_109),this.renderer);
    this._text_110 = this.renderer.createText(null,'\n    ',null);
      compView_107.create(this._Button_107_4,[[].concat([
        this._text_108,
        this._el_109,
        this._text_110
      ]
    )],null);
    this._text_111 = this.renderer.createText(this._el_103,'\n\n    ',null);
    this._el_112 = this.renderer.createElement(this._el_103,'ion-item',null);
    this.renderer.setElementAttribute(this._el_112,'class','item');
    this._appEl_112 = new import68.AppElement(112,103,this,this._el_112);
    var compView_112:any = import88.viewFactory_Item0(this.viewUtils,this.injector(112),this._appEl_112);
    this._ItemContent_112_4 = new import78.ItemContent();
    this._Item_112_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_112));
    this._query_Label_112_0 = new import79.QueryList<any>();
    this._query_Button_112_1 = new import79.QueryList<any>();
    this._query_Icon_112_2 = new import79.QueryList<any>();
    this._appEl_112.initComponent(this._Item_112_5,[],compView_112);
    this._text_113 = this.renderer.createText(null,'\n      ',null);
    this._el_114 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_114,'item-left','');
    this.renderer.setElementAttribute(this._el_114,'large','');
    this.renderer.setElementAttribute(this._el_114,'name','information-circle');
    this.renderer.setElementAttribute(this._el_114,'role','img');
    this._Icon_114_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_114),this.renderer);
    this._text_115 = this.renderer.createText(null,'\n      ',null);
    this._el_116 = this.renderer.createElement(null,'h2',null);
    this._text_117 = this.renderer.createText(this._el_116,'Museum of Information',null);
    this._text_118 = this.renderer.createText(null,'\n      ',null);
    this._el_119 = this.renderer.createElement(null,'p',null);
    this._text_120 = this.renderer.createText(this._el_119,'44 Rue de Info, 75010 Paris, France',null);
    this._text_121 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_112_0.reset([]);
    this._Item_112_5.contentLabel = this._query_Label_112_0.first;
    compView_112.create(this._Item_112_5,[
      [].concat([this._el_114]),
      [],
      [].concat([
        this._text_113,
        this._text_115,
        this._el_116,
        this._text_118,
        this._el_119,
        this._text_121
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_122 = this.renderer.createText(this._el_103,'\n\n    ',null);
    this._el_123 = this.renderer.createElement(this._el_103,'ion-item',null);
    this.renderer.setElementAttribute(this._el_123,'class','item');
    this._appEl_123 = new import68.AppElement(123,103,this,this._el_123);
    var compView_123:any = import88.viewFactory_Item0(this.viewUtils,this.injector(123),this._appEl_123);
    this._ItemContent_123_4 = new import78.ItemContent();
    this._Item_123_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_123));
    this._query_Label_123_0 = new import79.QueryList<any>();
    this._query_Button_123_1 = new import79.QueryList<any>();
    this._query_Icon_123_2 = new import79.QueryList<any>();
    this._appEl_123.initComponent(this._Item_123_5,[],compView_123);
    this._text_124 = this.renderer.createText(null,'\n      ',null);
    this._el_125 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_125,'item-left','');
    this.renderer.setElementAttribute(this._el_125,'large','');
    this.renderer.setElementAttribute(this._el_125,'name','leaf');
    this.renderer.setElementAttribute(this._el_125,'role','img');
    this._Icon_125_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_125),this.renderer);
    this._text_126 = this.renderer.createText(null,'\n      ',null);
    this._el_127 = this.renderer.createElement(null,'h2',null);
    this._text_128 = this.renderer.createText(this._el_127,'General Pharmacy',null);
    this._text_129 = this.renderer.createText(null,'\n      ',null);
    this._el_130 = this.renderer.createElement(null,'p',null);
    this._text_131 = this.renderer.createText(this._el_130,'1 Avenue Faux, 75010 Paris, France',null);
    this._text_132 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_123_0.reset([]);
    this._Item_123_5.contentLabel = this._query_Label_123_0.first;
    compView_123.create(this._Item_123_5,[
      [].concat([this._el_125]),
      [],
      [].concat([
        this._text_124,
        this._text_126,
        this._el_127,
        this._text_129,
        this._el_130,
        this._text_132
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_133 = this.renderer.createText(this._el_103,'\n\n    ',null);
    this._el_134 = this.renderer.createElement(this._el_103,'ion-item',null);
    this.renderer.setElementAttribute(this._el_134,'class','item');
    this._appEl_134 = new import68.AppElement(134,103,this,this._el_134);
    var compView_134:any = import88.viewFactory_Item0(this.viewUtils,this.injector(134),this._appEl_134);
    this._ItemContent_134_4 = new import78.ItemContent();
    this._Item_134_5 = new import78.Item(this.parentInjector.get(import24.Form),this.renderer,new import82.ElementRef(this._el_134));
    this._query_Label_134_0 = new import79.QueryList<any>();
    this._query_Button_134_1 = new import79.QueryList<any>();
    this._query_Icon_134_2 = new import79.QueryList<any>();
    this._appEl_134.initComponent(this._Item_134_5,[],compView_134);
    this._text_135 = this.renderer.createText(null,'\n      ',null);
    this._el_136 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_136,'item-left','');
    this.renderer.setElementAttribute(this._el_136,'secondary','');
    this._text_137 = this.renderer.createText(this._el_136,'26 min',null);
    this._text_138 = this.renderer.createText(null,'\n      ',null);
    this._el_139 = this.renderer.createElement(null,'span',null);
    this.renderer.setElementAttribute(this._el_139,'item-left','');
    this._text_140 = this.renderer.createText(this._el_139,'(8.1 mi)',null);
    this._text_141 = this.renderer.createText(null,'\n      ',null);
    this._el_142 = this.renderer.createElement(null,'button',null);
    this.renderer.setElementAttribute(this._el_142,'clear','');
    this.renderer.setElementAttribute(this._el_142,'item-right','');
    this.renderer.setElementAttribute(this._el_142,'secondary','');
    this._appEl_142 = new import68.AppElement(142,134,this,this._el_142);
    var compView_142:any = import87.viewFactory_Button0(this.viewUtils,this.injector(142),this._appEl_142);
    this._Button_142_4 = new import76.Button(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_142),this.renderer,null);
    this._appEl_142.initComponent(this._Button_142_4,[],compView_142);
    this._text_143 = this.renderer.createText(null,'\n        ',null);
    this._el_144 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_144,'name','navigate');
    this.renderer.setElementAttribute(this._el_144,'role','img');
    this._Icon_144_3 = new import77.Icon(this.parentInjector.get(import52.Config),new import82.ElementRef(this._el_144),this.renderer);
    this._text_145 = this.renderer.createText(null,'\n        Start\n      ',null);
      compView_142.create(this._Button_142_4,[[].concat([
        this._text_143,
        this._el_144,
        this._text_145
      ]
    )],null);
    this._text_146 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_134_0.reset([]);
    this._Item_134_5.contentLabel = this._query_Label_134_0.first;
    compView_134.create(this._Item_134_5,[
      [].concat([
        this._el_136,
        this._el_139
      ]
      ),
      [],
      [].concat([
        this._text_135,
        this._text_138,
        this._text_141,
        this._text_146
      ]
      ),
      [],
      [].concat([this._el_142])
    ]
    ,null);
    this._text_147 = this.renderer.createText(this._el_103,'\n\n  ',null);
    this._text_148 = this.renderer.createText(null,'\n\n',null);
    compView_9.create(this._Content_9_4,[
      [].concat([
        this._text_10,
        this._el_11,
        this._text_56,
        this._el_57,
        this._text_102,
        this._el_103,
        this._text_148
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_149 = this.renderer.createText(parentRenderNode,'\n\n\n',null);
    this._text_150 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import71.UNINITIALIZED;
    this._expr_1 = import71.UNINITIALIZED;
    this._expr_2 = import71.UNINITIALIZED;
    this._expr_3 = import71.UNINITIALIZED;
    this._expr_4 = import71.UNINITIALIZED;
    this._expr_5 = import71.UNINITIALIZED;
    this._expr_6 = import71.UNINITIALIZED;
    this._expr_7 = import71.UNINITIALIZED;
    this._expr_8 = import71.UNINITIALIZED;
    this._expr_9 = import71.UNINITIALIZED;
    this._expr_10 = import71.UNINITIALIZED;
    this._expr_11 = import71.UNINITIALIZED;
    this._expr_12 = import71.UNINITIALIZED;
    this._expr_13 = import71.UNINITIALIZED;
    this._expr_14 = import71.UNINITIALIZED;
    this._expr_15 = import71.UNINITIALIZED;
    this._expr_16 = import71.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._text_146,
      this._text_147,
      this._text_148,
      this._text_149,
      this._text_150
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import74.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import73.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Toolbar_2_4; }
    if (((token === import73.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import77.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3; }
    if (((token === import76.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4; }
    if (((token === import77.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3; }
    if (((token === import78.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_20_4; }
    if (((token === import78.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_20_5; }
    if (((token === import77.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3; }
    if (((token === import78.ItemContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_31_4; }
    if (((token === import78.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_31_5; }
    if (((token === import77.Icon) && (52 === requestNodeIndex))) { return this._Icon_52_3; }
    if (((token === import76.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Button_50_4; }
    if (((token === import78.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._ItemContent_42_4; }
    if (((token === import78.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Item_42_5; }
    if (((token === import77.Icon) && (63 === requestNodeIndex))) { return this._Icon_63_3; }
    if (((token === import76.Button) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Button_61_4; }
    if (((token === import77.Icon) && (68 === requestNodeIndex))) { return this._Icon_68_3; }
    if (((token === import78.ItemContent) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ItemContent_66_4; }
    if (((token === import78.Item) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Item_66_5; }
    if (((token === import77.Icon) && (79 === requestNodeIndex))) { return this._Icon_79_3; }
    if (((token === import78.ItemContent) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._ItemContent_77_4; }
    if (((token === import78.Item) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 86)))) { return this._Item_77_5; }
    if (((token === import77.Icon) && (98 === requestNodeIndex))) { return this._Icon_98_3; }
    if (((token === import76.Button) && ((96 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._Button_96_4; }
    if (((token === import78.ItemContent) && ((88 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._ItemContent_88_4; }
    if (((token === import78.Item) && ((88 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._Item_88_5; }
    if (((token === import77.Icon) && (109 === requestNodeIndex))) { return this._Icon_109_3; }
    if (((token === import76.Button) && ((107 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._Button_107_4; }
    if (((token === import77.Icon) && (114 === requestNodeIndex))) { return this._Icon_114_3; }
    if (((token === import78.ItemContent) && ((112 <= requestNodeIndex) && (requestNodeIndex <= 121)))) { return this._ItemContent_112_4; }
    if (((token === import78.Item) && ((112 <= requestNodeIndex) && (requestNodeIndex <= 121)))) { return this._Item_112_5; }
    if (((token === import77.Icon) && (125 === requestNodeIndex))) { return this._Icon_125_3; }
    if (((token === import78.ItemContent) && ((123 <= requestNodeIndex) && (requestNodeIndex <= 132)))) { return this._ItemContent_123_4; }
    if (((token === import78.Item) && ((123 <= requestNodeIndex) && (requestNodeIndex <= 132)))) { return this._Item_123_5; }
    if (((token === import77.Icon) && (144 === requestNodeIndex))) { return this._Icon_144_3; }
    if (((token === import76.Button) && ((142 <= requestNodeIndex) && (requestNodeIndex <= 145)))) { return this._Button_142_4; }
    if (((token === import78.ItemContent) && ((134 <= requestNodeIndex) && (requestNodeIndex <= 146)))) { return this._ItemContent_134_4; }
    if (((token === import78.Item) && ((134 <= requestNodeIndex) && (requestNodeIndex <= 146)))) { return this._Item_134_5; }
    if (((token === import75.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 148)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_15_4.ngOnInit(); }
    const currVal_2:any = 'pin';
    if (import69.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_17_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'football';
    if (import69.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_22_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'wine';
    if (import69.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_33_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    changed = false;
    const currVal_5:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Button_50_4.clear = currVal_5;
      changed = true;
      this._expr_5 = currVal_5;
    }
    if (changed) { this._appEl_50.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_50_4.ngOnInit(); }
    const currVal_6:any = 'navigate';
    if (import69.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_52_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_61_4.ngOnInit(); }
    const currVal_7:any = 'pin';
    if (import69.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_63_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'cloud';
    if (import69.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Icon_68_3.name = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'leaf';
    if (import69.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_79_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    changed = false;
    const currVal_10:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Button_96_4.clear = currVal_10;
      changed = true;
      this._expr_10 = currVal_10;
    }
    if (changed) { this._appEl_96.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_96_4.ngOnInit(); }
    const currVal_11:any = 'navigate';
    if (import69.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Icon_98_3.name = currVal_11;
      this._expr_11 = currVal_11;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_107_4.ngOnInit(); }
    const currVal_12:any = 'pin';
    if (import69.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_109_3.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 'information-circle';
    if (import69.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_114_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'leaf';
    if (import69.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_125_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    changed = false;
    const currVal_15:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Button_142_4.clear = currVal_15;
      changed = true;
      this._expr_15 = currVal_15;
    }
    if (changed) { this._appEl_142.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_142_4.ngOnInit(); }
    const currVal_16:any = 'navigate';
    if (import69.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_144_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset([]);
        this._Item_20_5._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([this._Icon_22_3]);
        this._Item_20_5._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset([]);
        this._Item_31_5._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset([this._Icon_33_3]);
        this._Item_31_5._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([this._Button_50_4]);
        this._Item_42_5._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([]);
        this._Item_42_5._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_66_1.dirty) {
        this._query_Button_66_1.reset([]);
        this._Item_66_5._buttons = this._query_Button_66_1;
        this._query_Button_66_1.notifyOnChanges();
      }
      if (this._query_Icon_66_2.dirty) {
        this._query_Icon_66_2.reset([this._Icon_68_3]);
        this._Item_66_5._icons = this._query_Icon_66_2;
        this._query_Icon_66_2.notifyOnChanges();
      }
      if (this._query_Button_77_1.dirty) {
        this._query_Button_77_1.reset([]);
        this._Item_77_5._buttons = this._query_Button_77_1;
        this._query_Button_77_1.notifyOnChanges();
      }
      if (this._query_Icon_77_2.dirty) {
        this._query_Icon_77_2.reset([this._Icon_79_3]);
        this._Item_77_5._icons = this._query_Icon_77_2;
        this._query_Icon_77_2.notifyOnChanges();
      }
      if (this._query_Button_88_1.dirty) {
        this._query_Button_88_1.reset([this._Button_96_4]);
        this._Item_88_5._buttons = this._query_Button_88_1;
        this._query_Button_88_1.notifyOnChanges();
      }
      if (this._query_Icon_88_2.dirty) {
        this._query_Icon_88_2.reset([]);
        this._Item_88_5._icons = this._query_Icon_88_2;
        this._query_Icon_88_2.notifyOnChanges();
      }
      if (this._query_Button_112_1.dirty) {
        this._query_Button_112_1.reset([]);
        this._Item_112_5._buttons = this._query_Button_112_1;
        this._query_Button_112_1.notifyOnChanges();
      }
      if (this._query_Icon_112_2.dirty) {
        this._query_Icon_112_2.reset([this._Icon_114_3]);
        this._Item_112_5._icons = this._query_Icon_112_2;
        this._query_Icon_112_2.notifyOnChanges();
      }
      if (this._query_Button_123_1.dirty) {
        this._query_Button_123_1.reset([]);
        this._Item_123_5._buttons = this._query_Button_123_1;
        this._query_Button_123_1.notifyOnChanges();
      }
      if (this._query_Icon_123_2.dirty) {
        this._query_Icon_123_2.reset([this._Icon_125_3]);
        this._Item_123_5._icons = this._query_Icon_123_2;
        this._query_Icon_123_2.notifyOnChanges();
      }
      if (this._query_Button_134_1.dirty) {
        this._query_Button_134_1.reset([this._Button_142_4]);
        this._Item_134_5._buttons = this._query_Button_134_1;
        this._query_Button_134_1.notifyOnChanges();
      }
      if (this._query_Icon_134_2.dirty) {
        this._query_Icon_134_2.reset([]);
        this._Item_134_5._icons = this._query_Icon_134_2;
        this._query_Icon_134_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.ngAfterContentInit(); }
      this._Button_15_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_31_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.ngAfterContentInit(); }
      this._Button_50_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_42_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_61_4.ngAfterContentInit(); }
      this._Button_61_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_66_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_77_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_96_4.ngAfterContentInit(); }
      this._Button_96_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_88_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_107_4.ngAfterContentInit(); }
      this._Button_107_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_112_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_123_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_142_4.ngAfterContentInit(); }
      this._Button_142_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_134_5.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Content_9_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_17_3.ngOnDestroy();
    this._Icon_22_3.ngOnDestroy();
    this._Icon_33_3.ngOnDestroy();
    this._Icon_52_3.ngOnDestroy();
    this._Icon_63_3.ngOnDestroy();
    this._Icon_68_3.ngOnDestroy();
    this._Icon_79_3.ngOnDestroy();
    this._Icon_98_3.ngOnDestroy();
    this._Icon_109_3.ngOnDestroy();
    this._Icon_114_3.ngOnDestroy();
    this._Icon_125_3.ngOnDestroy();
    this._Icon_144_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_E2EPage0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EPage> {
  if ((renderType_E2EPage === null)) { (renderType_E2EPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/card/map/main.html',0,import89.ViewEncapsulation.Emulated,styles_E2EPage,{})); }
  return new _View_E2EPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_E2EApp_Host:import66.RenderComponentType = null;
class _View_E2EApp_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EApp_0_4:import1.E2EApp;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp_Host0,renderType_E2EApp_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EApp_0_4 = new import1.E2EApp();
    this._appEl_0.initComponent(this._E2EApp_0_4,[],compView_0);
    compView_0.create(this._E2EApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EApp) && (0 === requestNodeIndex))) { return this._E2EApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EApp_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EApp_Host === null)) { (renderType_E2EApp_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EAppNgFactory:import72.ComponentFactory<import1.E2EApp> = new import72.ComponentFactory<import1.E2EApp>('ng-component',viewFactory_E2EApp_Host0,import1.E2EApp);
const styles_E2EApp:any[] = [];
var renderType_E2EApp:import66.RenderComponentType = null;
class _View_E2EApp0 extends import67.AppView<import1.E2EApp> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _Nav_0_4:import90.Nav;
  private _expr_0:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp0,renderType_E2EApp,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = import91.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import90.Nav(this.parentInjector.get(import80.ViewController,null),this.parentInjector.get(import92.NavControllerBase,null),this.parentInjector.get(import7.App),this.parentInjector.get(import52.Config),this.parentInjector.get(import31.Keyboard),new import82.ElementRef(this._el_0),this.parentInjector.get(import46.NgZone),this.renderer,this.parentInjector.get(import93.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import71.UNINITIALIZED;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import90.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_E2EApp0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EApp> {
  if ((renderType_E2EApp === null)) { (renderType_E2EApp = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/card/map/AppModule.ts class E2EApp - inline template',0,import89.ViewEncapsulation.None,styles_E2EApp,{})); }
  return new _View_E2EApp0(viewUtils,parentInjector,declarationEl);
}