/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../../dist/components/app/app';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '../../../dist/ionic-module';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '../../../dist/components/action-sheet/action-sheet';
import * as import23 from '../../../dist/components/alert/alert';
import * as import24 from '../../../dist/util/form';
import * as import25 from '../../../dist/util/feature-detect';
import * as import26 from '../../../dist/gestures/gesture-controller';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '../../../dist/util/keyboard';
import * as import32 from '../../../dist/components/loading/loading';
import * as import33 from '../../../dist/components/menu/menu-controller';
import * as import34 from '../../../dist/components/modal/modal';
import * as import35 from '../../../dist/components/picker/picker';
import * as import36 from '../../../dist/components/popover/popover';
import * as import37 from '../../../dist/components/tap-click/tap-click';
import * as import38 from '../../../dist/components/toast/toast';
import * as import39 from '../../../dist/translation/translate';
import * as import40 from '../../../dist/transitions/transition-controller';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../../../dist/components/app/app-root.d.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/http/http';
import * as import49 from '../../../dist/providers';
import * as import50 from '../../../dist/platform/query-params';
import * as import51 from '../../../dist/platform/platform';
import * as import52 from '../../../dist/config/config';
import * as import53 from '../../../dist/util/events';
import * as import54 from '@angular/core/src/console';
import * as import55 from '@angular/core/src/facade/exception_handler';
import * as import56 from '@angular/core/src/linker/component_resolver';
import * as import57 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import58 from '@angular/platform-browser/src/dom/animation_driver';
import * as import59 from '@angular/core/src/render/api';
import * as import60 from '@angular/core/src/security';
import * as import61 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import62 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import63 from '../../../dist/components/app/app-root';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/core/src/render/api';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import70 from '@angular/core/src/linker/view_type';
import * as import71 from '@angular/core/src/change_detection/change_detection';
import * as import72 from '@angular/core/src/linker/component_factory';
import * as import73 from '../../../dist/components/toolbar/toolbar';
import * as import74 from '../../../dist/components/toolbar/toolbar-title';
import * as import75 from '../../../dist/components/content/content';
import * as import76 from '../../../dist/components/list/list';
import * as import77 from '../../../dist/components/item/item';
import * as import78 from '@angular/core/src/linker/query_list';
import * as import79 from '../../../dist/components/icon/icon';
import * as import80 from '../../../dist/components/label/label';
import * as import81 from '../../../dist/components/toggle/toggle';
import * as import82 from '../../../dist/components/button/button';
import * as import83 from '../../../dist/components/nav/view-controller';
import * as import84 from '../../../dist/components/toolbar/toolbar.d.ngfactory';
import * as import85 from '@angular/core/src/linker/element_ref';
import * as import86 from '../../../dist/components/toolbar/toolbar-title.d.ngfactory';
import * as import87 from '../../../dist/components/navbar/navbar';
import * as import88 from '../../../dist/components/content/content.d.ngfactory';
import * as import89 from '../../../dist/components/tabs/tabs';
import * as import90 from '../../../dist/components/item/item.d.ngfactory';
import * as import91 from '../../../dist/components/toggle/toggle.d.ngfactory';
import * as import92 from '../../../dist/components/button/button.d.ngfactory';
import * as import93 from '@angular/forms/src/directives/control_value_accessor';
import * as import94 from '@angular/core/src/metadata/view';
import * as import95 from '../../../dist/components/nav/nav';
import * as import96 from '../../../dist/components/nav/nav.d.ngfactory';
import * as import97 from '../../../dist/components/nav/nav-controller-base';
import * as import98 from '@angular/core/src/linker/component_factory_resolver';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _ExceptionHandler_6:any;
  _UserUrl_7:any;
  _QueryParams_8:any;
  _UserAgent_9:any;
  _UserNavigatorPlatform_10:any;
  _Platform_11:any;
  _UserConfig_12:any;
  _Config_13:any;
  _App_14:import7.App;
  _APP_INITIALIZER_15:any[];
  _ApplicationInitStatus_16:import8.ApplicationInitStatus;
  _Testability_17:import9.Testability;
  _ApplicationRef__18:import10.ApplicationRef_;
  _ApplicationRef_19:any;
  _IonicModule_20:import11.IonicModule;
  _AppModule_21:import1.AppModule;
  __Compiler_22:import12.Compiler;
  __ComponentResolver_23:any;
  __APP_ID_24:any;
  __DOCUMENT_25:any;
  __HAMMER_GESTURE_CONFIG_26:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_27:any[];
  __EventManager_28:import14.EventManager;
  __DomSharedStylesHost_29:import15.DomSharedStylesHost;
  __AnimationDriver_30:any;
  __DomRootRenderer_31:import16.DomRootRenderer_;
  __RootRenderer_32:any;
  __DomSanitizationService_33:import17.DomSanitizationServiceImpl;
  __SanitizationService_34:any;
  __ViewUtils_35:import18.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DynamicComponentLoader_38:import19.DynamicComponentLoader_;
  __SharedStylesHost_39:any;
  __RadioControlRegistry_40:import20.RadioControlRegistry;
  __FormBuilder_41:import21.FormBuilder;
  __UserRoot_42:any;
  __ActionSheetController_43:import22.ActionSheetController;
  __AlertController_44:import23.AlertController;
  __Form_45:import24.Form;
  __FeatureDetect_46:import25.FeatureDetect;
  __GestureController_47:import26.GestureController;
  __BrowserXhr_48:import27.BrowserXhr;
  __ResponseOptions_49:import28.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import29.XHRBackend;
  __RequestOptions_52:import30.BaseRequestOptions;
  __Http_53:any;
  __Keyboard_54:import31.Keyboard;
  __LoadingController_55:import32.LoadingController;
  __MenuController_56:import33.MenuController;
  __ModalController_57:import34.ModalController;
  __PickerController_58:import35.PickerController;
  __PopoverController_59:import36.PopoverController;
  __TapClick_60:import37.TapClick;
  __ToastController_61:import38.ToastController;
  __Translate_62:import39.Translate;
  __TransitionController_63:import40.TransitionController;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.AppRootNgFactory,
      E2EAppNgFactory,
      E2EAppNgFactory,
      E2EPageNgFactory
    ]
    ,[]);
  }
  get _Compiler_22():import12.Compiler {
    if ((this.__Compiler_22 == null)) { (this.__Compiler_22 = new import12.Compiler()); }
    return this.__Compiler_22;
  }
  get _ComponentResolver_23():any {
    if ((this.__ComponentResolver_23 == null)) { (this.__ComponentResolver_23 = this._Compiler_22); }
    return this.__ComponentResolver_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == null)) { (this.__APP_ID_24 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_24;
  }
  get _DOCUMENT_25():any {
    if ((this.__DOCUMENT_25 == null)) { (this.__DOCUMENT_25 = import4._document()); }
    return this.__DOCUMENT_25;
  }
  get _HAMMER_GESTURE_CONFIG_26():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_26 == null)) { (this.__HAMMER_GESTURE_CONFIG_26 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_26;
  }
  get _EVENT_MANAGER_PLUGINS_27():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_27 == null)) { (this.__EVENT_MANAGER_PLUGINS_27 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_26)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_27;
  }
  get _EventManager_28():import14.EventManager {
    if ((this.__EventManager_28 == null)) { (this.__EventManager_28 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_27,this.parent.get(import46.NgZone))); }
    return this.__EventManager_28;
  }
  get _DomSharedStylesHost_29():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_29 == null)) { (this.__DomSharedStylesHost_29 = new import15.DomSharedStylesHost(this._DOCUMENT_25)); }
    return this.__DomSharedStylesHost_29;
  }
  get _AnimationDriver_30():any {
    if ((this.__AnimationDriver_30 == null)) { (this.__AnimationDriver_30 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_30;
  }
  get _DomRootRenderer_31():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_31 == null)) { (this.__DomRootRenderer_31 = new import16.DomRootRenderer_(this._DOCUMENT_25,this._EventManager_28,this._DomSharedStylesHost_29,this._AnimationDriver_30)); }
    return this.__DomRootRenderer_31;
  }
  get _RootRenderer_32():any {
    if ((this.__RootRenderer_32 == null)) { (this.__RootRenderer_32 = import47._createConditionalRootRenderer(this._DomRootRenderer_31)); }
    return this.__RootRenderer_32;
  }
  get _DomSanitizationService_33():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_33 == null)) { (this.__DomSanitizationService_33 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_33;
  }
  get _SanitizationService_34():any {
    if ((this.__SanitizationService_34 == null)) { (this.__SanitizationService_34 = this._DomSanitizationService_33); }
    return this.__SanitizationService_34;
  }
  get _ViewUtils_35():import18.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import18.ViewUtils(this._RootRenderer_32,this._APP_ID_24,this._SanitizationService_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _DynamicComponentLoader_38():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_38 == null)) { (this.__DynamicComponentLoader_38 = new import19.DynamicComponentLoader_(this._Compiler_22)); }
    return this.__DynamicComponentLoader_38;
  }
  get _SharedStylesHost_39():any {
    if ((this.__SharedStylesHost_39 == null)) { (this.__SharedStylesHost_39 = this._DomSharedStylesHost_29); }
    return this.__SharedStylesHost_39;
  }
  get _RadioControlRegistry_40():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _FormBuilder_41():import21.FormBuilder {
    if ((this.__FormBuilder_41 == null)) { (this.__FormBuilder_41 = new import21.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _UserRoot_42():any {
    if ((this.__UserRoot_42 == null)) { (this.__UserRoot_42 = import1.E2EApp); }
    return this.__UserRoot_42;
  }
  get _ActionSheetController_43():import22.ActionSheetController {
    if ((this.__ActionSheetController_43 == null)) { (this.__ActionSheetController_43 = new import22.ActionSheetController(this._App_14)); }
    return this.__ActionSheetController_43;
  }
  get _AlertController_44():import23.AlertController {
    if ((this.__AlertController_44 == null)) { (this.__AlertController_44 = new import23.AlertController(this._App_14)); }
    return this.__AlertController_44;
  }
  get _Form_45():import24.Form {
    if ((this.__Form_45 == null)) { (this.__Form_45 = new import24.Form()); }
    return this.__Form_45;
  }
  get _FeatureDetect_46():import25.FeatureDetect {
    if ((this.__FeatureDetect_46 == null)) { (this.__FeatureDetect_46 = new import25.FeatureDetect()); }
    return this.__FeatureDetect_46;
  }
  get _GestureController_47():import26.GestureController {
    if ((this.__GestureController_47 == null)) { (this.__GestureController_47 = new import26.GestureController(this._App_14)); }
    return this.__GestureController_47;
  }
  get _BrowserXhr_48():import27.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import48._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import29.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import29.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import30.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import48.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _Keyboard_54():import31.Keyboard {
    if ((this.__Keyboard_54 == null)) { (this.__Keyboard_54 = new import31.Keyboard(this._Config_13,this._Form_45,this.parent.get(import46.NgZone))); }
    return this.__Keyboard_54;
  }
  get _LoadingController_55():import32.LoadingController {
    if ((this.__LoadingController_55 == null)) { (this.__LoadingController_55 = new import32.LoadingController(this._App_14)); }
    return this.__LoadingController_55;
  }
  get _MenuController_56():import33.MenuController {
    if ((this.__MenuController_56 == null)) { (this.__MenuController_56 = new import33.MenuController()); }
    return this.__MenuController_56;
  }
  get _ModalController_57():import34.ModalController {
    if ((this.__ModalController_57 == null)) { (this.__ModalController_57 = new import34.ModalController(this._App_14)); }
    return this.__ModalController_57;
  }
  get _PickerController_58():import35.PickerController {
    if ((this.__PickerController_58 == null)) { (this.__PickerController_58 = new import35.PickerController(this._App_14)); }
    return this.__PickerController_58;
  }
  get _PopoverController_59():import36.PopoverController {
    if ((this.__PopoverController_59 == null)) { (this.__PopoverController_59 = new import36.PopoverController(this._App_14)); }
    return this.__PopoverController_59;
  }
  get _TapClick_60():import37.TapClick {
    if ((this.__TapClick_60 == null)) { (this.__TapClick_60 = new import37.TapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))); }
    return this.__TapClick_60;
  }
  get _ToastController_61():import38.ToastController {
    if ((this.__ToastController_61 == null)) { (this.__ToastController_61 = new import38.ToastController(this._App_14)); }
    return this.__ToastController_61;
  }
  get _Translate_62():import39.Translate {
    if ((this.__Translate_62 == null)) { (this.__Translate_62 = new import39.Translate()); }
    return this.__Translate_62;
  }
  get _TransitionController_63():import40.TransitionController {
    if ((this.__TransitionController_63 == null)) { (this.__TransitionController_63 = new import40.TransitionController()); }
    return this.__TransitionController_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._ExceptionHandler_6 = import4._exceptionHandler();
    this._UserUrl_7 = import49.getWindowLocation();
    this._QueryParams_8 = import50.setupQueryParams(this._UserUrl_7);
    this._UserAgent_9 = import49.getWindowUserAgent();
    this._UserNavigatorPlatform_10 = import49.getWindowPlatform();
    this._Platform_11 = import51.setupPlatform(this._QueryParams_8,this._UserAgent_9,this._UserNavigatorPlatform_10,this.parent.get(import46.NgZone));
    this._UserConfig_12 = null;
    this._Config_13 = import52.setupConfig(this._UserConfig_12,this._QueryParams_8,this._Platform_11);
    this._App_14 = new import7.App(this._Config_13,this._Platform_11);
    this._APP_INITIALIZER_15 = [
      import53.setupProvideEvents(this._Platform_11),
      import37.setupTapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))
    ]
    ;
    this._ApplicationInitStatus_16 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_15);
    this._Testability_17 = new import9.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__18 = new import10.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import54.Console),this,this._ExceptionHandler_6,this,this._ApplicationInitStatus_16,this.parent.get(import9.TestabilityRegistry,null),this._Testability_17);
    this._ApplicationRef_19 = this._ApplicationRef__18;
    this._IonicModule_20 = new import11.IonicModule(this.parent.get(import11.IonicModule,null),this._ApplicationRef_19);
    this._AppModule_21 = new import1.AppModule();
    return this._AppModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import55.ExceptionHandler)) { return this._ExceptionHandler_6; }
    if ((token === import50.UserUrl)) { return this._UserUrl_7; }
    if ((token === import50.QueryParams)) { return this._QueryParams_8; }
    if ((token === import51.UserAgent)) { return this._UserAgent_9; }
    if ((token === import51.UserNavigatorPlatform)) { return this._UserNavigatorPlatform_10; }
    if ((token === import51.Platform)) { return this._Platform_11; }
    if ((token === import52.UserConfig)) { return this._UserConfig_12; }
    if ((token === import52.Config)) { return this._Config_13; }
    if ((token === import7.App)) { return this._App_14; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import9.Testability)) { return this._Testability_17; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import11.IonicModule)) { return this._IonicModule_20; }
    if ((token === import1.AppModule)) { return this._AppModule_21; }
    if ((token === import12.Compiler)) { return this._Compiler_22; }
    if ((token === import56.ComponentResolver)) { return this._ComponentResolver_23; }
    if ((token === import43.APP_ID)) { return this._APP_ID_24; }
    if ((token === import57.DOCUMENT)) { return this._DOCUMENT_25; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_26; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_27; }
    if ((token === import14.EventManager)) { return this._EventManager_28; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_29; }
    if ((token === import58.AnimationDriver)) { return this._AnimationDriver_30; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_31; }
    if ((token === import59.RootRenderer)) { return this._RootRenderer_32; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_33; }
    if ((token === import60.SanitizationService)) { return this._SanitizationService_34; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import61.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import62.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_38; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_39; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import63.UserRoot)) { return this._UserRoot_42; }
    if ((token === import22.ActionSheetController)) { return this._ActionSheetController_43; }
    if ((token === import23.AlertController)) { return this._AlertController_44; }
    if ((token === import24.Form)) { return this._Form_45; }
    if ((token === import25.FeatureDetect)) { return this._FeatureDetect_46; }
    if ((token === import26.GestureController)) { return this._GestureController_47; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import65.Http)) { return this._Http_53; }
    if ((token === import31.Keyboard)) { return this._Keyboard_54; }
    if ((token === import32.LoadingController)) { return this._LoadingController_55; }
    if ((token === import33.MenuController)) { return this._MenuController_56; }
    if ((token === import34.ModalController)) { return this._ModalController_57; }
    if ((token === import35.PickerController)) { return this._PickerController_58; }
    if ((token === import36.PopoverController)) { return this._PopoverController_59; }
    if ((token === import37.TapClick)) { return this._TapClick_60; }
    if ((token === import38.ToastController)) { return this._ToastController_61; }
    if ((token === import39.Translate)) { return this._Translate_62; }
    if ((token === import40.TransitionController)) { return this._TransitionController_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
var renderType_E2EPage_Host:import66.RenderComponentType = null;
class _View_E2EPage_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EPage_0_4:import1.E2EPage;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage_Host0,renderType_E2EPage_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EPage_0_4 = new import1.E2EPage();
    this._appEl_0.initComponent(this._E2EPage_0_4,[],compView_0);
    compView_0.create(this._E2EPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EPage) && (0 === requestNodeIndex))) { return this._E2EPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EPage_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EPage_Host === null)) { (renderType_E2EPage_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EPageNgFactory:import72.ComponentFactory<import1.E2EPage> = new import72.ComponentFactory<import1.E2EPage>('ng-component',viewFactory_E2EPage_Host0,import1.E2EPage);
const styles_E2EPage:any[] = [];
var renderType_E2EPage:import66.RenderComponentType = null;
class _View_E2EPage0 extends import67.AppView<import1.E2EPage> {
  _el_0:any;
  _Header_0_3:import73.Header;
  _text_1:any;
  _el_2:any;
  private _appEl_2:import68.AppElement;
  _Toolbar_2_4:import73.Toolbar;
  _text_3:any;
  _el_4:any;
  private _appEl_4:import68.AppElement;
  _ToolbarTitle_4_4:import74.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  private _appEl_9:import68.AppElement;
  _Content_9_4:import75.Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import76.List;
  _text_12:any;
  _el_13:any;
  private _appEl_13:import68.AppElement;
  _ListHeader_13_4:import76.ListHeader;
  _Item_13_5:import77.Item;
  _query_Label_13_0:import78.QueryList<any>;
  _query_Button_13_1:import78.QueryList<any>;
  _query_Icon_13_2:import78.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Icon_15_3:import79.Icon;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  private _appEl_18:import68.AppElement;
  _ItemContent_18_4:import77.ItemContent;
  _Item_18_5:import77.Item;
  _query_Label_18_0:import78.QueryList<any>;
  _query_Button_18_1:import78.QueryList<any>;
  _query_Icon_18_2:import78.QueryList<any>;
  _text_19:any;
  _el_20:any;
  _Icon_20_3:import79.Icon;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import80.Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  private _appEl_25:import68.AppElement;
  _Toggle_25_4:import81.Toggle;
  __NG_VALUE_ACCESSOR_25_5:any[];
  _text_26:any;
  _text_27:any;
  _el_28:any;
  private _appEl_28:import68.AppElement;
  _ItemContent_28_4:import77.ItemContent;
  _Item_28_5:import77.Item;
  _query_Label_28_0:import78.QueryList<any>;
  _query_Button_28_1:import78.QueryList<any>;
  _query_Icon_28_2:import78.QueryList<any>;
  _text_29:any;
  _el_30:any;
  _Icon_30_3:import79.Icon;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  private _appEl_36:import68.AppElement;
  _ItemContent_36_4:import77.ItemContent;
  _Item_36_5:import77.Item;
  _query_Label_36_0:import78.QueryList<any>;
  _query_Button_36_1:import78.QueryList<any>;
  _query_Icon_36_2:import78.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Icon_38_3:import79.Icon;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _List_45_3:import76.List;
  _text_46:any;
  _el_47:any;
  private _appEl_47:import68.AppElement;
  _ListHeader_47_4:import76.ListHeader;
  _Item_47_5:import77.Item;
  _query_Label_47_0:import78.QueryList<any>;
  _query_Button_47_1:import78.QueryList<any>;
  _query_Icon_47_2:import78.QueryList<any>;
  _text_48:any;
  _el_49:any;
  private _appEl_49:import68.AppElement;
  _Button_49_4:import82.Button;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  private _appEl_53:import68.AppElement;
  _ItemContent_53_4:import77.ItemContent;
  _Item_53_5:import77.Item;
  _query_Label_53_0:import78.QueryList<any>;
  _query_Button_53_1:import78.QueryList<any>;
  _query_Icon_53_2:import78.QueryList<any>;
  _text_54:any;
  _el_55:any;
  _Icon_55_3:import79.Icon;
  _text_56:any;
  _el_57:any;
  _Label_57_3:import80.Label;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  private _appEl_60:import68.AppElement;
  _Toggle_60_4:import81.Toggle;
  __NG_VALUE_ACCESSOR_60_5:any[];
  _text_61:any;
  _text_62:any;
  _el_63:any;
  private _appEl_63:import68.AppElement;
  _ItemContent_63_4:import77.ItemContent;
  _Item_63_5:import77.Item;
  _query_Label_63_0:import78.QueryList<any>;
  _query_Button_63_1:import78.QueryList<any>;
  _query_Icon_63_2:import78.QueryList<any>;
  _text_64:any;
  _el_65:any;
  _Icon_65_3:import79.Icon;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _List_72_3:import76.List;
  _text_73:any;
  _el_74:any;
  private _appEl_74:import68.AppElement;
  _ListHeader_74_4:import76.ListHeader;
  _Item_74_5:import77.Item;
  _query_Label_74_0:import78.QueryList<any>;
  _query_Button_74_1:import78.QueryList<any>;
  _query_Icon_74_2:import78.QueryList<any>;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  private _appEl_77:import68.AppElement;
  _ItemContent_77_4:import77.ItemContent;
  _Item_77_5:import77.Item;
  _query_Label_77_0:import78.QueryList<any>;
  _query_Button_77_1:import78.QueryList<any>;
  _query_Icon_77_2:import78.QueryList<any>;
  _text_78:any;
  _el_79:any;
  _Icon_79_3:import79.Icon;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  private _appEl_85:import68.AppElement;
  _ItemContent_85_4:import77.ItemContent;
  _Item_85_5:import77.Item;
  _query_Label_85_0:import78.QueryList<any>;
  _query_Button_85_1:import78.QueryList<any>;
  _query_Icon_85_2:import78.QueryList<any>;
  _text_86:any;
  _el_87:any;
  _Icon_87_3:import79.Icon;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _el_93:any;
  private _appEl_93:import68.AppElement;
  _ItemContent_93_4:import77.ItemContent;
  _Item_93_5:import77.Item;
  _query_Label_93_0:import78.QueryList<any>;
  _query_Button_93_1:import78.QueryList<any>;
  _query_Icon_93_2:import78.QueryList<any>;
  _text_94:any;
  _el_95:any;
  _Icon_95_3:import79.Icon;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _List_102_3:import76.List;
  _text_103:any;
  _el_104:any;
  private _appEl_104:import68.AppElement;
  _ItemContent_104_4:import77.ItemContent;
  _Item_104_5:import77.Item;
  _query_Label_104_0:import78.QueryList<any>;
  _query_Button_104_1:import78.QueryList<any>;
  _query_Icon_104_2:import78.QueryList<any>;
  _text_105:any;
  _el_106:any;
  _Icon_106_3:import79.Icon;
  _text_107:any;
  _text_108:any;
  _el_109:any;
  private _appEl_109:import68.AppElement;
  _ItemContent_109_4:import77.ItemContent;
  _Item_109_5:import77.Item;
  _query_Label_109_0:import78.QueryList<any>;
  _query_Button_109_1:import78.QueryList<any>;
  _query_Icon_109_2:import78.QueryList<any>;
  _text_110:any;
  _el_111:any;
  _Icon_111_3:import79.Icon;
  _text_112:any;
  _text_113:any;
  _text_114:any;
  _text_115:any;
  private _expr_0:any;
  private _expr_1:any;
  private _expr_2:any;
  private _expr_3:any;
  private _expr_4:any;
  private _expr_5:any;
  private _expr_6:any;
  private _expr_7:any;
  private _expr_8:any;
  private _expr_9:any;
  private _expr_10:any;
  private _expr_11:any;
  private _expr_12:any;
  private _expr_13:any;
  private _expr_14:any;
  private _expr_15:any;
  private _expr_16:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage0,renderType_E2EPage,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_25_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_25_5 == null)) { (this.__NG_VALUE_ACCESSOR_25_5 = [this._Toggle_25_4]); }
    return this.__NG_VALUE_ACCESSOR_25_5;
  }
  get _NG_VALUE_ACCESSOR_60_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_60_5 == null)) { (this.__NG_VALUE_ACCESSOR_60_5 = [this._Toggle_60_4]); }
    return this.__NG_VALUE_ACCESSOR_60_5;
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',null);
    this._Header_0_3 = new import73.Header(this.parentInjector.get(import83.ViewController,null));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-toolbar',null);
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import68.AppElement(2,0,this,this._el_2);
    var compView_2:any = import84.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import73.Toolbar(this.parentInjector.get(import83.ViewController,null),this._Header_0_3,this.parentInjector.get(import73.Footer,null),this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_2));
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText(null,'\n    ',null);
    this._el_4 = this.renderer.createElement(null,'ion-title',null);
    this._appEl_4 = new import68.AppElement(4,2,this,this._el_4);
    var compView_4:any = import86.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import74.ToolbarTitle(new import85.ElementRef(this._el_4),this._Toolbar_2_4,this.parentInjector.get(import87.Navbar,null));
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText(null,'List Headers',null);
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],null);
    this._text_6 = this.renderer.createText(null,'\n  ',null);
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,null);
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',null);
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',null);
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this.renderer.setElementAttribute(this._el_9,'class','outer-content');
    this._appEl_9 = new import68.AppElement(9,null,this,this._el_9);
    var compView_9:any = import88.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import75.Content(new import85.ElementRef(this._el_9),this.parentInjector.get(import52.Config),this.parentInjector.get(import7.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import83.ViewController,null),this.parentInjector.get(import89.Tabs,null));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText(null,'\n\n  ',null);
    this._el_11 = this.renderer.createElement(null,'ion-list',null);
    this._List_11_3 = new import76.List(new import85.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_13 = this.renderer.createElement(this._el_11,'ion-list-header',null);
    this._appEl_13 = new import68.AppElement(13,11,this,this._el_13);
    var compView_13:any = import90.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ListHeader_13_4 = new import76.ListHeader(this.renderer,new import85.ElementRef(this._el_13),null);
    this._Item_13_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_13));
    this._query_Label_13_0 = new import78.QueryList<any>();
    this._query_Button_13_1 = new import78.QueryList<any>();
    this._query_Icon_13_2 = new import78.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_5,[],compView_13);
    this._text_14 = this.renderer.createText(null,'\n      List Header\n      ',null);
    this._el_15 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_15,'item-right','');
    this.renderer.setElementAttribute(this._el_15,'name','star');
    this.renderer.setElementAttribute(this._el_15,'primary','');
    this.renderer.setElementAttribute(this._el_15,'role','img');
    this._Icon_15_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_13_0.reset([]);
    this._Item_13_5.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_5,[
      [],
      [],
      [].concat([
        this._text_14,
        this._text_16
      ]
      ),
      [],
      [].concat([this._el_15])
    ]
    ,null);
    this._text_17 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_18 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_18,'class','item');
    this._appEl_18 = new import68.AppElement(18,11,this,this._el_18);
    var compView_18:any = import90.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._ItemContent_18_4 = new import77.ItemContent();
    this._Item_18_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_18));
    this._query_Label_18_0 = new import78.QueryList<any>();
    this._query_Button_18_1 = new import78.QueryList<any>();
    this._query_Icon_18_2 = new import78.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_5,[],compView_18);
    this._text_19 = this.renderer.createText(null,'\n      ',null);
    this._el_20 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_20,'item-left','');
    this.renderer.setElementAttribute(this._el_20,'name','wifi');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText(null,'\n      ',null);
    this._el_22 = this.renderer.createElement(null,'ion-label',null);
    this._Label_22_3 = new import80.Label(new import85.ElementRef(this._el_22),this.renderer,null,null,null,null);
    this._text_23 = this.renderer.createText(this._el_22,'Wifi',null);
    this._text_24 = this.renderer.createText(null,'\n      ',null);
    this._el_25 = this.renderer.createElement(null,'ion-toggle',null);
    this._appEl_25 = new import68.AppElement(25,18,this,this._el_25);
    var compView_25:any = import91.viewFactory_Toggle0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Toggle_25_4 = new import81.Toggle(this.parentInjector.get(import24.Form),new import85.ElementRef(this._el_25),this.renderer,this._Item_18_5);
    this._appEl_25.initComponent(this._Toggle_25_4,[],compView_25);
    compView_25.create(this._Toggle_25_4,[],null);
    this._text_26 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_18_0.reset([this._Label_22_3]);
    this._Item_18_5.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_5,[
      [].concat([this._el_20]),
      [].concat([this._el_22]),
      [].concat([
        this._text_19,
        this._text_21,
        this._text_24,
        this._text_26
      ]
      ),
      [],
      [].concat([this._el_25])
    ]
    ,null);
    this._text_27 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_28 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_28,'class','item');
    this._appEl_28 = new import68.AppElement(28,11,this,this._el_28);
    var compView_28:any = import90.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._ItemContent_28_4 = new import77.ItemContent();
    this._Item_28_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_28));
    this._query_Label_28_0 = new import78.QueryList<any>();
    this._query_Button_28_1 = new import78.QueryList<any>();
    this._query_Icon_28_2 = new import78.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_5,[],compView_28);
    this._text_29 = this.renderer.createText(null,'\n      ',null);
    this._el_30 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_30,'item-left','');
    this.renderer.setElementAttribute(this._el_30,'name','heart');
    this.renderer.setElementAttribute(this._el_30,'role','img');
    this._Icon_30_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(null,'\n      Affection\n      ',null);
    this._el_32 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_32,'item-right','');
    this._text_33 = this.renderer.createText(this._el_32,'\n        Very Little\n      ',null);
    this._text_34 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_28_0.reset([]);
    this._Item_28_5.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_5,[
      [].concat([this._el_30]),
      [],
      [].concat([
        this._text_29,
        this._text_31,
        this._text_34
      ]
      ),
      [],
      [].concat([this._el_32])
    ]
    ,null);
    this._text_35 = this.renderer.createText(this._el_11,'\n\n    ',null);
    this._el_36 = this.renderer.createElement(this._el_11,'ion-item',null);
    this.renderer.setElementAttribute(this._el_36,'class','item');
    this._appEl_36 = new import68.AppElement(36,11,this,this._el_36);
    var compView_36:any = import90.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._ItemContent_36_4 = new import77.ItemContent();
    this._Item_36_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_36));
    this._query_Label_36_0 = new import78.QueryList<any>();
    this._query_Button_36_1 = new import78.QueryList<any>();
    this._query_Icon_36_2 = new import78.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_5,[],compView_36);
    this._text_37 = this.renderer.createText(null,'\n      ',null);
    this._el_38 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_38,'item-left','');
    this.renderer.setElementAttribute(this._el_38,'name','home');
    this.renderer.setElementAttribute(this._el_38,'role','img');
    this._Icon_38_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText(null,'\n      Home\n      ',null);
    this._el_40 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_40,'item-right','');
    this._text_41 = this.renderer.createText(this._el_40,'\n        Where the heart is\n      ',null);
    this._text_42 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_36_0.reset([]);
    this._Item_36_5.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_5,[
      [].concat([this._el_38]),
      [],
      [].concat([
        this._text_37,
        this._text_39,
        this._text_42
      ]
      ),
      [],
      [].concat([this._el_40])
    ]
    ,null);
    this._text_43 = this.renderer.createText(this._el_11,'\n\n  ',null);
    this._text_44 = this.renderer.createText(null,'\n\n\n  ',null);
    this._el_45 = this.renderer.createElement(null,'ion-list',null);
    this._List_45_3 = new import76.List(new import85.ElementRef(this._el_45),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_46 = this.renderer.createText(this._el_45,'\n\n    ',null);
    this._el_47 = this.renderer.createElement(this._el_45,'ion-list-header',null);
    this._appEl_47 = new import68.AppElement(47,45,this,this._el_47);
    var compView_47:any = import90.viewFactory_Item0(this.viewUtils,this.injector(47),this._appEl_47);
    this._ListHeader_47_4 = new import76.ListHeader(this.renderer,new import85.ElementRef(this._el_47),null);
    this._Item_47_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_47));
    this._query_Label_47_0 = new import78.QueryList<any>();
    this._query_Button_47_1 = new import78.QueryList<any>();
    this._query_Icon_47_2 = new import78.QueryList<any>();
    this._appEl_47.initComponent(this._Item_47_5,[],compView_47);
    this._text_48 = this.renderer.createText(null,'\n      List Header\n      ',null);
    this._el_49 = this.renderer.createElement(null,'button',null);
    this.renderer.setElementAttribute(this._el_49,'item-right','');
    this.renderer.setElementAttribute(this._el_49,'outline','');
    this._appEl_49 = new import68.AppElement(49,47,this,this._el_49);
    var compView_49:any = import92.viewFactory_Button0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Button_49_4 = new import82.Button(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_49),this.renderer,null);
    this._appEl_49.initComponent(this._Button_49_4,[],compView_49);
    this._text_50 = this.renderer.createText(null,'Info',null);
    compView_49.create(this._Button_49_4,[[].concat([this._text_50])],null);
    this._text_51 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_47_0.reset([]);
    this._Item_47_5.contentLabel = this._query_Label_47_0.first;
    compView_47.create(this._Item_47_5,[
      [],
      [],
      [].concat([
        this._text_48,
        this._text_51
      ]
      ),
      [],
      [].concat([this._el_49])
    ]
    ,null);
    this._text_52 = this.renderer.createText(this._el_45,'\n\n    ',null);
    this._el_53 = this.renderer.createElement(this._el_45,'ion-item',null);
    this.renderer.setElementAttribute(this._el_53,'class','item');
    this._appEl_53 = new import68.AppElement(53,45,this,this._el_53);
    var compView_53:any = import90.viewFactory_Item0(this.viewUtils,this.injector(53),this._appEl_53);
    this._ItemContent_53_4 = new import77.ItemContent();
    this._Item_53_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_53));
    this._query_Label_53_0 = new import78.QueryList<any>();
    this._query_Button_53_1 = new import78.QueryList<any>();
    this._query_Icon_53_2 = new import78.QueryList<any>();
    this._appEl_53.initComponent(this._Item_53_5,[],compView_53);
    this._text_54 = this.renderer.createText(null,'\n      ',null);
    this._el_55 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_55,'item-left','');
    this.renderer.setElementAttribute(this._el_55,'name','color-wand');
    this.renderer.setElementAttribute(this._el_55,'role','img');
    this._Icon_55_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_55),this.renderer);
    this._text_56 = this.renderer.createText(null,'\n      ',null);
    this._el_57 = this.renderer.createElement(null,'ion-label',null);
    this._Label_57_3 = new import80.Label(new import85.ElementRef(this._el_57),this.renderer,null,null,null,null);
    this._text_58 = this.renderer.createText(this._el_57,'Magic',null);
    this._text_59 = this.renderer.createText(null,'\n      ',null);
    this._el_60 = this.renderer.createElement(null,'ion-toggle',null);
    this.renderer.setElementAttribute(this._el_60,'checked','true');
    this._appEl_60 = new import68.AppElement(60,53,this,this._el_60);
    var compView_60:any = import91.viewFactory_Toggle0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Toggle_60_4 = new import81.Toggle(this.parentInjector.get(import24.Form),new import85.ElementRef(this._el_60),this.renderer,this._Item_53_5);
    this._appEl_60.initComponent(this._Toggle_60_4,[],compView_60);
    compView_60.create(this._Toggle_60_4,[],null);
    this._text_61 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_53_0.reset([this._Label_57_3]);
    this._Item_53_5.contentLabel = this._query_Label_53_0.first;
    compView_53.create(this._Item_53_5,[
      [].concat([this._el_55]),
      [].concat([this._el_57]),
      [].concat([
        this._text_54,
        this._text_56,
        this._text_59,
        this._text_61
      ]
      ),
      [],
      [].concat([this._el_60])
    ]
    ,null);
    this._text_62 = this.renderer.createText(this._el_45,'\n\n    ',null);
    this._el_63 = this.renderer.createElement(this._el_45,'ion-item',null);
    this.renderer.setElementAttribute(this._el_63,'class','item');
    this._appEl_63 = new import68.AppElement(63,45,this,this._el_63);
    var compView_63:any = import90.viewFactory_Item0(this.viewUtils,this.injector(63),this._appEl_63);
    this._ItemContent_63_4 = new import77.ItemContent();
    this._Item_63_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_63));
    this._query_Label_63_0 = new import78.QueryList<any>();
    this._query_Button_63_1 = new import78.QueryList<any>();
    this._query_Icon_63_2 = new import78.QueryList<any>();
    this._appEl_63.initComponent(this._Item_63_5,[],compView_63);
    this._text_64 = this.renderer.createText(null,'\n      ',null);
    this._el_65 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_65,'item-left','');
    this.renderer.setElementAttribute(this._el_65,'name','star');
    this.renderer.setElementAttribute(this._el_65,'role','img');
    this._Icon_65_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_65),this.renderer);
    this._text_66 = this.renderer.createText(null,'\n      Star status\n      ',null);
    this._el_67 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_67,'item-right','');
    this._text_68 = this.renderer.createText(this._el_67,'\n        Super\n      ',null);
    this._text_69 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_63_0.reset([]);
    this._Item_63_5.contentLabel = this._query_Label_63_0.first;
    compView_63.create(this._Item_63_5,[
      [].concat([this._el_65]),
      [],
      [].concat([
        this._text_64,
        this._text_66,
        this._text_69
      ]
      ),
      [],
      [].concat([this._el_67])
    ]
    ,null);
    this._text_70 = this.renderer.createText(this._el_45,'\n\n  ',null);
    this._text_71 = this.renderer.createText(null,'\n\n\n  ',null);
    this._el_72 = this.renderer.createElement(null,'ion-list',null);
    this._List_72_3 = new import76.List(new import85.ElementRef(this._el_72),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_73 = this.renderer.createText(this._el_72,'\n\n    ',null);
    this._el_74 = this.renderer.createElement(this._el_72,'ion-list-header',null);
    this._appEl_74 = new import68.AppElement(74,72,this,this._el_74);
    var compView_74:any = import90.viewFactory_Item0(this.viewUtils,this.injector(74),this._appEl_74);
    this._ListHeader_74_4 = new import76.ListHeader(this.renderer,new import85.ElementRef(this._el_74),null);
    this._Item_74_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_74));
    this._query_Label_74_0 = new import78.QueryList<any>();
    this._query_Button_74_1 = new import78.QueryList<any>();
    this._query_Icon_74_2 = new import78.QueryList<any>();
    this._appEl_74.initComponent(this._Item_74_5,[],compView_74);
    this._text_75 = this.renderer.createText(null,'\n      List Header with text that is too long to fit inside the list header\n    ',null);
    this._query_Label_74_0.reset([]);
    this._Item_74_5.contentLabel = this._query_Label_74_0.first;
    compView_74.create(this._Item_74_5,[
      [],
      [],
      [].concat([this._text_75]),
      [],
      []
    ]
    ,null);
    this._text_76 = this.renderer.createText(this._el_72,'\n\n    ',null);
    this._el_77 = this.renderer.createElement(this._el_72,'ion-item',null);
    this.renderer.setElementAttribute(this._el_77,'class','item');
    this._appEl_77 = new import68.AppElement(77,72,this,this._el_77);
    var compView_77:any = import90.viewFactory_Item0(this.viewUtils,this.injector(77),this._appEl_77);
    this._ItemContent_77_4 = new import77.ItemContent();
    this._Item_77_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_77));
    this._query_Label_77_0 = new import78.QueryList<any>();
    this._query_Button_77_1 = new import78.QueryList<any>();
    this._query_Icon_77_2 = new import78.QueryList<any>();
    this._appEl_77.initComponent(this._Item_77_5,[],compView_77);
    this._text_78 = this.renderer.createText(null,'\n      ',null);
    this._el_79 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_79,'item-left','');
    this.renderer.setElementAttribute(this._el_79,'name','pizza');
    this.renderer.setElementAttribute(this._el_79,'role','img');
    this._Icon_79_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(null,'\n      Pizza\n      ',null);
    this._el_81 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_81,'item-right','');
    this._text_82 = this.renderer.createText(this._el_81,'\n        Always\n      ',null);
    this._text_83 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_77_0.reset([]);
    this._Item_77_5.contentLabel = this._query_Label_77_0.first;
    compView_77.create(this._Item_77_5,[
      [].concat([this._el_79]),
      [],
      [].concat([
        this._text_78,
        this._text_80,
        this._text_83
      ]
      ),
      [],
      [].concat([this._el_81])
    ]
    ,null);
    this._text_84 = this.renderer.createText(this._el_72,'\n\n    ',null);
    this._el_85 = this.renderer.createElement(this._el_72,'ion-item',null);
    this.renderer.setElementAttribute(this._el_85,'class','item');
    this._appEl_85 = new import68.AppElement(85,72,this,this._el_85);
    var compView_85:any = import90.viewFactory_Item0(this.viewUtils,this.injector(85),this._appEl_85);
    this._ItemContent_85_4 = new import77.ItemContent();
    this._Item_85_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_85));
    this._query_Label_85_0 = new import78.QueryList<any>();
    this._query_Button_85_1 = new import78.QueryList<any>();
    this._query_Icon_85_2 = new import78.QueryList<any>();
    this._appEl_85.initComponent(this._Item_85_5,[],compView_85);
    this._text_86 = this.renderer.createText(null,'\n      ',null);
    this._el_87 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_87,'item-left','');
    this.renderer.setElementAttribute(this._el_87,'name','beer');
    this.renderer.setElementAttribute(this._el_87,'role','img');
    this._Icon_87_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_87),this.renderer);
    this._text_88 = this.renderer.createText(null,'\n      Beer\n      ',null);
    this._el_89 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_89,'item-right','');
    this._text_90 = this.renderer.createText(this._el_89,'\n        Yes Plz\n      ',null);
    this._text_91 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_85_0.reset([]);
    this._Item_85_5.contentLabel = this._query_Label_85_0.first;
    compView_85.create(this._Item_85_5,[
      [].concat([this._el_87]),
      [],
      [].concat([
        this._text_86,
        this._text_88,
        this._text_91
      ]
      ),
      [],
      [].concat([this._el_89])
    ]
    ,null);
    this._text_92 = this.renderer.createText(this._el_72,'\n\n    ',null);
    this._el_93 = this.renderer.createElement(this._el_72,'ion-item',null);
    this.renderer.setElementAttribute(this._el_93,'class','item');
    this._appEl_93 = new import68.AppElement(93,72,this,this._el_93);
    var compView_93:any = import90.viewFactory_Item0(this.viewUtils,this.injector(93),this._appEl_93);
    this._ItemContent_93_4 = new import77.ItemContent();
    this._Item_93_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_93));
    this._query_Label_93_0 = new import78.QueryList<any>();
    this._query_Button_93_1 = new import78.QueryList<any>();
    this._query_Icon_93_2 = new import78.QueryList<any>();
    this._appEl_93.initComponent(this._Item_93_5,[],compView_93);
    this._text_94 = this.renderer.createText(null,'\n      ',null);
    this._el_95 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_95,'item-left','');
    this.renderer.setElementAttribute(this._el_95,'name','wine');
    this.renderer.setElementAttribute(this._el_95,'role','img');
    this._Icon_95_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_95),this.renderer);
    this._text_96 = this.renderer.createText(null,'\n      Wine\n      ',null);
    this._el_97 = this.renderer.createElement(null,'ion-note',null);
    this.renderer.setElementAttribute(this._el_97,'item-right','');
    this._text_98 = this.renderer.createText(this._el_97,'\n        All the time\n      ',null);
    this._text_99 = this.renderer.createText(null,'\n    ',null);
    this._query_Label_93_0.reset([]);
    this._Item_93_5.contentLabel = this._query_Label_93_0.first;
    compView_93.create(this._Item_93_5,[
      [].concat([this._el_95]),
      [],
      [].concat([
        this._text_94,
        this._text_96,
        this._text_99
      ]
      ),
      [],
      [].concat([this._el_97])
    ]
    ,null);
    this._text_100 = this.renderer.createText(this._el_72,'\n\n  ',null);
    this._text_101 = this.renderer.createText(null,'\n\n\n  ',null);
    this._el_102 = this.renderer.createElement(null,'ion-list',null);
    this._List_102_3 = new import76.List(new import85.ElementRef(this._el_102),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_103 = this.renderer.createText(this._el_102,'\n\n    ',null);
    this._el_104 = this.renderer.createElement(this._el_102,'ion-item',null);
    this.renderer.setElementAttribute(this._el_104,'class','item');
    this._appEl_104 = new import68.AppElement(104,102,this,this._el_104);
    var compView_104:any = import90.viewFactory_Item0(this.viewUtils,this.injector(104),this._appEl_104);
    this._ItemContent_104_4 = new import77.ItemContent();
    this._Item_104_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_104));
    this._query_Label_104_0 = new import78.QueryList<any>();
    this._query_Button_104_1 = new import78.QueryList<any>();
    this._query_Icon_104_2 = new import78.QueryList<any>();
    this._appEl_104.initComponent(this._Item_104_5,[],compView_104);
    this._text_105 = this.renderer.createText(null,'\n      ',null);
    this._el_106 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_106,'item-left','');
    this.renderer.setElementAttribute(this._el_106,'name','chatboxes');
    this.renderer.setElementAttribute(this._el_106,'role','img');
    this._Icon_106_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_106),this.renderer);
    this._text_107 = this.renderer.createText(null,'\n      New List, no header, Item 1\n    ',null);
    this._query_Label_104_0.reset([]);
    this._Item_104_5.contentLabel = this._query_Label_104_0.first;
    compView_104.create(this._Item_104_5,[
      [].concat([this._el_106]),
      [],
      [].concat([
        this._text_105,
        this._text_107
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_108 = this.renderer.createText(this._el_102,'\n\n    ',null);
    this._el_109 = this.renderer.createElement(this._el_102,'ion-item',null);
    this.renderer.setElementAttribute(this._el_109,'class','item');
    this._appEl_109 = new import68.AppElement(109,102,this,this._el_109);
    var compView_109:any = import90.viewFactory_Item0(this.viewUtils,this.injector(109),this._appEl_109);
    this._ItemContent_109_4 = new import77.ItemContent();
    this._Item_109_5 = new import77.Item(this.parentInjector.get(import24.Form),this.renderer,new import85.ElementRef(this._el_109));
    this._query_Label_109_0 = new import78.QueryList<any>();
    this._query_Button_109_1 = new import78.QueryList<any>();
    this._query_Icon_109_2 = new import78.QueryList<any>();
    this._appEl_109.initComponent(this._Item_109_5,[],compView_109);
    this._text_110 = this.renderer.createText(null,'\n      ',null);
    this._el_111 = this.renderer.createElement(null,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_111,'item-left','');
    this.renderer.setElementAttribute(this._el_111,'name','chatboxes');
    this.renderer.setElementAttribute(this._el_111,'role','img');
    this._Icon_111_3 = new import79.Icon(this.parentInjector.get(import52.Config),new import85.ElementRef(this._el_111),this.renderer);
    this._text_112 = this.renderer.createText(null,'\n      New List, no header, Item 2\n    ',null);
    this._query_Label_109_0.reset([]);
    this._Item_109_5.contentLabel = this._query_Label_109_0.first;
    compView_109.create(this._Item_109_5,[
      [].concat([this._el_111]),
      [],
      [].concat([
        this._text_110,
        this._text_112
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_113 = this.renderer.createText(this._el_102,'\n\n  ',null);
    this._text_114 = this.renderer.createText(null,'\n\n',null);
    compView_9.create(this._Content_9_4,[
      [].concat([
        this._text_10,
        this._el_11,
        this._text_44,
        this._el_45,
        this._text_71,
        this._el_72,
        this._text_101,
        this._el_102,
        this._text_114
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_115 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import71.UNINITIALIZED;
    this._expr_1 = import71.UNINITIALIZED;
    this._expr_2 = import71.UNINITIALIZED;
    this._expr_3 = import71.UNINITIALIZED;
    this._expr_4 = import71.UNINITIALIZED;
    this._expr_5 = import71.UNINITIALIZED;
    this._expr_6 = import71.UNINITIALIZED;
    this._expr_7 = import71.UNINITIALIZED;
    this._expr_8 = import71.UNINITIALIZED;
    this._expr_9 = import71.UNINITIALIZED;
    this._expr_10 = import71.UNINITIALIZED;
    this._expr_11 = import71.UNINITIALIZED;
    this._expr_12 = import71.UNINITIALIZED;
    this._expr_13 = import71.UNINITIALIZED;
    this._expr_14 = import71.UNINITIALIZED;
    this._expr_15 = import71.UNINITIALIZED;
    this._expr_16 = import71.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._text_114,
      this._text_115
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import74.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import73.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Toolbar_2_4; }
    if (((token === import73.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import79.Icon) && (15 === requestNodeIndex))) { return this._Icon_15_3; }
    if (((token === import76.ListHeader) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ListHeader_13_4; }
    if (((token === import77.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_13_5; }
    if (((token === import79.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import80.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3; }
    if (((token === import81.Toggle) && (25 === requestNodeIndex))) { return this._Toggle_25_4; }
    if (((token === import93.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_5; }
    if (((token === import77.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_18_4; }
    if (((token === import77.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_18_5; }
    if (((token === import79.Icon) && (30 === requestNodeIndex))) { return this._Icon_30_3; }
    if (((token === import77.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_28_4; }
    if (((token === import77.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_28_5; }
    if (((token === import79.Icon) && (38 === requestNodeIndex))) { return this._Icon_38_3; }
    if (((token === import77.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemContent_36_4; }
    if (((token === import77.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_36_5; }
    if (((token === import76.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._List_11_3; }
    if (((token === import82.Button) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Button_49_4; }
    if (((token === import76.ListHeader) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ListHeader_47_4; }
    if (((token === import77.Item) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Item_47_5; }
    if (((token === import79.Icon) && (55 === requestNodeIndex))) { return this._Icon_55_3; }
    if (((token === import80.Label) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Label_57_3; }
    if (((token === import81.Toggle) && (60 === requestNodeIndex))) { return this._Toggle_60_4; }
    if (((token === import93.NG_VALUE_ACCESSOR) && (60 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_60_5; }
    if (((token === import77.ItemContent) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._ItemContent_53_4; }
    if (((token === import77.Item) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Item_53_5; }
    if (((token === import79.Icon) && (65 === requestNodeIndex))) { return this._Icon_65_3; }
    if (((token === import77.ItemContent) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._ItemContent_63_4; }
    if (((token === import77.Item) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Item_63_5; }
    if (((token === import76.List) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._List_45_3; }
    if (((token === import76.ListHeader) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ListHeader_74_4; }
    if (((token === import77.Item) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Item_74_5; }
    if (((token === import79.Icon) && (79 === requestNodeIndex))) { return this._Icon_79_3; }
    if (((token === import77.ItemContent) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._ItemContent_77_4; }
    if (((token === import77.Item) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 83)))) { return this._Item_77_5; }
    if (((token === import79.Icon) && (87 === requestNodeIndex))) { return this._Icon_87_3; }
    if (((token === import77.ItemContent) && ((85 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._ItemContent_85_4; }
    if (((token === import77.Item) && ((85 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._Item_85_5; }
    if (((token === import79.Icon) && (95 === requestNodeIndex))) { return this._Icon_95_3; }
    if (((token === import77.ItemContent) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._ItemContent_93_4; }
    if (((token === import77.Item) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._Item_93_5; }
    if (((token === import76.List) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._List_72_3; }
    if (((token === import79.Icon) && (106 === requestNodeIndex))) { return this._Icon_106_3; }
    if (((token === import77.ItemContent) && ((104 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._ItemContent_104_4; }
    if (((token === import77.Item) && ((104 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._Item_104_5; }
    if (((token === import79.Icon) && (111 === requestNodeIndex))) { return this._Icon_111_3; }
    if (((token === import77.ItemContent) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 112)))) { return this._ItemContent_109_4; }
    if (((token === import77.Item) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 112)))) { return this._Item_109_5; }
    if (((token === import76.List) && ((102 <= requestNodeIndex) && (requestNodeIndex <= 113)))) { return this._List_102_3; }
    if (((token === import75.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 114)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_2:any = 'star';
    if (import69.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_15_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'wifi';
    if (import69.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_20_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'heart';
    if (import69.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_30_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'home';
    if (import69.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_38_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    changed = false;
    const currVal_7:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Button_49_4.outline = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    if (changed) { this._appEl_49.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_49_4.ngOnInit(); }
    const currVal_8:any = 'color-wand';
    if (import69.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Icon_55_3.name = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'true';
    if (import69.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Toggle_60_4.checked = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = 'star';
    if (import69.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Icon_65_3.name = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'pizza';
    if (import69.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_79_3.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 'beer';
    if (import69.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_87_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'wine';
    if (import69.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_95_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'chatboxes';
    if (import69.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Icon_106_3.name = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'chatboxes';
    if (import69.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_111_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset([]);
        this._Item_13_5._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset([this._Icon_15_3]);
        this._Item_13_5._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset([]);
        this._Item_18_5._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset([this._Icon_20_3]);
        this._Item_18_5._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset([]);
        this._Item_28_5._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset([this._Icon_30_3]);
        this._Item_28_5._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset([]);
        this._Item_36_5._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset([this._Icon_38_3]);
        this._Item_36_5._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      if (this._query_Button_47_1.dirty) {
        this._query_Button_47_1.reset([this._Button_49_4]);
        this._Item_47_5._buttons = this._query_Button_47_1;
        this._query_Button_47_1.notifyOnChanges();
      }
      if (this._query_Icon_47_2.dirty) {
        this._query_Icon_47_2.reset([]);
        this._Item_47_5._icons = this._query_Icon_47_2;
        this._query_Icon_47_2.notifyOnChanges();
      }
      if (this._query_Button_53_1.dirty) {
        this._query_Button_53_1.reset([]);
        this._Item_53_5._buttons = this._query_Button_53_1;
        this._query_Button_53_1.notifyOnChanges();
      }
      if (this._query_Icon_53_2.dirty) {
        this._query_Icon_53_2.reset([this._Icon_55_3]);
        this._Item_53_5._icons = this._query_Icon_53_2;
        this._query_Icon_53_2.notifyOnChanges();
      }
      if (this._query_Button_63_1.dirty) {
        this._query_Button_63_1.reset([]);
        this._Item_63_5._buttons = this._query_Button_63_1;
        this._query_Button_63_1.notifyOnChanges();
      }
      if (this._query_Icon_63_2.dirty) {
        this._query_Icon_63_2.reset([this._Icon_65_3]);
        this._Item_63_5._icons = this._query_Icon_63_2;
        this._query_Icon_63_2.notifyOnChanges();
      }
      if (this._query_Button_74_1.dirty) {
        this._query_Button_74_1.reset([]);
        this._Item_74_5._buttons = this._query_Button_74_1;
        this._query_Button_74_1.notifyOnChanges();
      }
      if (this._query_Icon_74_2.dirty) {
        this._query_Icon_74_2.reset([]);
        this._Item_74_5._icons = this._query_Icon_74_2;
        this._query_Icon_74_2.notifyOnChanges();
      }
      if (this._query_Button_77_1.dirty) {
        this._query_Button_77_1.reset([]);
        this._Item_77_5._buttons = this._query_Button_77_1;
        this._query_Button_77_1.notifyOnChanges();
      }
      if (this._query_Icon_77_2.dirty) {
        this._query_Icon_77_2.reset([this._Icon_79_3]);
        this._Item_77_5._icons = this._query_Icon_77_2;
        this._query_Icon_77_2.notifyOnChanges();
      }
      if (this._query_Button_85_1.dirty) {
        this._query_Button_85_1.reset([]);
        this._Item_85_5._buttons = this._query_Button_85_1;
        this._query_Button_85_1.notifyOnChanges();
      }
      if (this._query_Icon_85_2.dirty) {
        this._query_Icon_85_2.reset([this._Icon_87_3]);
        this._Item_85_5._icons = this._query_Icon_85_2;
        this._query_Icon_85_2.notifyOnChanges();
      }
      if (this._query_Button_93_1.dirty) {
        this._query_Button_93_1.reset([]);
        this._Item_93_5._buttons = this._query_Button_93_1;
        this._query_Button_93_1.notifyOnChanges();
      }
      if (this._query_Icon_93_2.dirty) {
        this._query_Icon_93_2.reset([this._Icon_95_3]);
        this._Item_93_5._icons = this._query_Icon_93_2;
        this._query_Icon_93_2.notifyOnChanges();
      }
      if (this._query_Button_104_1.dirty) {
        this._query_Button_104_1.reset([]);
        this._Item_104_5._buttons = this._query_Button_104_1;
        this._query_Button_104_1.notifyOnChanges();
      }
      if (this._query_Icon_104_2.dirty) {
        this._query_Icon_104_2.reset([this._Icon_106_3]);
        this._Item_104_5._icons = this._query_Icon_104_2;
        this._query_Icon_104_2.notifyOnChanges();
      }
      if (this._query_Button_109_1.dirty) {
        this._query_Button_109_1.reset([]);
        this._Item_109_5._buttons = this._query_Button_109_1;
        this._query_Button_109_1.notifyOnChanges();
      }
      if (this._query_Icon_109_2.dirty) {
        this._query_Icon_109_2.reset([this._Icon_111_3]);
        this._Item_109_5._icons = this._query_Icon_109_2;
        this._query_Icon_109_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_13_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_25_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_36_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_49_4.ngAfterContentInit(); }
      this._Button_49_4.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_47_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_60_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_53_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_63_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_74_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_77_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_85_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_93_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_104_5.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_109_5.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Toolbar_2_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Content_9_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._Toggle_25_4._disabled;
    if (import69.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_25,'toggle-disabled',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_10:any = this._Toggle_60_4._disabled;
    if (import69.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_60,'toggle-disabled',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_15_3.ngOnDestroy();
    this._Icon_20_3.ngOnDestroy();
    this._Toggle_25_4.ngOnDestroy();
    this._Icon_30_3.ngOnDestroy();
    this._Icon_38_3.ngOnDestroy();
    this._List_11_3.ngOnDestroy();
    this._Icon_55_3.ngOnDestroy();
    this._Toggle_60_4.ngOnDestroy();
    this._Icon_65_3.ngOnDestroy();
    this._List_45_3.ngOnDestroy();
    this._Icon_79_3.ngOnDestroy();
    this._Icon_87_3.ngOnDestroy();
    this._Icon_95_3.ngOnDestroy();
    this._List_72_3.ngOnDestroy();
    this._Icon_106_3.ngOnDestroy();
    this._Icon_111_3.ngOnDestroy();
    this._List_102_3.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_E2EPage0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EPage> {
  if ((renderType_E2EPage === null)) { (renderType_E2EPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/list/headers/main.html',0,import94.ViewEncapsulation.None,styles_E2EPage,{})); }
  return new _View_E2EPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_E2EApp_Host:import66.RenderComponentType = null;
class _View_E2EApp_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EApp_0_4:import1.E2EApp;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp_Host0,renderType_E2EApp_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EApp_0_4 = new import1.E2EApp();
    this._appEl_0.initComponent(this._E2EApp_0_4,[],compView_0);
    compView_0.create(this._E2EApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EApp) && (0 === requestNodeIndex))) { return this._E2EApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EApp_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EApp_Host === null)) { (renderType_E2EApp_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EAppNgFactory:import72.ComponentFactory<import1.E2EApp> = new import72.ComponentFactory<import1.E2EApp>('ng-component',viewFactory_E2EApp_Host0,import1.E2EApp);
const styles_E2EApp:any[] = [];
var renderType_E2EApp:import66.RenderComponentType = null;
class _View_E2EApp0 extends import67.AppView<import1.E2EApp> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _Nav_0_4:import95.Nav;
  private _expr_0:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp0,renderType_E2EApp,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = import96.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import95.Nav(this.parentInjector.get(import83.ViewController,null),this.parentInjector.get(import97.NavControllerBase,null),this.parentInjector.get(import7.App),this.parentInjector.get(import52.Config),this.parentInjector.get(import31.Keyboard),new import85.ElementRef(this._el_0),this.parentInjector.get(import46.NgZone),this.renderer,this.parentInjector.get(import98.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import71.UNINITIALIZED;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import95.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_E2EApp0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EApp> {
  if ((renderType_E2EApp === null)) { (renderType_E2EApp = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/list/headers/AppModule.ts class E2EApp - inline template',0,import94.ViewEncapsulation.None,styles_E2EApp,{})); }
  return new _View_E2EApp0(viewUtils,parentInjector,declarationEl);
}