/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import41 from '@angular/core/src/di/injector';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import72 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const TabsPageNgFactory: import72.ComponentFactory<import1.TabsPage>;
export declare function viewFactory_TabsPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.TabsPage>;
export declare const Page4NgFactory: import72.ComponentFactory<import1.Page4>;
export declare function viewFactory_Page40(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Page4>;
export declare const Page3NgFactory: import72.ComponentFactory<import1.Page3>;
export declare function viewFactory_Page30(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Page3>;
export declare const Page2NgFactory: import72.ComponentFactory<import1.Page2>;
export declare function viewFactory_Page20(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Page2>;
export declare const Page1NgFactory: import72.ComponentFactory<import1.Page1>;
export declare function viewFactory_Page10(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.Page1>;
export declare const E2EPageNgFactory: import72.ComponentFactory<import1.E2EPage>;
export declare function viewFactory_E2EPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EPage>;
export declare const E2EAppNgFactory: import72.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EApp>;
