/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../../dist/components/app/app';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '../../../dist/ionic-module';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '../../../dist/components/action-sheet/action-sheet';
import * as import23 from '../../../dist/components/alert/alert';
import * as import24 from '../../../dist/util/form';
import * as import25 from '../../../dist/util/feature-detect';
import * as import26 from '../../../dist/gestures/gesture-controller';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '../../../dist/util/keyboard';
import * as import32 from '../../../dist/components/loading/loading';
import * as import33 from '../../../dist/components/menu/menu-controller';
import * as import34 from '../../../dist/components/modal/modal';
import * as import35 from '../../../dist/components/picker/picker';
import * as import36 from '../../../dist/components/popover/popover';
import * as import37 from '../../../dist/components/tap-click/tap-click';
import * as import38 from '../../../dist/components/toast/toast';
import * as import39 from '../../../dist/translation/translate';
import * as import40 from '../../../dist/transitions/transition-controller';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../../../dist/components/app/app-root.d.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/http/http';
import * as import49 from '../../../dist/providers';
import * as import50 from '../../../dist/platform/query-params';
import * as import51 from '../../../dist/platform/platform';
import * as import52 from '../../../dist/config/config';
import * as import53 from '../../../dist/util/events';
import * as import54 from '@angular/core/src/console';
import * as import55 from '@angular/core/src/facade/exception_handler';
import * as import56 from '@angular/core/src/linker/component_resolver';
import * as import57 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import58 from '@angular/platform-browser/src/dom/animation_driver';
import * as import59 from '@angular/core/src/render/api';
import * as import60 from '@angular/core/src/security';
import * as import61 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import62 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import63 from '../../../dist/components/app/app-root';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/core/src/render/api';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import70 from '@angular/core/src/linker/view_type';
import * as import71 from '@angular/core/src/change_detection/change_detection';
import * as import72 from '@angular/core/src/linker/component_factory';
import * as import73 from '../../../dist/components/content/content';
import * as import74 from '@angular/forms/src/directives/ng_model';
import * as import75 from '@angular/forms/src/directives/ng_control_status';
import * as import76 from '../../../dist/components/searchbar/searchbar';
import * as import77 from '../../../dist/components/button/button';
import * as import78 from '../../../dist/components/content/content.d.ngfactory';
import * as import79 from '@angular/core/src/linker/element_ref';
import * as import80 from '../../../dist/components/nav/view-controller';
import * as import81 from '../../../dist/components/tabs/tabs';
import * as import82 from '../../../dist/components/searchbar/searchbar.d.ngfactory';
import * as import83 from '@angular/forms/src/directives/ng_control';
import * as import84 from '../../../dist/components/button/button.d.ngfactory';
import * as import85 from '@angular/core/src/metadata/view';
import * as import86 from '../../../dist/components/nav/nav';
import * as import87 from '../../../dist/components/nav/nav.d.ngfactory';
import * as import88 from '../../../dist/components/nav/nav-controller-base';
import * as import89 from '@angular/core/src/linker/component_factory_resolver';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _ExceptionHandler_6:any;
  _UserUrl_7:any;
  _QueryParams_8:any;
  _UserAgent_9:any;
  _UserNavigatorPlatform_10:any;
  _Platform_11:any;
  _UserConfig_12:any;
  _Config_13:any;
  _App_14:import7.App;
  _APP_INITIALIZER_15:any[];
  _ApplicationInitStatus_16:import8.ApplicationInitStatus;
  _Testability_17:import9.Testability;
  _ApplicationRef__18:import10.ApplicationRef_;
  _ApplicationRef_19:any;
  _IonicModule_20:import11.IonicModule;
  _AppModule_21:import1.AppModule;
  __Compiler_22:import12.Compiler;
  __ComponentResolver_23:any;
  __APP_ID_24:any;
  __DOCUMENT_25:any;
  __HAMMER_GESTURE_CONFIG_26:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_27:any[];
  __EventManager_28:import14.EventManager;
  __DomSharedStylesHost_29:import15.DomSharedStylesHost;
  __AnimationDriver_30:any;
  __DomRootRenderer_31:import16.DomRootRenderer_;
  __RootRenderer_32:any;
  __DomSanitizationService_33:import17.DomSanitizationServiceImpl;
  __SanitizationService_34:any;
  __ViewUtils_35:import18.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DynamicComponentLoader_38:import19.DynamicComponentLoader_;
  __SharedStylesHost_39:any;
  __RadioControlRegistry_40:import20.RadioControlRegistry;
  __FormBuilder_41:import21.FormBuilder;
  __UserRoot_42:any;
  __ActionSheetController_43:import22.ActionSheetController;
  __AlertController_44:import23.AlertController;
  __Form_45:import24.Form;
  __FeatureDetect_46:import25.FeatureDetect;
  __GestureController_47:import26.GestureController;
  __BrowserXhr_48:import27.BrowserXhr;
  __ResponseOptions_49:import28.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import29.XHRBackend;
  __RequestOptions_52:import30.BaseRequestOptions;
  __Http_53:any;
  __Keyboard_54:import31.Keyboard;
  __LoadingController_55:import32.LoadingController;
  __MenuController_56:import33.MenuController;
  __ModalController_57:import34.ModalController;
  __PickerController_58:import35.PickerController;
  __PopoverController_59:import36.PopoverController;
  __TapClick_60:import37.TapClick;
  __ToastController_61:import38.ToastController;
  __Translate_62:import39.Translate;
  __TransitionController_63:import40.TransitionController;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.AppRootNgFactory,
      E2EAppNgFactory,
      E2EAppNgFactory,
      E2EPageNgFactory
    ]
    ,[]);
  }
  get _Compiler_22():import12.Compiler {
    if ((this.__Compiler_22 == null)) { (this.__Compiler_22 = new import12.Compiler()); }
    return this.__Compiler_22;
  }
  get _ComponentResolver_23():any {
    if ((this.__ComponentResolver_23 == null)) { (this.__ComponentResolver_23 = this._Compiler_22); }
    return this.__ComponentResolver_23;
  }
  get _APP_ID_24():any {
    if ((this.__APP_ID_24 == null)) { (this.__APP_ID_24 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_24;
  }
  get _DOCUMENT_25():any {
    if ((this.__DOCUMENT_25 == null)) { (this.__DOCUMENT_25 = import4._document()); }
    return this.__DOCUMENT_25;
  }
  get _HAMMER_GESTURE_CONFIG_26():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_26 == null)) { (this.__HAMMER_GESTURE_CONFIG_26 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_26;
  }
  get _EVENT_MANAGER_PLUGINS_27():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_27 == null)) { (this.__EVENT_MANAGER_PLUGINS_27 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_26)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_27;
  }
  get _EventManager_28():import14.EventManager {
    if ((this.__EventManager_28 == null)) { (this.__EventManager_28 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_27,this.parent.get(import46.NgZone))); }
    return this.__EventManager_28;
  }
  get _DomSharedStylesHost_29():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_29 == null)) { (this.__DomSharedStylesHost_29 = new import15.DomSharedStylesHost(this._DOCUMENT_25)); }
    return this.__DomSharedStylesHost_29;
  }
  get _AnimationDriver_30():any {
    if ((this.__AnimationDriver_30 == null)) { (this.__AnimationDriver_30 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_30;
  }
  get _DomRootRenderer_31():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_31 == null)) { (this.__DomRootRenderer_31 = new import16.DomRootRenderer_(this._DOCUMENT_25,this._EventManager_28,this._DomSharedStylesHost_29,this._AnimationDriver_30)); }
    return this.__DomRootRenderer_31;
  }
  get _RootRenderer_32():any {
    if ((this.__RootRenderer_32 == null)) { (this.__RootRenderer_32 = import47._createConditionalRootRenderer(this._DomRootRenderer_31)); }
    return this.__RootRenderer_32;
  }
  get _DomSanitizationService_33():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_33 == null)) { (this.__DomSanitizationService_33 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_33;
  }
  get _SanitizationService_34():any {
    if ((this.__SanitizationService_34 == null)) { (this.__SanitizationService_34 = this._DomSanitizationService_33); }
    return this.__SanitizationService_34;
  }
  get _ViewUtils_35():import18.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import18.ViewUtils(this._RootRenderer_32,this._APP_ID_24,this._SanitizationService_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _DynamicComponentLoader_38():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_38 == null)) { (this.__DynamicComponentLoader_38 = new import19.DynamicComponentLoader_(this._Compiler_22)); }
    return this.__DynamicComponentLoader_38;
  }
  get _SharedStylesHost_39():any {
    if ((this.__SharedStylesHost_39 == null)) { (this.__SharedStylesHost_39 = this._DomSharedStylesHost_29); }
    return this.__SharedStylesHost_39;
  }
  get _RadioControlRegistry_40():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _FormBuilder_41():import21.FormBuilder {
    if ((this.__FormBuilder_41 == null)) { (this.__FormBuilder_41 = new import21.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _UserRoot_42():any {
    if ((this.__UserRoot_42 == null)) { (this.__UserRoot_42 = import1.E2EApp); }
    return this.__UserRoot_42;
  }
  get _ActionSheetController_43():import22.ActionSheetController {
    if ((this.__ActionSheetController_43 == null)) { (this.__ActionSheetController_43 = new import22.ActionSheetController(this._App_14)); }
    return this.__ActionSheetController_43;
  }
  get _AlertController_44():import23.AlertController {
    if ((this.__AlertController_44 == null)) { (this.__AlertController_44 = new import23.AlertController(this._App_14)); }
    return this.__AlertController_44;
  }
  get _Form_45():import24.Form {
    if ((this.__Form_45 == null)) { (this.__Form_45 = new import24.Form()); }
    return this.__Form_45;
  }
  get _FeatureDetect_46():import25.FeatureDetect {
    if ((this.__FeatureDetect_46 == null)) { (this.__FeatureDetect_46 = new import25.FeatureDetect()); }
    return this.__FeatureDetect_46;
  }
  get _GestureController_47():import26.GestureController {
    if ((this.__GestureController_47 == null)) { (this.__GestureController_47 = new import26.GestureController(this._App_14)); }
    return this.__GestureController_47;
  }
  get _BrowserXhr_48():import27.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import48._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import29.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import29.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import30.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import48.httpFactory(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _Keyboard_54():import31.Keyboard {
    if ((this.__Keyboard_54 == null)) { (this.__Keyboard_54 = new import31.Keyboard(this._Config_13,this._Form_45,this.parent.get(import46.NgZone))); }
    return this.__Keyboard_54;
  }
  get _LoadingController_55():import32.LoadingController {
    if ((this.__LoadingController_55 == null)) { (this.__LoadingController_55 = new import32.LoadingController(this._App_14)); }
    return this.__LoadingController_55;
  }
  get _MenuController_56():import33.MenuController {
    if ((this.__MenuController_56 == null)) { (this.__MenuController_56 = new import33.MenuController()); }
    return this.__MenuController_56;
  }
  get _ModalController_57():import34.ModalController {
    if ((this.__ModalController_57 == null)) { (this.__ModalController_57 = new import34.ModalController(this._App_14)); }
    return this.__ModalController_57;
  }
  get _PickerController_58():import35.PickerController {
    if ((this.__PickerController_58 == null)) { (this.__PickerController_58 = new import35.PickerController(this._App_14)); }
    return this.__PickerController_58;
  }
  get _PopoverController_59():import36.PopoverController {
    if ((this.__PopoverController_59 == null)) { (this.__PopoverController_59 = new import36.PopoverController(this._App_14)); }
    return this.__PopoverController_59;
  }
  get _TapClick_60():import37.TapClick {
    if ((this.__TapClick_60 == null)) { (this.__TapClick_60 = new import37.TapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))); }
    return this.__TapClick_60;
  }
  get _ToastController_61():import38.ToastController {
    if ((this.__ToastController_61 == null)) { (this.__ToastController_61 = new import38.ToastController(this._App_14)); }
    return this.__ToastController_61;
  }
  get _Translate_62():import39.Translate {
    if ((this.__Translate_62 == null)) { (this.__Translate_62 = new import39.Translate()); }
    return this.__Translate_62;
  }
  get _TransitionController_63():import40.TransitionController {
    if ((this.__TransitionController_63 == null)) { (this.__TransitionController_63 = new import40.TransitionController()); }
    return this.__TransitionController_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._ExceptionHandler_6 = import4._exceptionHandler();
    this._UserUrl_7 = import49.getWindowLocation();
    this._QueryParams_8 = import50.setupQueryParams(this._UserUrl_7);
    this._UserAgent_9 = import49.getWindowUserAgent();
    this._UserNavigatorPlatform_10 = import49.getWindowPlatform();
    this._Platform_11 = import51.setupPlatform(this._QueryParams_8,this._UserAgent_9,this._UserNavigatorPlatform_10,this.parent.get(import46.NgZone));
    this._UserConfig_12 = null;
    this._Config_13 = import52.setupConfig(this._UserConfig_12,this._QueryParams_8,this._Platform_11);
    this._App_14 = new import7.App(this._Config_13,this._Platform_11);
    this._APP_INITIALIZER_15 = [
      import53.setupProvideEvents(this._Platform_11),
      import37.setupTapClick(this._Config_13,this._App_14,this.parent.get(import46.NgZone))
    ]
    ;
    this._ApplicationInitStatus_16 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_15);
    this._Testability_17 = new import9.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__18 = new import10.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import54.Console),this,this._ExceptionHandler_6,this,this._ApplicationInitStatus_16,this.parent.get(import9.TestabilityRegistry,null),this._Testability_17);
    this._ApplicationRef_19 = this._ApplicationRef__18;
    this._IonicModule_20 = new import11.IonicModule(this.parent.get(import11.IonicModule,null),this._ApplicationRef_19);
    this._AppModule_21 = new import1.AppModule();
    return this._AppModule_21;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import55.ExceptionHandler)) { return this._ExceptionHandler_6; }
    if ((token === import50.UserUrl)) { return this._UserUrl_7; }
    if ((token === import50.QueryParams)) { return this._QueryParams_8; }
    if ((token === import51.UserAgent)) { return this._UserAgent_9; }
    if ((token === import51.UserNavigatorPlatform)) { return this._UserNavigatorPlatform_10; }
    if ((token === import51.Platform)) { return this._Platform_11; }
    if ((token === import52.UserConfig)) { return this._UserConfig_12; }
    if ((token === import52.Config)) { return this._Config_13; }
    if ((token === import7.App)) { return this._App_14; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_15; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_16; }
    if ((token === import9.Testability)) { return this._Testability_17; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__18; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_19; }
    if ((token === import11.IonicModule)) { return this._IonicModule_20; }
    if ((token === import1.AppModule)) { return this._AppModule_21; }
    if ((token === import12.Compiler)) { return this._Compiler_22; }
    if ((token === import56.ComponentResolver)) { return this._ComponentResolver_23; }
    if ((token === import43.APP_ID)) { return this._APP_ID_24; }
    if ((token === import57.DOCUMENT)) { return this._DOCUMENT_25; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_26; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_27; }
    if ((token === import14.EventManager)) { return this._EventManager_28; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_29; }
    if ((token === import58.AnimationDriver)) { return this._AnimationDriver_30; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_31; }
    if ((token === import59.RootRenderer)) { return this._RootRenderer_32; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_33; }
    if ((token === import60.SanitizationService)) { return this._SanitizationService_34; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import61.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import62.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_38; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_39; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import63.UserRoot)) { return this._UserRoot_42; }
    if ((token === import22.ActionSheetController)) { return this._ActionSheetController_43; }
    if ((token === import23.AlertController)) { return this._AlertController_44; }
    if ((token === import24.Form)) { return this._Form_45; }
    if ((token === import25.FeatureDetect)) { return this._FeatureDetect_46; }
    if ((token === import26.GestureController)) { return this._GestureController_47; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import65.Http)) { return this._Http_53; }
    if ((token === import31.Keyboard)) { return this._Keyboard_54; }
    if ((token === import32.LoadingController)) { return this._LoadingController_55; }
    if ((token === import33.MenuController)) { return this._MenuController_56; }
    if ((token === import34.ModalController)) { return this._ModalController_57; }
    if ((token === import35.PickerController)) { return this._PickerController_58; }
    if ((token === import36.PopoverController)) { return this._PopoverController_59; }
    if ((token === import37.TapClick)) { return this._TapClick_60; }
    if ((token === import38.ToastController)) { return this._ToastController_61; }
    if ((token === import39.Translate)) { return this._Translate_62; }
    if ((token === import40.TransitionController)) { return this._TransitionController_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__18.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
var renderType_E2EPage_Host:import66.RenderComponentType = null;
class _View_E2EPage_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EPage_0_4:import1.E2EPage;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage_Host0,renderType_E2EPage_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EPage_0_4 = new import1.E2EPage(compView_0.ref);
    this._appEl_0.initComponent(this._E2EPage_0_4,[],compView_0);
    compView_0.create(this._E2EPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EPage) && (0 === requestNodeIndex))) { return this._E2EPage_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._E2EPage_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_E2EPage_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EPage_Host === null)) { (renderType_E2EPage_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EPageNgFactory:import72.ComponentFactory<import1.E2EPage> = new import72.ComponentFactory<import1.E2EPage>('ng-component',viewFactory_E2EPage_Host0,import1.E2EPage);
const styles_E2EPage:any[] = [];
var renderType_E2EPage:import66.RenderComponentType = null;
class _View_E2EPage0 extends import67.AppView<import1.E2EPage> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _Content_0_4:import73.Content;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  private _appEl_5:import68.AppElement;
  _NgModel_5_4:import74.NgModel;
  _NgControl_5_5:any;
  _NgControlStatus_5_6:import75.NgControlStatus;
  _Searchbar_5_7:import76.Searchbar;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  private _appEl_16:import68.AppElement;
  _NgModel_16_4:import74.NgModel;
  _NgControl_16_5:any;
  _NgControlStatus_16_6:import75.NgControlStatus;
  _Searchbar_16_7:import76.Searchbar;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  private _appEl_27:import68.AppElement;
  _NgModel_27_4:import74.NgModel;
  _NgControl_27_5:any;
  _NgControlStatus_27_6:import75.NgControlStatus;
  _Searchbar_27_7:import76.Searchbar;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  private _appEl_38:import68.AppElement;
  _Searchbar_38_4:import76.Searchbar;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  private _appEl_43:import68.AppElement;
  _Searchbar_43_4:import76.Searchbar;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  private _appEl_47:import68.AppElement;
  _Button_47_4:import77.Button;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  private _expr_0:any;
  private _expr_7:any;
  private _expr_8:any;
  private _expr_9:any;
  private _expr_10:any;
  private _expr_11:any;
  private _expr_12:any;
  private _expr_13:any;
  private _expr_14:any;
  private _expr_15:any;
  private _expr_16:any;
  private _expr_17:any;
  private _expr_18:any;
  private _expr_19:any;
  private _expr_20:any;
  private _expr_21:any;
  private _expr_26:any;
  private _expr_27:any;
  private _expr_28:any;
  private _expr_29:any;
  private _expr_30:any;
  private _expr_31:any;
  private _expr_32:any;
  private _expr_33:any;
  private _expr_34:any;
  private _expr_35:any;
  private _expr_36:any;
  private _expr_37:any;
  private _expr_38:any;
  private _expr_39:any;
  private _expr_40:any;
  private _expr_41:any;
  private _expr_42:any;
  private _expr_43:any;
  private _expr_44:any;
  private _expr_49:any;
  private _expr_50:any;
  private _expr_51:any;
  private _expr_52:any;
  private _expr_53:any;
  private _expr_54:any;
  private _expr_55:any;
  private _expr_56:any;
  private _expr_57:any;
  private _expr_58:any;
  private _expr_59:any;
  private _expr_60:any;
  private _expr_61:any;
  private _expr_62:any;
  private _expr_63:any;
  private _expr_64:any;
  private _expr_65:any;
  private _expr_69:any;
  private _expr_70:any;
  private _expr_71:any;
  private _expr_72:any;
  private _expr_73:any;
  private _expr_74:any;
  private _expr_75:any;
  private _expr_79:any;
  private _expr_80:any;
  private _expr_81:any;
  private _expr_82:any;
  private _expr_83:any;
  private _expr_84:any;
  private _expr_85:any;
  private _expr_86:any;
  private _expr_88:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EPage0,renderType_E2EPage,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = import78.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import73.Content(new import79.ElementRef(this._el_0),this.parentInjector.get(import52.Config),this.parentInjector.get(import7.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import46.NgZone),this.parentInjector.get(import80.ViewController,null),this.parentInjector.get(import81.Tabs,null));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText(null,'\n  ',null);
    this._el_2 = this.renderer.createElement(null,'h5',null);
    this.renderer.setElementAttribute(this._el_2,'padding-left','');
    this._text_3 = this.renderer.createText(this._el_2,' Search - Default ',null);
    this._text_4 = this.renderer.createText(null,'\n  ',null);
    this._el_5 = this.renderer.createElement(null,'ion-searchbar',null);
    this.renderer.setElementAttribute(this._el_5,'debounce','500');
    this.renderer.setElementAttribute(this._el_5,'showCancelButton','');
    this._appEl_5 = new import68.AppElement(5,0,this,this._el_5);
    var compView_5:any = import82.viewFactory_Searchbar0(this.viewUtils,this.injector(5),this._appEl_5);
    this._NgModel_5_4 = new import74.NgModel(null,null,null,null);
    this._NgControl_5_5 = this._NgModel_5_4;
    this._NgControlStatus_5_6 = new import75.NgControlStatus(this._NgControl_5_5);
    this._Searchbar_5_7 = new import76.Searchbar(new import79.ElementRef(this._el_5),this.parentInjector.get(import52.Config),this._NgControl_5_5);
    this._appEl_5.initComponent(this._Searchbar_5_7,[],compView_5);
    compView_5.create(this._Searchbar_5_7,[],null);
    this._text_6 = this.renderer.createText(null,'\n\n  ',null);
    this._el_7 = this.renderer.createElement(null,'p',null);
    this.renderer.setElementAttribute(this._el_7,'padding-left','');
    this._text_8 = this.renderer.createText(this._el_7,'\n    defaultSearch: ',null);
    this._el_9 = this.renderer.createElement(this._el_7,'b',null);
    this._text_10 = this.renderer.createText(this._el_9,'',null);
    this._text_11 = this.renderer.createText(this._el_7,'\n  ',null);
    this._text_12 = this.renderer.createText(null,'\n\n  ',null);
    this._el_13 = this.renderer.createElement(null,'h5',null);
    this.renderer.setElementAttribute(this._el_13,'padding-left','');
    this._text_14 = this.renderer.createText(this._el_13,' Search - Custom Placeholder ',null);
    this._text_15 = this.renderer.createText(null,'\n  ',null);
    this._el_16 = this.renderer.createElement(null,'ion-searchbar',null);
    this.renderer.setElementAttribute(this._el_16,'placeholder','Filter Schedules');
    this.renderer.setElementAttribute(this._el_16,'showCancelButton','true');
    this.renderer.setElementAttribute(this._el_16,'type','number');
    this._appEl_16 = new import68.AppElement(16,0,this,this._el_16);
    var compView_16:any = import82.viewFactory_Searchbar0(this.viewUtils,this.injector(16),this._appEl_16);
    this._NgModel_16_4 = new import74.NgModel(null,null,null,null);
    this._NgControl_16_5 = this._NgModel_16_4;
    this._NgControlStatus_16_6 = new import75.NgControlStatus(this._NgControl_16_5);
    this._Searchbar_16_7 = new import76.Searchbar(new import79.ElementRef(this._el_16),this.parentInjector.get(import52.Config),this._NgControl_16_5);
    this._appEl_16.initComponent(this._Searchbar_16_7,[],compView_16);
    compView_16.create(this._Searchbar_16_7,[],null);
    this._text_17 = this.renderer.createText(null,'\n\n  ',null);
    this._el_18 = this.renderer.createElement(null,'p',null);
    this.renderer.setElementAttribute(this._el_18,'padding-left','');
    this._text_19 = this.renderer.createText(this._el_18,'\n    customPlaceholder: ',null);
    this._el_20 = this.renderer.createElement(this._el_18,'b',null);
    this._text_21 = this.renderer.createText(this._el_20,'',null);
    this._text_22 = this.renderer.createText(this._el_18,'\n  ',null);
    this._text_23 = this.renderer.createText(null,'\n\n  ',null);
    this._el_24 = this.renderer.createElement(null,'h5',null);
    this.renderer.setElementAttribute(this._el_24,'padding-left','');
    this._text_25 = this.renderer.createText(this._el_24,' Search - No Cancel Button ',null);
    this._text_26 = this.renderer.createText(null,'\n  ',null);
    this._el_27 = this.renderer.createElement(null,'ion-searchbar',null);
    this.renderer.setElementAttribute(this._el_27,'autocomplete','off');
    this.renderer.setElementAttribute(this._el_27,'autocorrect','off');
    this.renderer.setElementAttribute(this._el_27,'spellcheck','true');
    this.renderer.setElementAttribute(this._el_27,'type','text');
    this._appEl_27 = new import68.AppElement(27,0,this,this._el_27);
    var compView_27:any = import82.viewFactory_Searchbar0(this.viewUtils,this.injector(27),this._appEl_27);
    this._NgModel_27_4 = new import74.NgModel(null,null,null,null);
    this._NgControl_27_5 = this._NgModel_27_4;
    this._NgControlStatus_27_6 = new import75.NgControlStatus(this._NgControl_27_5);
    this._Searchbar_27_7 = new import76.Searchbar(new import79.ElementRef(this._el_27),this.parentInjector.get(import52.Config),this._NgControl_27_5);
    this._appEl_27.initComponent(this._Searchbar_27_7,[],compView_27);
    compView_27.create(this._Searchbar_27_7,[],null);
    this._text_28 = this.renderer.createText(null,'\n\n  ',null);
    this._el_29 = this.renderer.createElement(null,'p',null);
    this.renderer.setElementAttribute(this._el_29,'padding-left','');
    this._text_30 = this.renderer.createText(this._el_29,'\n    defaultCancel: ',null);
    this._el_31 = this.renderer.createElement(this._el_29,'b',null);
    this._text_32 = this.renderer.createText(this._el_31,'',null);
    this._text_33 = this.renderer.createText(this._el_29,'\n  ',null);
    this._text_34 = this.renderer.createText(null,'\n\n  ',null);
    this._el_35 = this.renderer.createElement(null,'h5',null);
    this.renderer.setElementAttribute(this._el_35,'padding-left','');
    this._text_36 = this.renderer.createText(this._el_35,' Search - Custom Cancel Button Danger ',null);
    this._text_37 = this.renderer.createText(null,'\n  ',null);
    this._el_38 = this.renderer.createElement(null,'ion-searchbar',null);
    this.renderer.setElementAttribute(this._el_38,'cancelButtonText','Really Long Cancel');
    this.renderer.setElementAttribute(this._el_38,'danger','');
    this.renderer.setElementAttribute(this._el_38,'showCancelButton','');
    this._appEl_38 = new import68.AppElement(38,0,this,this._el_38);
    var compView_38:any = import82.viewFactory_Searchbar0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Searchbar_38_4 = new import76.Searchbar(new import79.ElementRef(this._el_38),this.parentInjector.get(import52.Config),this.parentInjector.get(import83.NgControl,null));
    this._appEl_38.initComponent(this._Searchbar_38_4,[],compView_38);
    compView_38.create(this._Searchbar_38_4,[],null);
    this._text_39 = this.renderer.createText(null,'\n\n  ',null);
    this._el_40 = this.renderer.createElement(null,'h5',null);
    this.renderer.setElementAttribute(this._el_40,'padding-left','');
    this._text_41 = this.renderer.createText(this._el_40,' Search - Value passed ',null);
    this._text_42 = this.renderer.createText(null,'\n  ',null);
    this._el_43 = this.renderer.createElement(null,'ion-searchbar',null);
    this.renderer.setElementAttribute(this._el_43,'cancelButtonText','Really Long Cancel');
    this.renderer.setElementAttribute(this._el_43,'dark','');
    this.renderer.setElementAttribute(this._el_43,'showCancelButton','');
    this.renderer.setElementAttribute(this._el_43,'value','mysearch');
    this._appEl_43 = new import68.AppElement(43,0,this,this._el_43);
    var compView_43:any = import82.viewFactory_Searchbar0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Searchbar_43_4 = new import76.Searchbar(new import79.ElementRef(this._el_43),this.parentInjector.get(import52.Config),this.parentInjector.get(import83.NgControl,null));
    this._appEl_43.initComponent(this._Searchbar_43_4,[],compView_43);
    compView_43.create(this._Searchbar_43_4,[],null);
    this._text_44 = this.renderer.createText(null,'\n\n  ',null);
    this._el_45 = this.renderer.createElement(null,'p',null);
    this.renderer.setElementAttribute(this._el_45,'padding','');
    this._text_46 = this.renderer.createText(this._el_45,'\n    ',null);
    this._el_47 = this.renderer.createElement(this._el_45,'button',null);
    this.renderer.setElementAttribute(this._el_47,'block','');
    this._appEl_47 = new import68.AppElement(47,45,this,this._el_47);
    var compView_47:any = import84.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import77.Button(this.parentInjector.get(import52.Config),new import79.ElementRef(this._el_47),this.renderer,null);
    this._appEl_47.initComponent(this._Button_47_4,[],compView_47);
    this._text_48 = this.renderer.createText(null,'Change Value',null);
    compView_47.create(this._Button_47_4,[[].concat([this._text_48])],null);
    this._text_49 = this.renderer.createText(this._el_45,'\n  ',null);
    this._text_50 = this.renderer.createText(null,'\n',null);
    compView_0.create(this._Content_0_4,[
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_6,
        this._el_7,
        this._text_12,
        this._el_13,
        this._text_15,
        this._el_16,
        this._text_17,
        this._el_18,
        this._text_23,
        this._el_24,
        this._text_26,
        this._el_27,
        this._text_28,
        this._el_29,
        this._text_34,
        this._el_35,
        this._text_37,
        this._el_38,
        this._text_39,
        this._el_40,
        this._text_42,
        this._el_43,
        this._text_44,
        this._el_45,
        this._text_50
      ]
      ),
      [],
      []
    ]
    ,null);
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',null);
    this._expr_0 = import71.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'ngModelChange',this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'ionInput',this.eventHandler(this._handle_ionInput_5_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_5,'ionBlur',this.eventHandler(this._handle_ionBlur_5_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_5,'ionFocus',this.eventHandler(this._handle_ionFocus_5_3.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_5,'ionCancel',this.eventHandler(this._handle_ionCancel_5_4.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_5,'ionClear',this.eventHandler(this._handle_ionClear_5_5.bind(this)));
    this._expr_7 = import71.UNINITIALIZED;
    const subscription_0:any = this._NgModel_5_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_8 = import71.UNINITIALIZED;
    this._expr_9 = import71.UNINITIALIZED;
    this._expr_10 = import71.UNINITIALIZED;
    this._expr_11 = import71.UNINITIALIZED;
    this._expr_12 = import71.UNINITIALIZED;
    this._expr_13 = import71.UNINITIALIZED;
    this._expr_14 = import71.UNINITIALIZED;
    this._expr_15 = import71.UNINITIALIZED;
    this._expr_16 = import71.UNINITIALIZED;
    this._expr_17 = import71.UNINITIALIZED;
    this._expr_18 = import71.UNINITIALIZED;
    this._expr_19 = import71.UNINITIALIZED;
    this._expr_20 = import71.UNINITIALIZED;
    const subscription_1:any = this._Searchbar_5_7.ionInput.subscribe(this.eventHandler(this._handle_ionInput_5_1.bind(this)));
    const subscription_2:any = this._Searchbar_5_7.ionBlur.subscribe(this.eventHandler(this._handle_ionBlur_5_2.bind(this)));
    const subscription_3:any = this._Searchbar_5_7.ionFocus.subscribe(this.eventHandler(this._handle_ionFocus_5_3.bind(this)));
    const subscription_4:any = this._Searchbar_5_7.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_5_4.bind(this)));
    const subscription_5:any = this._Searchbar_5_7.ionClear.subscribe(this.eventHandler(this._handle_ionClear_5_5.bind(this)));
    this._expr_21 = import71.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_16,'ionInput',this.eventHandler(this._handle_ionInput_16_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_16,'ionCancel',this.eventHandler(this._handle_ionCancel_16_2.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_16,'ionClear',this.eventHandler(this._handle_ionClear_16_3.bind(this)));
    this._expr_26 = import71.UNINITIALIZED;
    const subscription_6:any = this._NgModel_16_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_27 = import71.UNINITIALIZED;
    this._expr_28 = import71.UNINITIALIZED;
    this._expr_29 = import71.UNINITIALIZED;
    this._expr_30 = import71.UNINITIALIZED;
    this._expr_31 = import71.UNINITIALIZED;
    this._expr_32 = import71.UNINITIALIZED;
    this._expr_33 = import71.UNINITIALIZED;
    this._expr_34 = import71.UNINITIALIZED;
    this._expr_35 = import71.UNINITIALIZED;
    this._expr_36 = import71.UNINITIALIZED;
    this._expr_37 = import71.UNINITIALIZED;
    this._expr_38 = import71.UNINITIALIZED;
    this._expr_39 = import71.UNINITIALIZED;
    this._expr_40 = import71.UNINITIALIZED;
    this._expr_41 = import71.UNINITIALIZED;
    this._expr_42 = import71.UNINITIALIZED;
    this._expr_43 = import71.UNINITIALIZED;
    const subscription_7:any = this._Searchbar_16_7.ionInput.subscribe(this.eventHandler(this._handle_ionInput_16_1.bind(this)));
    const subscription_8:any = this._Searchbar_16_7.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_16_2.bind(this)));
    const subscription_9:any = this._Searchbar_16_7.ionClear.subscribe(this.eventHandler(this._handle_ionClear_16_3.bind(this)));
    this._expr_44 = import71.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_27,'ngModelChange',this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_27,'ionInput',this.eventHandler(this._handle_ionInput_27_1.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_27,'ionCancel',this.eventHandler(this._handle_ionCancel_27_2.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_27,'ionClear',this.eventHandler(this._handle_ionClear_27_3.bind(this)));
    this._expr_49 = import71.UNINITIALIZED;
    const subscription_10:any = this._NgModel_27_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_50 = import71.UNINITIALIZED;
    this._expr_51 = import71.UNINITIALIZED;
    this._expr_52 = import71.UNINITIALIZED;
    this._expr_53 = import71.UNINITIALIZED;
    this._expr_54 = import71.UNINITIALIZED;
    this._expr_55 = import71.UNINITIALIZED;
    this._expr_56 = import71.UNINITIALIZED;
    this._expr_57 = import71.UNINITIALIZED;
    this._expr_58 = import71.UNINITIALIZED;
    this._expr_59 = import71.UNINITIALIZED;
    this._expr_60 = import71.UNINITIALIZED;
    this._expr_61 = import71.UNINITIALIZED;
    this._expr_62 = import71.UNINITIALIZED;
    this._expr_63 = import71.UNINITIALIZED;
    this._expr_64 = import71.UNINITIALIZED;
    const subscription_11:any = this._Searchbar_27_7.ionInput.subscribe(this.eventHandler(this._handle_ionInput_27_1.bind(this)));
    const subscription_12:any = this._Searchbar_27_7.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_27_2.bind(this)));
    const subscription_13:any = this._Searchbar_27_7.ionClear.subscribe(this.eventHandler(this._handle_ionClear_27_3.bind(this)));
    this._expr_65 = import71.UNINITIALIZED;
    var disposable_14:Function = this.renderer.listen(this._el_38,'ionInput',this.eventHandler(this._handle_ionInput_38_0.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_38,'ionCancel',this.eventHandler(this._handle_ionCancel_38_1.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_38,'ionClear',this.eventHandler(this._handle_ionClear_38_2.bind(this)));
    this._expr_69 = import71.UNINITIALIZED;
    this._expr_70 = import71.UNINITIALIZED;
    this._expr_71 = import71.UNINITIALIZED;
    this._expr_72 = import71.UNINITIALIZED;
    this._expr_73 = import71.UNINITIALIZED;
    this._expr_74 = import71.UNINITIALIZED;
    this._expr_75 = import71.UNINITIALIZED;
    const subscription_14:any = this._Searchbar_38_4.ionInput.subscribe(this.eventHandler(this._handle_ionInput_38_0.bind(this)));
    const subscription_15:any = this._Searchbar_38_4.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_38_1.bind(this)));
    const subscription_16:any = this._Searchbar_38_4.ionClear.subscribe(this.eventHandler(this._handle_ionClear_38_2.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_43,'ionInput',this.eventHandler(this._handle_ionInput_43_0.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_43,'ionCancel',this.eventHandler(this._handle_ionCancel_43_1.bind(this)));
    var disposable_19:Function = this.renderer.listen(this._el_43,'ionClear',this.eventHandler(this._handle_ionClear_43_2.bind(this)));
    this._expr_79 = import71.UNINITIALIZED;
    this._expr_80 = import71.UNINITIALIZED;
    this._expr_81 = import71.UNINITIALIZED;
    this._expr_82 = import71.UNINITIALIZED;
    this._expr_83 = import71.UNINITIALIZED;
    this._expr_84 = import71.UNINITIALIZED;
    this._expr_85 = import71.UNINITIALIZED;
    this._expr_86 = import71.UNINITIALIZED;
    const subscription_17:any = this._Searchbar_43_4.ionInput.subscribe(this.eventHandler(this._handle_ionInput_43_0.bind(this)));
    const subscription_18:any = this._Searchbar_43_4.ionCancel.subscribe(this.eventHandler(this._handle_ionCancel_43_1.bind(this)));
    const subscription_19:any = this._Searchbar_43_4.ionClear.subscribe(this.eventHandler(this._handle_ionClear_43_2.bind(this)));
    var disposable_20:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_88 = import71.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19,
      disposable_20
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5,
      subscription_6,
      subscription_7,
      subscription_8,
      subscription_9,
      subscription_10,
      subscription_11,
      subscription_12,
      subscription_13,
      subscription_14,
      subscription_15,
      subscription_16,
      subscription_17,
      subscription_18,
      subscription_19
    ]
    );
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import74.NgModel) && (5 === requestNodeIndex))) { return this._NgModel_5_4; }
    if (((token === import83.NgControl) && (5 === requestNodeIndex))) { return this._NgControl_5_5; }
    if (((token === import75.NgControlStatus) && (5 === requestNodeIndex))) { return this._NgControlStatus_5_6; }
    if (((token === import76.Searchbar) && (5 === requestNodeIndex))) { return this._Searchbar_5_7; }
    if (((token === import74.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_4; }
    if (((token === import83.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_5; }
    if (((token === import75.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_6; }
    if (((token === import76.Searchbar) && (16 === requestNodeIndex))) { return this._Searchbar_16_7; }
    if (((token === import74.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_4; }
    if (((token === import83.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_5; }
    if (((token === import75.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_6; }
    if (((token === import76.Searchbar) && (27 === requestNodeIndex))) { return this._Searchbar_27_7; }
    if (((token === import76.Searchbar) && (38 === requestNodeIndex))) { return this._Searchbar_38_4; }
    if (((token === import76.Searchbar) && (43 === requestNodeIndex))) { return this._Searchbar_43_4; }
    if (((token === import77.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_47_4; }
    if (((token === import73.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import71.SimpleChange} = null;
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    changes = null;
    const currVal_7:any = this.context.defaultSearch;
    if (import69.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgModel_5_4.model = currVal_7;
      if ((changes === null)) { (changes = {}); }
      changes['model'] = new import71.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== null)) { this._NgModel_5_4.ngOnChanges(changes); }
    const currVal_14:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Searchbar_5_7.showCancelButton = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = '500';
    if (import69.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Searchbar_5_7.debounce = currVal_15;
      this._expr_15 = currVal_15;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_5_7.ngOnInit(); }
    changes = null;
    const currVal_26:any = this.context.customPlaceholder;
    if (import69.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_16_4.model = currVal_26;
      if ((changes === null)) { (changes = {}); }
      changes['model'] = new import71.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    if ((changes !== null)) { this._NgModel_16_4.ngOnChanges(changes); }
    const currVal_33:any = 'true';
    if (import69.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._Searchbar_16_7.showCancelButton = currVal_33;
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = 'Filter Schedules';
    if (import69.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._Searchbar_16_7.placeholder = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this.context.isAutocomplete;
    if (import69.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._Searchbar_16_7.autocomplete = currVal_35;
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this.context.isAutocorrect;
    if (import69.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._Searchbar_16_7.autocorrect = currVal_36;
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this.context.isSpellcheck;
    if (import69.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this._Searchbar_16_7.spellcheck = currVal_37;
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = 'number';
    if (import69.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._Searchbar_16_7.type = currVal_38;
      this._expr_38 = currVal_38;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_16_7.ngOnInit(); }
    changes = null;
    const currVal_49:any = this.context.defaultCancel;
    if (import69.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this._NgModel_27_4.model = currVal_49;
      if ((changes === null)) { (changes = {}); }
      changes['model'] = new import71.SimpleChange(this._expr_49,currVal_49);
      this._expr_49 = currVal_49;
    }
    if ((changes !== null)) { this._NgModel_27_4.ngOnChanges(changes); }
    const currVal_56:any = 'off';
    if (import69.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this._Searchbar_27_7.autocomplete = currVal_56;
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = 'off';
    if (import69.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this._Searchbar_27_7.autocorrect = currVal_57;
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = 'true';
    if (import69.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this._Searchbar_27_7.spellcheck = currVal_58;
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = 'text';
    if (import69.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this._Searchbar_27_7.type = currVal_59;
      this._expr_59 = currVal_59;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_27_7.ngOnInit(); }
    const currVal_69:any = 'Really Long Cancel';
    if (import69.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this._Searchbar_38_4.cancelButtonText = currVal_69;
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this._Searchbar_38_4.showCancelButton = currVal_70;
      this._expr_70 = currVal_70;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_38_4.ngOnInit(); }
    const currVal_79:any = 'Really Long Cancel';
    if (import69.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this._Searchbar_43_4.cancelButtonText = currVal_79;
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this._Searchbar_43_4.showCancelButton = currVal_80;
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = 'mysearch';
    if (import69.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this._Searchbar_43_4.value = currVal_81;
      this._expr_81 = currVal_81;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Searchbar_43_4.ngOnInit(); }
    changed = false;
    const currVal_88:any = '';
    if (import69.checkBinding(throwOnChange,this._expr_88,currVal_88)) {
      this._Button_47_4.block = currVal_88;
      changed = true;
      this._expr_88 = currVal_88;
    }
    if (changed) { this._appEl_47.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Button_47_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_47_4.ngAfterContentInit(); }
      this._Button_47_4.ngAfterContentChecked();
    }
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_8:any = this._NgControlStatus_5_6.ngClassUntouched;
    if (import69.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_5_6.ngClassTouched;
    if (import69.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_5_6.ngClassPristine;
    if (import69.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_5_6.ngClassDirty;
    if (import69.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_5_6.ngClassValid;
    if (import69.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_5_6.ngClassInvalid;
    if (import69.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._Searchbar_5_7._value;
    if (import69.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_5,'searchbar-has-value',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._Searchbar_5_7._isActive;
    if (import69.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_5,'searchbar-active',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Searchbar_5_7.showCancelButton;
    if (import69.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_5,'searchbar-show-cancel',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._Searchbar_5_7.shouldAlignLeft();
    if (import69.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_5,'searchbar-left-aligned',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._Searchbar_5_7._sbHasFocus;
    if (import69.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_5,'searchbar-has-focus',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import69.interpolate(1,'',this.context.defaultSearch,'');
    if (import69.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_10,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_27:any = this._NgControlStatus_16_6.ngClassUntouched;
    if (import69.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_16_6.ngClassTouched;
    if (import69.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_16_6.ngClassPristine;
    if (import69.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_16_6.ngClassDirty;
    if (import69.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_16_6.ngClassValid;
    if (import69.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_16_6.ngClassInvalid;
    if (import69.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_39:any = this._Searchbar_16_7._value;
    if (import69.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_16,'searchbar-has-value',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._Searchbar_16_7._isActive;
    if (import69.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_16,'searchbar-active',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._Searchbar_16_7.showCancelButton;
    if (import69.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_16,'searchbar-show-cancel',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._Searchbar_16_7.shouldAlignLeft();
    if (import69.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_16,'searchbar-left-aligned',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._Searchbar_16_7._sbHasFocus;
    if (import69.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_16,'searchbar-has-focus',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = import69.interpolate(1,'',this.context.customPlaceholder,'');
    if (import69.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setText(this._text_21,currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_50:any = this._NgControlStatus_27_6.ngClassUntouched;
    if (import69.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_27_6.ngClassTouched;
    if (import69.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_27_6.ngClassPristine;
    if (import69.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_27_6.ngClassDirty;
    if (import69.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_27_6.ngClassValid;
    if (import69.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_27_6.ngClassInvalid;
    if (import69.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_60:any = this._Searchbar_27_7._value;
    if (import69.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_27,'searchbar-has-value',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = this._Searchbar_27_7._isActive;
    if (import69.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_27,'searchbar-active',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this._Searchbar_27_7.showCancelButton;
    if (import69.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_27,'searchbar-show-cancel',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this._Searchbar_27_7.shouldAlignLeft();
    if (import69.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_27,'searchbar-left-aligned',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._Searchbar_27_7._sbHasFocus;
    if (import69.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_27,'searchbar-has-focus',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = import69.interpolate(1,'',this.context.defaultCancel,'');
    if (import69.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setText(this._text_32,currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_71:any = this._Searchbar_38_4._value;
    if (import69.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_38,'searchbar-has-value',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_72:any = this._Searchbar_38_4._isActive;
    if (import69.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementClass(this._el_38,'searchbar-active',currVal_72);
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this._Searchbar_38_4.showCancelButton;
    if (import69.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementClass(this._el_38,'searchbar-show-cancel',currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this._Searchbar_38_4.shouldAlignLeft();
    if (import69.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementClass(this._el_38,'searchbar-left-aligned',currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = this._Searchbar_38_4._sbHasFocus;
    if (import69.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementClass(this._el_38,'searchbar-has-focus',currVal_75);
      this._expr_75 = currVal_75;
    }
    const currVal_82:any = this._Searchbar_43_4._value;
    if (import69.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementClass(this._el_43,'searchbar-has-value',currVal_82);
      this._expr_82 = currVal_82;
    }
    const currVal_83:any = this._Searchbar_43_4._isActive;
    if (import69.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementClass(this._el_43,'searchbar-active',currVal_83);
      this._expr_83 = currVal_83;
    }
    const currVal_84:any = this._Searchbar_43_4.showCancelButton;
    if (import69.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setElementClass(this._el_43,'searchbar-show-cancel',currVal_84);
      this._expr_84 = currVal_84;
    }
    const currVal_85:any = this._Searchbar_43_4.shouldAlignLeft();
    if (import69.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this.renderer.setElementClass(this._el_43,'searchbar-left-aligned',currVal_85);
      this._expr_85 = currVal_85;
    }
    const currVal_86:any = this._Searchbar_43_4._sbHasFocus;
    if (import69.checkBinding(throwOnChange,this._expr_86,currVal_86)) {
      this.renderer.setElementClass(this._el_43,'searchbar-has-focus',currVal_86);
      this._expr_86 = currVal_86;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Searchbar_5_7.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_16_7.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_27_7.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_38_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_43_4.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._NgModel_5_4.ngOnDestroy();
    this._NgModel_16_4.ngOnDestroy();
    this._NgModel_27_4.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_ngModelChange_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.defaultSearch = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.triggerInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionBlur_5_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputBlurred($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionFocus_5_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputFocused($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_5_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancelSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionClear_5_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClearSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.customPlaceholder = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.triggerInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancelSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionClear_16_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClearSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.defaultCancel = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_27_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.triggerInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_27_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancelSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionClear_27_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClearSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.triggerInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_38_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancelSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionClear_38_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClearSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.triggerInput($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionCancel_43_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onCancelSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionClear_43_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClearSearchbar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.changeValue()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_E2EPage0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EPage> {
  if ((renderType_E2EPage === null)) { (renderType_E2EPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/searchbar/basic/main.html',0,import85.ViewEncapsulation.None,styles_E2EPage,{})); }
  return new _View_E2EPage0(viewUtils,parentInjector,declarationEl);
}
var renderType_E2EApp_Host:import66.RenderComponentType = null;
class _View_E2EApp_Host0 extends import67.AppView<any> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _E2EApp_0_4:import1.E2EApp;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp_Host0,renderType_E2EApp_Host,import70.ViewType.HOST,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_E2EApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._E2EApp_0_4 = new import1.E2EApp();
    this._appEl_0.initComponent(this._E2EApp_0_4,[],compView_0);
    compView_0.create(this._E2EApp_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.E2EApp) && (0 === requestNodeIndex))) { return this._E2EApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_E2EApp_Host0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<any> {
  if ((renderType_E2EApp_Host === null)) { (renderType_E2EApp_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_E2EApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const E2EAppNgFactory:import72.ComponentFactory<import1.E2EApp> = new import72.ComponentFactory<import1.E2EApp>('ng-component',viewFactory_E2EApp_Host0,import1.E2EApp);
const styles_E2EApp:any[] = [];
var renderType_E2EApp:import66.RenderComponentType = null;
class _View_E2EApp0 extends import67.AppView<import1.E2EApp> {
  _el_0:any;
  private _appEl_0:import68.AppElement;
  _Nav_0_4:import86.Nav;
  private _expr_0:any;
  constructor(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement) {
    super(_View_E2EApp0,renderType_E2EApp,import70.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import71.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import68.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import68.AppElement(0,null,this,this._el_0);
    var compView_0:any = import87.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import86.Nav(this.parentInjector.get(import80.ViewController,null),this.parentInjector.get(import88.NavControllerBase,null),this.parentInjector.get(import7.App),this.parentInjector.get(import52.Config),this.parentInjector.get(import31.Keyboard),new import79.ElementRef(this._el_0),this.parentInjector.get(import46.NgZone),this.renderer,this.parentInjector.get(import89.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import71.UNINITIALIZED;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import86.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.root;
    if (import69.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_E2EApp0(viewUtils:import69.ViewUtils,parentInjector:import41.Injector,declarationEl:import68.AppElement):import67.AppView<import1.E2EApp> {
  if ((renderType_E2EApp === null)) { (renderType_E2EApp = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/ionic/test/searchbar/basic/AppModule.ts class E2EApp - inline template',0,import85.ViewEncapsulation.None,styles_E2EApp,{})); }
  return new _View_E2EApp0(viewUtils,parentInjector,declarationEl);
}