/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './AppModule';
import * as import41 from '@angular/core/src/di/injector';
import * as import67 from '@angular/core/src/linker/view';
import * as import68 from '@angular/core/src/linker/element';
import * as import69 from '@angular/core/src/linker/view_utils';
import * as import73 from '@angular/core/src/linker/component_factory';
export declare const AppModuleNgFactory: import0.NgModuleFactory<import1.AppModule>;
export declare const MainPageNgFactory: import73.ComponentFactory<import1.MainPage>;
export declare function viewFactory_MainPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.MainPage>;
export declare const SearchPageNgFactory: import73.ComponentFactory<import1.SearchPage>;
export declare function viewFactory_SearchPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.SearchPage>;
export declare const DetailPageNgFactory: import73.ComponentFactory<import1.DetailPage>;
export declare function viewFactory_DetailPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.DetailPage>;
export declare const TabsPageNgFactory: import73.ComponentFactory<import1.TabsPage>;
export declare function viewFactory_TabsPage0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.TabsPage>;
export declare const E2EAppNgFactory: import73.ComponentFactory<import1.E2EApp>;
export declare function viewFactory_E2EApp0(viewUtils: import69.ViewUtils, parentInjector: import41.Injector, declarationEl: import68.AppElement): import67.AppView<import1.E2EApp>;
